### ISSUE TITLE
Save only delta on update

### ISSUE THREAD

**Issue by asxcandrew** [scrumpy/tiptap#107]
There are few ways how to keep notes on the backend. I have chosen Medium`s one.
Short investigation showed me some facts:

- They keep stories as json probably in noSQL database
- They only send delta on each update and probably merge them on backend.

`POST https://medium.com/p/7cbc4898d666/deltas?logLockId=4338`
<img width="239" alt="2018-11-23 20 35 45" src="https://user-images.githubusercontent.com/1057914/48957128-780f4b80-ef5f-11e8-8d57-a18b9897b004.png">

Are there posibility to get json delta of prosemirror`s data on update, instead of full data?

**Comment by philippkuehn** [comment]
In v1.7.0 there is also a `transaction` for the updated event.
