### ISSUE TITLE
Setting content while typing

### ISSUE THREAD

**Issue by ilicmarko** [scrumpy/tiptap#110]
This a question not an issue and should be marked as one.

This is maybe pushing the editor to its limits but I am trying to live update the content while typing. Normally this doesn't work because when the content is update the cursor will mode to the start (expected behavior of `contenteditable`).

Is there a way to 'hack' it and find a workaround. I had and idea to `debounce` the typing, call the highlighter after the typing start but I don't know how to return the cursor to original position.

Here was my idea:
```javascript
onUpdate: ({ getHTML }) => {
	this.editMe(getHTML())
},
```
editMe function
```javascript
editMe: _debounce(function(html) {
  let replacedContent = html.replace(spamWordsReges, '<strong>marko</strong>')
  this.editor.setContent(replacedContent)
  this.editor.focus()
}, 1000)
```

**Why would someone need this?**
I am trying to build a bad word highlighter. When a user types a bad word I mark it with a `<span>` or `<mark>`.
This is for example how Grammarly works (https://app.grammarly.com/). From what I saw they use Quill but didn't put much research into how (https://github.com/quilljs/quill)

Thank you advance if anyone has and idea how to solve this.

**Comment by philippkuehn** [comment]
Hey @ilicmarko. When using `setContent` the complete state will be replaced so focus will be lost. It's definitely possible with a better merge strategy (for example used in the [collab example](http://prosemirror.net/docs/guide/#collab)).

But especially for your problem you can use use the [decorations](http://prosemirror.net/docs/ref/#view.Decorations) feature of ProseMirror. You can wrap content with a `<span>` but it's not included in the state.

Decorations are also used for [suggestions](https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap-extensions/src/plugins/Suggestions.js#L227) where it wraps content in a span while typing a mention.

<img width="672" alt="aognrkzl92" src="https://user-images.githubusercontent.com/2500670/49520195-fdb9c200-f8a2-11e8-8fb9-1f7d3ef366f9.png">

**Comment by ilicmarko** [comment]
@philippkuehn I saw that, and I know I need to build it like suggestions but Prosemirror is not available to us as this is a wrapper around it. I was thinking of a Tip-tap solution. Where somehow you expose either the `Decoration` or cursor so we can insert DOM after/before cursor.

Thank you for the reply, I will maybe try and go forward with this or change the feature so it doesn't work like (while typing).

**Comment by philippkuehn** [comment]
You can do anything with tiptap aswell. You just have to write you own extension to pass prosemirror plugins.

```js
import { Extension, Plugin } from 'tiptap'

export default class BadWords extends Extension {

  get name() {
    return 'badWords'
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          decorations(editorState) {
            // handle decorations
          },
        },
      }),
    ]
  }

}
```

**Comment by philippkuehn** [comment]
Hmm, I don't get it. Is it working now or not? To add a prosemirror plugin is exactly the way I would do it. Tiptap is still a wrapper around prosemirror for adding custom nodes easier but I can't abstract the core api from prosemirror.

**Comment by ilicmarko** [comment]
It works, but I wanted to write this exclusively in Tiptap, because now I am including Prosemirror. But it is ok.

```
import { Plugin, PluginKey } from 'prosemirror-state'
import { Decoration, DecorationSet } from 'prosemirror-view'
```
