### ISSUE TITLE
Change editable option on the fly

### ISSUE THREAD

**Issue by Zanzavar** [scrumpy/tiptap#111]
Hi, is there a way to set the editor editable option to switch on/off on the fly? e.g i would like to set the editor from read-only to editable when the user double-clicks on it.

Here is a clone of your read-only example with the addition of the double click handler but it doesn't seem to work:
https://codesandbox.io/s/w6rw2wy6ml

Any ideas what i am missing?

**Comment by gmickel** [comment]
Hi there!

This works for me:

```
this.editor.setOptions({editable: false});
this.editor.setOptions({editable: true});
```

**Comment by panayotisk** [comment]
Hello,
I guess we need to call ProseMirror's view update afterwards. The following worked for me (checking with chrome dev tools for immediate DOM update)
```
this.editor.options.editable = true;
this.editor.view.update(this.editor.view.props); 
```
Gordon, beware! I am afraid that setOptions may also modify other options you set, like for example an onBlur() callback function you may have passed to the options object. Check this carefully please.

**Comment by gmickel** [comment]
@panayotisk You're absolutely right.
I didn't mention that I was doing some other crazy stuff with the setOptions method. But thanks for the warning!

**Comment by frkn-aydn** [comment]
I can change the editable state and if editable is true i can change the content very easy. I have a problem with editor menu bar. Its not working when i change editable state with setOptions function. How can make this work.

**Comment by philippkuehn** [comment]
Yeah, I'll add this feature.

**Comment by frkn-aydn** [comment]
to get around this problem, I started the code as "editable: true". Before I render the editor, I change the editable state to false and rendered like this. That's fixed my editor menu bar problem. @philippkuehn

**Comment by philippkuehn** [comment]
This should be fixed in the latest version. You can now use `editor.setOptions({editable: false})`

**Comment by jans-y** [comment]
Hi guys,

There is a problem with menuBubble. When I init the editor with editable false, then update it to true, it's not possible to manipulate the link, I have copied the code from official demo.

I have solved this by initialising editor as { editable: true } and the immediately setting it to { editable: false }

Have a nice day.

**Comment by Azim-Ahmed** [comment]
`  useEffect(() => {

    if(editor){
      editor.setEditable(false);
    }
  }, [ editor]);
  
  `
if you find this useful.

**Comment by mathix420** [comment]
In my case, I was using custom vue component as block with conditional style based on the `editable` property. It was not updating when doing `setEditable` or `setOptions`.

I ended up using this solutions:
```ts
editor.setEditable(true);
editor.createNodeViews();
```

**Comment by Judge-Paul** [comment]
Can confirm this worked for me as well
``` javascript
useEffect(() => {
	if (editor) {
		editor.setEditable(editable);
	}
}, [editable]);
```
