### ISSUE TITLE
ColorPicker extension

### ISSUE THREAD

**Issue by jonasbiberg** [scrumpy/tiptap#128]
I would like to have a extension where you can change the color of the text.

**Comment by HugoCrd** [comment]
Hi!

We're considering implementing Tiptap in our product as it's very nice an elegant (kudos @philippkuehn 🥇).
If we decide to give it a go, we could definitely invest a little bit of time implementing this extension and would happily give it back to the community.
@philippkuehn do you think this should be contributed as a separate extension or could be part of this repository?

When reading #80 I was under the impression you wanted most extra features developed as third party extensions.

Best!

**Comment by philippkuehn** [comment]
Hey, sorry but I still don't plan to put this into the core. Maybe someone try to create an extension for it.

**Comment by jeremyphillipsfti** [comment]
@HugoCrd were you able to implement this as an extension?

**Comment by dolbex** [comment]
Same - any update with this @HugoCrd

**Comment by akhoury** [comment]
+1

**Comment by vladansn** [comment]
+1

**Comment by dolbex** [comment]
I ended up doing something like this: https://github.com/devisephp/interface/blob/master/src/components/utilities/wysiwyg/tiptap/extensions/TextColor.js

**Comment by rob-sullivan** [comment]
@dolbex any chance you could explain how to implement the color picker? details on extensions don't say how to set them up only point to prosemirror https://prosemirror.net/docs/guide/

**Comment by dolbex** [comment]
@rob-sullivan - it's been a while since I looked at this but looking through the source I have a vue component that opens up and allows you to pick a color and then apply it with the following function:

```
    applyTextColor (commands) {
      const { r, g, b, a } = this.textColor.rgba;
      commands.textcolor({ color: `rgba(${r},${g},${b},${a})` })
      this.showTextColorPicker = false
    },
```

This is from: https://github.com/devisephp/interface/blob/master/src/components/utilities/Wysiwyg.vue
