### ISSUE TITLE
upload image from local file system and set it as base64encoded string

### ISSUE THREAD

**Issue by osman-mohamad** [scrumpy/tiptap#129]
how to upload image from local file system and set it as base64encoded string inside the produced html ?

**Comment by ilicmarko** [comment]
This issue is not related to Tiptap, you have to provide the string editor can't do that for you.

As I said before, please google it... https://www.npmjs.com/package/image-to-base64

**Comment by philippkuehn** [comment]
Like said in #89, there is already an example for dropping and converting to base64 at the [official example](https://tiptap.scrumpy.io/images). It's up to you to add a button for selecting from your local file system.

**Comment by kennethcode** [comment]
> Like said in #89, there is already an example for dropping and converting to base64 at the [official example](https://tiptap.scrumpy.io/images). It's up to you to add a button for selecting from your local file system.

The provided link is broken.
