### ISSUE TITLE
Nuxt JS document is not defined

### ISSUE THREAD

**Issue by AlexanderBelkevich** [scrumpy/tiptap#131]
Hi!
Please help me! Why in nuxt js project error 'document is not defined'?
I tried installing through plugins and ssr: false - not working(

**Comment by AveryBibeau** [comment]
I'm using tiptap with Nuxt and have gotten it to work by wrapping the editor in a `<no-ssr>` tag and initializing the editor in the component's `mounted` rather than in `data`. I don't have it installed as a plugin, just imported in an editor component

**Comment by AlexanderBelkevich** [comment]
Are you using tiptap-extensions too? The problem appears when using it. In any case, I will try your advice today :)

**Comment by AlexanderBelkevich** [comment]
> I'm using tiptap with Nuxt and have gotten it to work by wrapping the editor in a `<no-ssr>` tag and initializing the editor in the component's `mounted` rather than in `data`. I don't have it installed as a plugin, just imported in an editor component

Thanks. It's working! The problem was 'data'

**Comment by furkanmutlu** [comment]
> I'm using tiptap with Nuxt and have gotten it to work by wrapping the editor in a `<no-ssr>` tag and initializing the editor in the component's `mounted` rather than in `data`. I don't have it installed as a plugin, just imported in an editor component

Can you please share the updated code? I didnt understand how to initializing the editor in the mounted? How did you do that please help :(

**Comment by eslamoo** [comment]
> > I'm using tiptap with Nuxt and have gotten it to work by wrapping the editor in a `<no-ssr>` tag and initializing the editor in the component's `mounted` rather than in `data`. I don't have it installed as a plugin, just imported in an editor component
> 
> Thanks. It's working! The problem was 'data'

@AlexanderBelkevich Please can you tell me how to implement this solution, I've been tried every possible way with no results. 
thanks in advance

**Comment by hok-wtag** [comment]
`<template>
  <no-ssr>
    <editor-content :editor="editor" />
  </no-ssr>
</template>

<script>
import { Editor, EditorContent } from 'tiptap'

export default {
  mounted() {
    this.editor = new Editor({
      content: '<p>This is just a boring paragraph</p>'
    })
  },
  components: {
    EditorContent
  },
  data() {
    return {
      editor: null
    }
  },
  beforeDestroy() {
    // Always destroy your editor instance when it's no longer needed
    this.editor.destroy()
  }
}
</script>
`

**Comment by maxcaplan** [comment]
Hey, I know this issue has been closed for a while, but I think it's worthwhile for anyone referencing this that the `<no-ssr>` is deprecated in favor of the new `<client-only>` component for Nuxt < v2.9.0.

You can read the docs [here](https://nuxtjs.org/api/components-client-only/)

**Comment by bmkubia** [comment]
Anyone have any luck rendering the contents of the editor at server time? Ran into this issue but unfortunately my use case has me wanting the Editor to render the content on the server.

**Comment by maxcaplan** [comment]
@bmkubia I don't quite understand your problem. Are you talking about rendering the full Tip Tap editor on the server-side? Or are you talking about rendering the actual HTML content of the editor server-side?

**Comment by bmkubia** [comment]
@maxcaplan Yes but v-html is prone to XSS, I assumed the tiptap editor takes care of that factor which is why I am displaying the content inside of another Editor instance and would like to on the server side as well. 

I guess I also could just write sanitization myself server side but I was hoping this lib had it included.

**Comment by kamilbeben** [comment]
@bmkubia I'm struggling with the very same thing, but in my case using `v-html` is not even an option because i persist editor's json value, not html (the output of `getJSON` instead of `getHTML`). Have you had any luck finding a solution?

**Comment by hanspagel** [comment]
@bmkubia That works with the upcoming v2. :) https://github.com/ueberdosis/tiptap/issues/821#issuecomment-686536616
