### ISSUE TITLE
How to copy a node

### ISSUE THREAD

**Issue by wade41** [scrumpy/tiptap#132]
Hey,

Love the project so far.

I'm currently trying to have both the regular @ mention functionality as well as using it with a #. So basically, I have to use the same node twice. However I found that this isn't possible thanks to issue #75 

You mention there that you can copy a node and by changing that getting the desired functionality, which in my case is using a # to add tags to a post and @ to mention people.

However, it is not clear to me as of where I have to copy this node to and what steps I have to take to get to the point where I can import the custom node in my editor. Could you elaborate on that?

Thanks.

**Comment by Chrissi2812** [comment]
Hey @wade41,

there is already PR #123 which will do what you want once it's merged 🎉

**Comment by wade41** [comment]
Ah I see, thanks for letting me know. I'll close the issue, looking forward to the merge 👍
