### ISSUE TITLE
page scrolls down on long text paste

### ISSUE THREAD

**Issue by jgabis** [scrumpy/tiptap#142]
First of all thank you for creating tiptap! I am trying to use it in a project but I have a problem with handling paste of long texts. If there is more content on the page below the editor, and editor has fixed height and overflow: scroll, then after paste the whole page scrolls down to the point where the text would have ended without overflow property.

This is probably the issue of prosemirror handleScrollToSelection function (or something similar), but there should be a way to disable this behaviour on paste.

Here is a fiddle - try pasting a very long text into the editor: [https://codesandbox.io/s/52940pk6zx](https://codesandbox.io/s/52940pk6zx)

**Comment by philippkuehn** [comment]
Hey @jgabis, I think this is related to prosemirror.

**Comment by philippkuehn** [comment]
Closing this. Please open an issue at prosemirror.
