### ISSUE TITLE
Always having an empty paragraph at the end of the document

### ISSUE THREAD

**Issue by holtwick** [scrumpy/tiptap#143]
In some scenarios it is almost impossible to put a cursor after the last element, like for the "Embed" example: https://tiptap.scrumpy.io/embeds

It would be great to always have an empty trailing paragraph to avoid this problem.

**Comment by philippkuehn** [comment]
Yeah that sounds good.

**Comment by drewtownchi** [comment]
I wanted to do something similar in my controlled tiptap component.  I am handling this in the `onUpdate` method

```javascript
        onUpdate: ({ getHTML }) => {
          let state = getHTML();
          if (!state.endsWith("</p>")) {
            state += "<p></p>";
            this.editor.setContent(state);
          }

          this.$emit("input", state);
        },
````

**Comment by holtwick** [comment]
@philippkuehn do you think that an approach like the one used for https://tiptap.scrumpy.io/title would be a smart way to solve this issue?

**Comment by philippkuehn** [comment]
Hmm, I don't think so. But I still don't know how to solve this problem 😅

**Comment by holtwick** [comment]
Thanks for the feedback. I tried to implement it this way, but indeed I didn't get it working correctly. The problem was that this *empty* last element would not automatically change to a regular `paragraph` element when typing in it.

I asked on the ProseMirror list, maybe they have an idea: https://discuss.prosemirror.net/t/empty-trailing-block/2072

**Comment by ryanbliss** [comment]
As mentioned in the linked Prosemirror thread that @holtwick opened, gapcursor does kind of work (you just need to set showGapCursor: true on the node), but it's far from a complete solution. You can change the CSS for the cursor, but I was having trouble making it appear consistently. Now it only really appears when you are on the selection point after the node, rather than on the node itself; this would be a fine solution if there was an intuitive way to present this to the user, but I haven't figured that part out. 

Really what I settled on is this:
```
// Catch events on stopEvent to ensure line breaks work as expected
// This works well for text fields
stopEvent(e) {
    if (e.inputType) {
      if (e.inputType === 'insertLineBreak') {
        return false;
      }
    } else if (e.key) {
      if (['Enter', 'ArrowDown', 'ArrowUp'].includes(e.key)) {
        return false;
      }
    }
    return true;
}
// Enable gapCursor and set selectable to
get schema() {
    return {
      attrs: {  ... },
      group: 'block',
      selectable: true,
      showGapCursor: true,
      atom: true, // not quite sure why I needed this, but it seemed to help
     ...
  }
```

Finally, in my component, I set the cursor position to the NodeView when the `<input>` was focused. This will obviously differ depending on your use case.
```
fieldFocused() {
          this.view.dispatch(this.view.state.tr
            .setSelection(NodeSelection
              .create(this.view.state.doc, this.getPos())));
        },
```

Again, far from a perfect solution, but hopefully this will help others looking into similar use cases. I had some jankier solutions for ensuring there was always a trailing paragraph (I threw those out), but we won't talk about those 🤣

**Comment by holtwick** [comment]
@ryanbliss Thanks for the input. I believe having the trailing empty paragraph is very important, because GapCursor only works in mouse based areas. On mobile devices it does not help that much. The overall experience is more natural having the last empty line.

Many many thanks to @ifiokjr !!! I adopted his remirror implementation for TipTap. The following is a plugin definition to do the job. I have put it into my Paragraph extension, but it could be anywhere else. Hope this helps:

```js
get plugins() {

    const findNodeAtPosition = ($pos) => {
      const { depth } = $pos
      const node = $pos.node(depth)
      return {
        pos: depth > 0 ? $pos.before(depth) : 0,
        start: $pos.start(depth),
        node,
      }
    }

    const nodeEqualsType = ({ types, node }) => {
      return (Array.isArray(types) && types.includes(node.type)) || node.type === types
    }

    let plugin = new PluginKey('paragraph-trailing')

    return [
      new Plugin({
        key: plugin,
        view() {
          return {
            update: view => {
              let state = view.state
              const insertParagraphAtEnd = plugin.getState(state)

              if (!insertParagraphAtEnd /* || !ensureTrailingParagraph */) return
              const { pos, node } = insertParagraphAtEnd

              let type = state.schema.nodes.paragraph
              view.dispatch(view.state.tr.insert(pos + node.nodeSize, type.create()))
            },
          }
        },
        state: {
          init: (_, state) => {
            let type = state.schema.nodes.paragraph
            let result = findNodeAtPosition(Selection.atEnd(state.tr.doc).$from)
            return nodeEqualsType({ node: result.node, types: type }) ? false : result
          },
          apply: (tr, oldState, state) => {
            if (!tr.docChanged) {
              return state || oldState
            }
            let type = state.schema.nodes.paragraph
            let result = findNodeAtPosition(Selection.atEnd(tr.doc).$from)
            return nodeEqualsType({ node: result.node, types: type }) ? false : result
          },
        },
      }),
    ]
  }
```

**Comment by philippkuehn** [comment]
Thanks @holtwick. Will try it. It's definitely something I want to see in the core.

**Comment by holtwick** [comment]
I enhanced the code to also accept headers as trailing lines, which will avoid problems with common placeholder plugin configurations:

```js
 let types = [
    state.schema.nodes.paragraph,
    state.schema.nodes.header]
// ...
return nodeEqualsType({ node: result.node, types }) ? false : result
```

**Comment by philippkuehn** [comment]
I've added a `TrailingNode()` extension, which you can see at the [embed example](https://tiptap.scrumpy.io/embeds). For me, your way of calculating the last node with `findNodeAtPosition(Selection.atEnd(tr.doc).$from)` didn't work at the embed example so I think I found a better solution.

These are the default options:

```js
new Editor({
  extensions: [
    new TrailingNode({
      node: 'paragraph',
      notAfter: ['paragraph'],
    }),
  ],
})
```

**Comment by ifiokjr** [comment]
@philippkuehn your solution is so much better 👍  I didn't even know that `doc.lastChild` existed which the API so much better. Also separating it into its own extension makes a lot more sense. I hope you don't mind me "borrowing" aspects for remirror.

**Comment by philippkuehn** [comment]
@ifiokjr That's one of the great parts of open source ✌️

**Comment by ryanbliss** [comment]
@philippkuehn and @holtwick this is incredible thank you!

**Comment by jermitval** [comment]
TrailingNode something mess up the history. May be someway can close history temporary?

**Comment by SivaRSR** [comment]
Undo is not available, when content is selected from the trailing paragraph...

**Comment by WilliamIPark** [comment]
Hey @philippkuehn, is a more solid implementation of the TrailingNode extension on the roadmap? I think I can currently get by with just a gap cursor but this would be nice to have :)

**Comment by mgtcampbell** [comment]
Another approach that I took which works for how we wanted to handle this type of scenario...

I am using the `handleClick` function inside the `editorProps` when setting up your Tiptap...

1. The first part checks if the click was on any of the existing content/nodes inside the `.proseMirror` DOM element, and if it was ignore, if it wasn't then assume the click was in the space at the bottom of the element where there's no content.
2. If the last element isn't a paragraph it adds one
3. If the last element is an empty paragraph then just focus into it
4. If the last element is a paragraph and has content, add an empty one after it (optional depending on your preference for how to handle that scenario)

```
handleClick: (view, pos, event) => {
  if (event.target !== view.dom) {
    return false
  }

  if (view.state.doc.lastChild?.type.name != "paragraph") {
    editor.value.commands.focus("end")
    let nodePosition = editor.value.state.selection.$to.pos - view.state.doc.lastChild.nodeSize
    editor.value.commands.setNodeSelection(nodePosition)
    editor.value.commands.createParagraphNear()
    return true
  } else if (view.state.doc.lastChild?.content.size < 1) {
    editor.value.commands.focus("end")
    return true
  } else {
    editor.value.commands.focus("end")
    let nodePosition = editor.value.state.selection.$to.pos - view.state.doc.lastChild.nodeSize + 1
    editor.value.commands.setNodeSelection(nodePosition)
    editor.value.commands.createParagraphNear()
    return true
  }
}
```

**Comment by punkpeye** [comment]
I've tried this, but it works sporadically at best:

```
import { Extension } from '@tiptap/core';
import { Plugin, PluginKey } from '@tiptap/pm/state';

export const TrailingNode = Extension.create({
  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey('TrailingNode'),
        props: {
          handleClick: (view, pos, event) => {
            if (event.target !== view.dom) {
              return false;
            }

            const { editor } = this;

            console.log('???');

            if (
              view.state.doc.lastChild?.type.name !== 'paragraph' ||
              (view.state.doc.lastChild?.content.size > 0 &&
                view.state.doc.lastChild?.type.name === 'paragraph')
            ) {
              const nodePosition =
                editor.state.doc.content.size -
                (view.state.doc.lastChild?.nodeSize ?? 0);
              editor.commands.setNodeSelection(nodePosition);
              editor.commands.createParagraphNear();
              return true;
            } else if (view.state.doc.lastChild?.content.size < 1) {
              editor.commands.focus('end');
              return true;
            }

            return false;
          },
        },
      }),
    ];
  },

  name: 'TrailingNode',
});
```

**Comment by mgtcampbell** [comment]
@punkpeye - I don't have a lot of experience writing plugins.

Probably best to take a look at how they've handled this in the experiments section -> https://tiptap.dev/docs/examples/experiments/trailing-node - you can see in the source code how they handle making something similar a plugin.

My implementation works well enough for me for now, although it does create a new node at the bottom of the content if you click in any gaps between other blocks which is not ideal.
