### ISSUE TITLE
Visible Markdown Formatting

### ISSUE THREAD

**Issue by phendan** [scrumpy/tiptap#146]
Hey, I’ve tried looking through the examples and ProseMirror documentation, but I’m a little lost so I thought I’d ask here.

I’d like to use tiptap to enable the kind of Markdown formatting that apps like Ulysses offer. Specifically when the regex I provide in the respective node/mark class is matched, I’d like to only change the markup (say from a p to an h1 tag) but keep the hash and space that triggered the change. I don’t fully understand them yet but could I write a custom Prosemirror input rule to handle this?

Additionally, could I then use a Vue component in the view method to style the hash separately from the actual content of the h1?

**Comment by MarkGStacey** [comment]
This would be my number one request !

**Comment by philippkuehn** [comment]
I dont have plans to implement this anymore.
