### ISSUE TITLE
problem with styling

### ISSUE THREAD

**Issue by Saeid-Barzegar** [scrumpy/tiptap#151]
hi phill
thank's guy for your cool editor
i have a problem
i used your editor in my vue project but i have a same problem with all of your templates
**styles not loading!!!**
as a sample i decide to use bubble menu
but i saw a simple box with three button
how can i load your editor styles in my project
i installed it with npm command

is there any dependencies that i must install it first?

**Comment by philippkuehn** [comment]
Hey @Saeid-Barzegar, tiptap is renderless and comes without any styling. So it's a feature – not a bug ;)
But feel free to take the styling from the [examples page](https://github.com/scrumpy/tiptap/tree/master/examples).

**Comment by Saeid-Barzegar** [comment]
thanks man.
but i think its better release it with style and every body can customize it
or write this feature in your github first page
its so useful and beautiful  but in first look seems  a bug...
cause if installed it from npm  repository i didn't see your repository files
thank you so much  and 
Have a good year...

**Comment by anirudhRowjee** [comment]
I second this. I really love the look of the editor as it is on the examples page, so much so that I ended up borrowing all your sass for one of my projects. Thank you!
