### ISSUE TITLE
Any dist / compiled files available?

### ISSUE THREAD

**Issue by rdlh** [scrumpy/tiptap#158]
Hi guys!

We're building a Vue app inside an existing Rails app.
We import components / files the "old" way. Example:

```
= javascript_include_tag 'https://cdn.jsdelivr.net/npm/vue/dist/vue.js'
= javascript_include_tag 'foo/libs/selectize.js'
= javascript_include_tag 'foo/components/bar.js'
...
```

Is there any `dist` file (like [this one](https://github.com/rhyek/vue2-selectize/tree/master/dist) for example, minified etc.) to help us integrate this awesome plugin without yarn or npm?

Thanks!

**Comment by rdlh** [comment]
Switched to npm & webpack, closign issue :).

**Comment by khabubu** [comment]
Good day I have been trying to make this work with no avail. could you please provide guidance on how you solved this issue.

**Comment by khabubu** [comment]
Please disregard the comment above I got it work.

**Comment by ImTheDeveloper** [comment]
How did you get it to work in the end?
