### ISSUE TITLE
An example of how to reproduce the example editors in a vue app?

### ISSUE THREAD

**Issue by Neophen** [scrumpy/tiptap#160]
### Issue:
You have great docs and examples. But you don't show any way I can reproduce the same examples in a vue component, with the same styling and your icons?

Could you provide a simple video or something showing a step by step how to add a tiptap example to an existing vue app?

**Comment by antimodern** [comment]
> Could you provide a simple video or something showing a step by step how to add a tiptap example to an existing vue app?

:smile: 

Sorry can't help myself.

You can find everything (including icons!) here - https://github.com/scrumpy/tiptap/tree/master/examples

Still, I think we are missing good Docs.

**Comment by hanspagel** [comment]
We'll publish docs soon.

**Comment by philippkuehn** [comment]
You can follow #162 for the progress of better docs.

**Comment by Neophen** [comment]
> > Could you provide a simple video or something showing a step by step how to add a tiptap example to an existing vue app?
> 
> 😄
> 
> Sorry can't help myself.
> 
> You can find everything (including icons!) here - https://github.com/scrumpy/tiptap/tree/master/examples
> 
> Still, I think we are missing good Docs.

Yes, but try including that into a vue app. what do you get? Nothing is working. the icons are broken with. and the editor while shows up doesn't have any csss.

The css in the examples is also touching a lot of things outside the example itself, like body/html.

While i've done an implementation of the editor and i'm super happy with it. Still an easy renderfull example of how to add one of the examples into an existing vue app would be cool.

Thank you either way this is a great product and super thank you to the contributors this has saved my ass :)

**Comment by lalitj** [comment]
@Neophen I am facing the same issue. Can you share the CSS you used for basic example? Thanks in advance.

**Comment by 1421gcs** [comment]
Six years have passed, and we still cannot easily reproduce any of the examples in the documentation. Although you have provided the complete component code, the lack of CSS code makes it difficult to reproduce. Additionally, I noticed that all the examples on the official website ultimately point to https://embed.tiptap.dev but I cannot find the source code for this website itself. All of these obstacles have hindered my ability to quickly understand the Tiptap editor!
