### ISSUE TITLE
How to bind click event to node?

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#163]

**Comment by philippkuehn** [comment]
You can pass prosemirror plugins to your extensions. There are some [editor props](https://prosemirror.net/docs/ref/#view.EditorProps) you can use – in your case it's `handleClick`.

```js
import { Node, Plugin } from 'tiptap'

export default class CustomNode extends Node {

  get name() {
    return 'custom_node'
  }

  get schema() {
    // schema
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          handleClick(view, pos) {
            // do something
          },
        },
      }),
    ]
  }

}
```

**Comment by Alecyrus** [comment]
Is it possible to get the Vue instance in functon `handleClick`?  For now, my solution is to store some variables  through using LocalStorage, then I can visit these variables in CustomNode.js.  But I really want to find a way to visit `this` directly in `handleClick`

**Comment by Alecyrus** [comment]
Or maybe we can register these `editor props` when the Editor is initialized?  
Like this.
```javascript
new Editor({ 
  handleClick: ( view, pos, event) => {} .   // now it is not supported
})

```

**Comment by zifnab87** [comment]
Since it wasn't very clear from the documentation - I found on ProseMirror documentation how to get which node was pressed. This way you can get attributes etc :D

```
 new Editor({
    editorProps: {
        handleClickOn: (view, pos, node) => {
            console.log('handleClickOn', node.attrs)
        }
    } [...]
```

**Comment by Everything-Ready** [comment]
Hello?
