### ISSUE TITLE
Custom vue components slots

### ISSUE THREAD

**Issue by krvd** [scrumpy/tiptap#165]
Hello,
Does tiptape support custom vue components with slots? And can you please provide an example if yes.

**Comment by philippkuehn** [comment]
What do you mean with slots here? What do you want to achieve?

**Comment by krvd** [comment]
Sorry for late reply. I want to make a spoiler as vue component and I want to pass spoiler content into slot of this component.

**Comment by kpdemetriou** [comment]
I believe what is being asked is whether custom Vue components can provide a slot in order to accept inner content. I too would like an answer to that question.

**Comment by philippkuehn** [comment]
I'm still not sure what you want to do. You can define inner content for nested nodes with `ref="content"`. ProseMirror will render any child nodes into this element. Is that what you want to achieve?

```vue
<div class="my-custom-component">
   <div ref="content"></div>
<div/>
```

**Comment by kpdemetriou** [comment]
This is precisely what I was looking for, thank you. I highly recommend noting this somewhere in the documentation; this feature cleanly enables some really bespoke editing capabilities.

**Comment by philippkuehn** [comment]
Yeah. Docs are incomplete but [I'm working on it](https://tiptap.scrumpy.io/docs).

**Comment by ThomasKientz** [comment]
> I'm still not sure what you want to do. You can define inner content for nested nodes with `ref="content"`. ProseMirror will render any child nodes into this element. Is that what you want to achieve?
> 
> ```
> <div class="my-custom-component">
>    <div ref="content"></div>
> <div/>
> ```

This should definitely be part of the docs !
