### ISSUE TITLE
Preserve &nbsp; (Non-breaking whitespace)

### ISSUE THREAD

**Issue by ustych** [scrumpy/tiptap#168]
I have a problem with outputting html after setContent(). When i add non-breaking space with html entity (nbsp;) Editor replaces all non-breaking spaces to default spaces. I need to preserve that special chars. What can i do in this situation?

**Comment by litvinchuk** [comment]
Same problem
I think it's referring to https://prosemirror.net/docs/ref/#model.ParseOptions.preserveWhitespace
But there is no method to pass this option

**Comment by Bicazian** [comment]
Same Problem.
To have the option added to setContent would be great

**Comment by mayacoda** [comment]
Same issue when passing content to the `Editor` constructor. I'll submit a PR to add passing `ParserOptions` to fix this issue.

**Comment by philippkuehn** [comment]
fixed with #254

**Comment by zalbastakiNetsells** [comment]
Note: the options is `parseOptions` and not `parserOptions` 😛had to look into the diff to figure that one out
