### ISSUE TITLE
Read content at cursor position

### ISSUE THREAD

**Issue by javisperez** [scrumpy/tiptap#169]
Hi! just found this package and is amazing, thanks for this!

I've been trying to insert automatic bullet items on some `markdown code highlight` block.

For example:
```
- one
- two
- three
```

I'm trying that inside a code block, when I press enter at the end of `- three`, add a new list item (`- `) to continue adding items.

My approach right now is to add a new plugin (e.g.`onEnterKey`) and try to pass a callback that checks if the `line previous to the cursor position` (on the code block) is a markdown list item to add another, but I'm not sure how to read the content of the previous line.

I have access to the whole `code block` text via `state > doc` but i guess i would have to split that by `\n`.

So, anybody knows if there's a better way to achieve this?

Thanks!

**Comment by Alecyrus** [comment]
This [todo-list example](https://tiptap.scrumpy.io/todo-list) maybe helpful.  You can press enter to add next todo-list item.

**Comment by javisperez** [comment]
Hey @Alecyrus thanks for the reply! my problem is that i need it for inside a `code` block :( so, cant use the `TodoList` extension :(

**Comment by Alecyrus** [comment]
oh ,back to previous question,  you can get the selection at cursor position, so you can visit the node. The previous line... function`findPositionOfNodeBefore` from [prosemirror-utils](https://github.com/atlassian/prosemirror-utils) may be helpful.

**Comment by javisperez** [comment]
Yeah @Alecyrus I was looking at that i finally made it :D, here's the final code in case it helps anybody:

```
      const { state } = editorView;
      const { $from, $to } = state.selection

      const before = $from.nodeBefore.textContent
      const after = $to.nodeAfter.textContent
      const previousLine = before.slice(before.lastIndexOf('\n') + 1)

      if (previousLine.match(/^[-+*]/g)) {
        this.updatedQueue.push(_ => {
          $from.pos += 2
          $to.pos += 1
          this.editor.setContent(`<pre><code>${before}\n- \n${after.slice(1)}</code></pre>`)
          this.setSelectionAtPos(editorView, state.selection)
        });
      }
```

I still need to add some stuff thou but to me, the hardest part was that :) thanks @Alecyrus !
