### ISSUE TITLE
Maybe we should consider to register `editor props` when the Editor is initialized?

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#173]
Or maybe we can register these `editor props` when the Editor is initialized?  
Like this.
```javascript
new Editor({ 
  handleClick: ( view, pos, event) => {} .   // now it is not supported
})

```

_Originally posted by @Alecyrus in https://github.com/scrumpy/tiptap/issues/163#issuecomment-456342336_

**Comment by philippkuehn** [comment]
In the newest version of tiptap there is an `editorProps` option.

```js
new Editor({ 
  editorProps: {
    handleClick: ( view, pos, event) => {
      // something
    }
  },
})
```
