### ISSUE TITLE
Error in apply() (file suggestions.js) when using Mentions and Horizontal Rule 

### ISSUE THREAD

**Issue by panayotisk** [scrumpy/tiptap#176]
I want to thank you for all the great work on tiptap and the new support for Horizontal rules.
Unfortunately I believe I stumbled upon a bug (breaking) that was lurking in Mentions that was revealed by the use of HR. I created a code sandbox [here](https://codesandbox.io/s/njj087j24) to demonstrate the error. If I put an HR in the end of the document and try to click on it then I get the following in Chrome Dev tools:

> Uncaught RangeError: There is no position before the top-level node
>     at ResolvedPos.before (VM4419 index.js:800)
>     at eval (VM4434 extensions.common.js:879)
>     at Plugin.apply (VM4434 extensions.common.js:1064)
>     at EditorState.applyInner (VM4418 index.js:864)
>     at EditorState.applyTransaction (VM4418 index.js:826)
>     at EditorState.apply (VM4418 index.js:799)
>     at Editor.dispatchTransaction (VM4417 tiptap.common.js:1026)
>     at EditorView.dispatch (VM4422 index.js:4548)
>     at SelectionReader.readFromDOM (VM4422 index.js:2058)
>     at HTMLDocument.SelectionChangePoller.readFunc (VM4422 index.js:2075) 

In case you cannot reproduce the error tell me to provide extra information. Thank you once again,
Panayotis

**Comment by bvkimball** [comment]
Is there work around for this?
