### ISSUE TITLE
Weird cursor behavior on codeblock if `display: block` is on a node

### ISSUE THREAD

**Issue by javisperez** [scrumpy/tiptap#177]
Hi!

Inside a `highlighted code block`, if i try to add some style to the generated highlightjs dom the cursor behaves weird.

If i make any of the highlight styles full width (like `.hljs-comment`), either with: `display: block` or `display: inline-block; width: 100%;` the cursor behaves super weird and jumps from the current block to another.

Here's a demo of what i mean:
![test](https://user-images.githubusercontent.com/4766570/51750681-30a15a80-2089-11e9-820c-fa0d7e058834.gif)

There, the red line has `display: block` and notice how the cursor jumps from the red bar to the `Header` text instead of the previous paragraph.

Not sure if is an issue with tip tap or ProseMirror but i think is related to the `CodeblockHighlight` extension, any help?

Thanks!

**Comment by philippkuehn** [comment]
Can you provide a codesandbox?

**Comment by philippkuehn** [comment]
closed due to inactivity
