### ISSUE TITLE
KaTeX Integration

### ISSUE THREAD

**Issue by wngu6** [scrumpy/tiptap#179]
It would be great if there was an extension that uses KaTeX, sort of like Dropbox Paper but better.
There should be one for inline mode and another for display mode. When editing maths, especially for display mode, it would be great if it allows multiple lines.

This is my attempt in display math mode.
```
import { Node } from "tiptap"
import { toggleBlockType, setBlockType, textblockTypeInputRule } from "tiptap-commands"
import katex from "katex"

export default class DisplayMath extends Node {

  get name() {
    return "displaymath"
  }

  get schema() {
    return {
      attrs: {
        content: {
          default: ""
        }
      },
      content: "text*",
      marks: "",
      group: "block",
      defining: true,
      draggable: false,
      parseDOM: [
        {
          tag: "displaymath",
          getAttrs: dom => ({
            content: dom.getAttribute("content")
          })
        }
      ],
      toDOM: node => [
        "displaymath", { content: node.attrs.content }, ["div"], ["textarea", 0]
      ]
    }
  }

  get view() {
    return {
      props: ["node", "updateAttrs", "editable"],
      data: function () {
        return {
          edit: true
        }
      },
      watch: {
        content: function (newContent, oldContent) {
          katex.render(this.content, this.$refs.disp, {
            throwOnError: false
          })
        }
      },
      computed: {
        content: {
          get() {
            return this.node.attrs.content
          },
          set(content) {
            this.updateAttrs({
              content
            })
          }
        }
      },
      mounted() {
        katex.render(this.content, this.$refs.disp, {
          throwOnError: false
        })
      },
      methods: {
        change() {
          this.edit = true;
        },
        update() {
          this.edit = false;
        }
      },
      template: `
      <div>
        <div ref="disp" @click="change"></div>
        <textarea v-if="edit" class="katex-input" v-model="content" @focusout="update"></textarea>
      </div>
      `
    }
  }

  inputRules({ type }) {
    return [
      textblockTypeInputRule(/^\$\$\$$/, type)
    ]
  }

}

```
I modeled it after ```Iframe.js```.

**Comment by philippkuehn** [comment]
Maybe you could see how it's implemented [here](https://github.com/chanzuckerberg/czi-prosemirror). Since I don't want to implement it, I will close the ticket.

**Comment by themindstorm** [comment]
@wngu6 Were you able to figure out how to do this?

**Comment by BrianHung** [comment]
@wngu6 @themindstorm 

I've implemented a working prototype for inline math. You may have to add additional css to get it working as depicted [here](https://i.imgur.com/xJCrj7z.mp4).

https://gist.github.com/BrianHung/b72126c98fa08cb1c09170b1394771a0

**Comment by mvind** [comment]
@BrianHung can you explain how to use the katex inline extension? 
I've tried to use just like an regular extensions, but it does not render and I get the following error:
 `VM241 app.js:125340 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "selected"`

**Comment by BrianHung** [comment]
@mvind @ninest I updated the `math` node gist. To use it, just import and use it in your editor like any other node.

**Comment by ramsane** [comment]
@BrianHung Thanks for the gist. But when I try to render by typing $a$, when I type the last $, it is giving the error. 
```
Cannot set property 'textContent' of undefined
```
This is what I've done.
![image](https://user-images.githubusercontent.com/14745146/91763593-70c8a780-ebf3-11ea-84c0-432b2cdd40e7.png)
I kept all the files in the same directory. And then,  importing it. `import Math from '@/utils/editor/Math.js'` and them adding `new Math()` to the extensions array when initializing the editor.

I think that's enough.  

Is there anything else that I've missed ?

**Comment by ramsane** [comment]
I got the solution. We need to add this to the nuxt confit( if you are using nuxt) so that it renders at pre compilation stage. Same is requred for youtube embeds too.

```js
  build: {
    extend(config) {
      config.resolve.alias.vue = 'vue/dist/vue.common'
    },
  },
```

**One request**
![image](https://user-images.githubusercontent.com/14745146/91914664-2f5cf880-ecd6-11ea-91ac-d1e7984c3c54.png)

It won't render when the parent element is active. It should render immediately when the cursor leaves the math node. And get back to edit mode when the cursor moves between $ symbol.

I've tried but couldn't figure it out. All I know is to change the logic here to make it false when the cursor leaves the node.
![image](https://user-images.githubusercontent.com/14745146/91914802-92e72600-ecd6-11ea-8b3c-eab7920cd1d1.png)

Can someone help me with this logic. With this, I think inline math functionality would be usable.

**Comment by BrianHung** [comment]
Detecting whether a cursor leaves or enter an inline node is harder than detecting whether it leaves a block-level node like a paragraph. See https://discuss.prosemirror.net/t/prosemirror-math-at-desmos/707/8. I would recommend getting comfortable with ProseMirror's plugin system first: https://prosemirror.net/docs/ref/#state.Plugin_System.

**Comment by ramsane** [comment]
I figured it out. 

```js
parentHasSelection() {
  .....
  // decides whether the anchor is between the Math node or not
  const hasAnchor = this.getPos() < anchor && anchor < this.getPos() + this.node.nodeSize
  ...
  ...
  // some other cases where it was not rendering. It helps if we are displaying the math equations.
  // I removed the selection as it doesn't change anything when I paste the math. It is adding extra $ at both ends. Don't know 
  // why.
  return hasAnchor && this.view.focused && this.view.editable
```

@BrianHung  if possible, could you please update the gist with this logic with some changes if required. And if you have time, please add comments so that we understand what is going on. It saves lot of time.

**Comment by ramsane** [comment]
And, for mathblock.js too, we need to change few things Otherwise it won't work properly.

```js
...
      computed: {
        visibleClass() {
          return this.hasProseMirrorSelection() ? "active" : "hidden"
        },
      },
...
```
And this
```js
 hasProseMirrorSelection() {
          let anchor = this.view.state.selection.anchor
          const hasAnchor = this.getPos() <= anchor && anchor < this.node.nodeSize + this.getPos()
          return hasAnchor && this.view.focused && this.view.editable
  },
```

Hope these are updated in the gist so that others won't face this issue.

**Comment by Zogsha** [comment]
@ramsane @BrianHung hello. I'm no expert but I managed to use different extension except this one. Could you provide a sandbox or a working exemple ? I can't figure why it doesnt work for me. I'd love to be able to add maths to a project.

**Comment by AdminScientificHub** [comment]
Hi, did anyone know an alternative when you work in React ? Didn't find any so far 😔

**Comment by MuhamadSelim** [comment]
> Hi, did anyone know an alternative when you work in React ? Didn't find any so far 😔
Check this
https://github.com/fantasticit/think/blob/main/packages/client/src/tiptap/core/wrappers/katex/index.tsx

**Comment by MuhamadSelim** [comment]
> Hi, did anyone know an alternative when you work in React ? Didn't find any so far 😔

@AdminScientificHub 
Check this 
https://github.com/fantasticit/think/blob/main/packages/client/src/tiptap/core/wrappers/katex/index.tsx
