### ISSUE TITLE
How to prevent a node from being deleted

### ISSUE THREAD

**Issue by NvdB31** [scrumpy/tiptap#181]
We're currently trying to make Tiptap render an editable Vue component. However we want to prevent that Vue component from being deleted.

From the Prosemirror docs I found that preventing node deletion is something that isn't so straightforward. I've seen stuff about Transactions and someone here deleting a node using a command which catches the backspace. However, as far as I know it's not directly possible to add custom Commands to tiptap, and I'm not sure if we can 'hook' into Prosemirror transactions from Tiptap to prevent node deletion?

I was wondering if any of you could point us in the right direction as to how to implement node deletion. It would help us a lot.

**Comment by Alecyrus** [comment]
Probably, you need to catch the `Backspace` event, then you could visit the previous node through the position of the cursor or the selection.

**Comment by Alecyrus** [comment]
Of course it is definitely possible to add your own command to any node, even the `Doc` node.

```javascript
import { Node } from 'tiptap';

export default class Doc extends Node {
  get name() {
    return 'doc';
  }

  commands() {
  }

  keys() {
  }
}

```

**Comment by philippkuehn** [comment]
This issue is related to ProseMirror.

**Comment by justin-schroeder** [comment]
@NvdB31 did you ever figure out how to prevent a node from being deleted? I'm going down the same path and struggling to find good intel on it.

**Comment by engram-design** [comment]
@justin-schroeder I have no idea if this is correct behaviour, but from what I've read it's two-parts. Detecting when you're hitting backspace/delete and detecting if you're about to remove the node you are wanting to detect.

```
get plugins() {
    return [
        new Plugin({
            props: {
                handleKeyDown: (view, event) => {
                    if (event.which === 8 || event.which === 46) {
                        view.state.deleting = true;
                    }

                    return false;
                },
            },

            filterTransaction: (transaction, state) => {
                var isDeleting = state.deleting;

                if (!state.deleting) {
                    return true;
                }

                var result = true;

                transaction.mapping.maps.forEach(map => {
                    map.forEach((oldStart, oldEnd, newStart, newEnd) => {
                        state.doc.nodesBetween(oldStart, oldEnd, (node, number, pos, parent, index) => {
                            if (node.type.name === 'custom_block') {
                                result = false;
                            }
                        });
                    });
                });

                return result;
            },
        }),
    ];
}
```

I'm not sure my `view.state.deleting` property-setting is abusing the model, but I couldn't figure out any other way!

**Comment by Spacarar** [comment]
@engram-design I know this is a quite old post, but for you and possibly to help others in the future, it's also possible to check the steps include replace events, and look at those specific mappings.

Based on the [ProseMirror docs about StepMap ranges](https://prosemirror.net/docs/ref/#transform.StepMap) you can determine the oldStart/End using the ranges. Since delete events are marked as `replace` steps and mappings correlate to steps, you can achieve the same result without manipulating state or checking for backspace commands using the following

```javascript
filterTransaction (transaction, state) {
  let result = true // true for keep, false for stop transaction
  const replaceSteps = []
  transaction.steps.forEach((step, index) => {
    if (step.jsonID === 'replace') {
      replaceSteps.push(index)
    }
  })

  replaceSteps.forEach(index => {
    const map = transaction.mapping.maps[index]
    const oldStart = map.ranges[0]
    const oldEnd = map.ranges[0] + map.ranges[1]
    state.doc.nodesBetween(oldStart, oldEnd, node => {
      if (node.type.name === 'custom_block') {
        result = false
      }
    })
  })
  return result
}
```

**Comment by engram-design** [comment]
Thanks for the suggestion, I might consider refactoring what I’ve got as this might be a little nicer handed!

**Comment by miketromba** [comment]
@Spacarar - Exactly what I needed for my use-case... thank you!!

**Comment by fahad1226** [comment]
I know it's too late but I have found an easy way to do that.

#this solution will apply for Vue 3 only.

handleKeyDown(view, event) {
            /**
             *
             *  1. We are checking if the key pressed is "Delete"
             *  2. If it is, we are getting the element that has the focus class
             *  3. We are getting the length of the text in that element
             *  4. We are getting the cursor position in that element
             *  5. If the cursor position is at the end of the text,
             *  6. We are disabling editing for 400ms and then enabling it again.
             *  7. This is to prevent deletion of the @CrossButton component when you press delete at the end of a task.
             */
            if (event.key == "Delete") {
                let element = document.querySelectorAll(".focus");
                const textLength = element[1].innerText.length;
                const cursorPosition = view.state.selection.$anchor.parentOffset;
                if (textLength == cursorPosition) {
                    editor.value.setEditable(false);
                    setTimeout(() => {
                        editor.value.setEditable(true);
                    }, 400);
                }
                throw new ErrorEvent("not allowed");
            }
        },

**Comment by remi-guan** [comment]
For my case, I also added a button to preform a logical deletion. I'm using transaction metadata to differ from the intentionally delete or not.

```ts
new Plugin({
  filterTransaction(transaction, state) {
    let result = true; // true for keep, false for stop transaction
    const replaceSteps: any[] = [];
    // if we're processing an intentional deletion, don't stop transaction
    if (transaction.getMeta('intentionalDeletion')) {
      return result;
    }
    transaction.steps.forEach((step: any, index) => {
      if (step.jsonID === 'replace') {
        const nodes = step.slice.content.content;
        if (nodes.length === 1) {
          const node = nodes[0];
          // if it's updating gamePageRedirect, don't stop transaction
          if (node.type.name === 'gamePageRedirect') {
            return;
          }
        }
        // filter delete or replace nodes actions to prevent gamePageRedirect button being deleted by keyboard
        replaceSteps.push(index);
      }
    });
    replaceSteps.forEach((index) => {
      const map = transaction.mapping.maps[index] as any;
      const oldStart = map.ranges[0];
      const oldEnd = map.ranges[0] + map.ranges[1];
      state.doc.nodesBetween(oldStart, oldEnd, (node) => {
        if (node.type.name === 'gamePageRedirect') {
          result = false;
        }
      });
    });
    return result;
  },
}),
```

And here's the logic to perform this "white-listed deletion" in React:

```ts
const handleDelete = () => {
  const from = getPos();
  const to = from + node.nodeSize;

  // Create an empty slice
  const emptySlice = Slice.empty;

  // Replace the content in the specified range with the empty slice
  const transaction = editor.state.tr.replace(from, to, emptySlice);

  // Optionally, you can add metadata to the transaction to indicate that this is an intentional deletion
  transaction.setMeta('intentionalDeletion', true);

  // Apply the transaction to the editor state
  editor.view.dispatch(transaction);
};
```

**Comment by kilgarenone** [comment]
I think catching early the backspace key is more performant:
```js
                 chainCommands(
                    (state) => {
                        // return true to stop backspace key from doing anything
                        // return false to let backspace do its thing

                        // In my case, first I get the context of the current cursor
                        console.log(state.doc.resolve(state.selection.anchor);

                        // Then, I check the value of `nodeBefore` property to see 
                        // if the node before the cursor is the node user can't delete 
                    },
                    deleteSelection,
                    joinBackward,
                    selectNodeBackward,
                ),
```
[Reference](https://github.com/ProseMirror/prosemirror-commands/blob/20fa086dfe21f7ce03e5a05b842cf04e0a91e653/src/commands.ts#L603)
