### ISSUE TITLE
Tiptap doesn't proceed pasted markdown

### ISSUE THREAD

**Issue by bdrtsk** [scrumpy/tiptap#182]
I see (surprisingly!) Tiptap can process markdown markup on the fly while I am typing (which is absolutely awesome!). But, if I copy paste prepared markdown tiptop doesn't proceed pasted text. Is there a way to process in? Which event is fired and what event I should trigger so tiptap could process markdown, like it's able to do?

```
hello **hello** hello
```

**Comment by Chrissi2812** [comment]
I have created some basic parsing at https://deploy-preview-184--scrumpy-tiptap.netlify.com/

Currently only marks are supported.

**Comment by elliotaplant** [comment]
Can you provide the source for that example @Chrissi2812 ?

**Comment by rfgamaral** [comment]
@elliotaplant If you need Markdown support on a Tiptap-based editor, see if [Typist](https://github.com/Doist/typist) feels your needs.
