### ISSUE TITLE
Check selection not empty within isActive ?

### ISSUE THREAD

**Issue by ligne13** [scrumpy/tiptap#183]
Hi,

is it possible to check if current selection is not empty in order to enable/disable a button in the menu ?
I guess this is related to the isActive function, but how can I check the current range selection before returning the isActive value ?

For example, I want to enable a custom extension button (font family dropdown) only if the user has selected one or more characters in the editor.

thanks !

**Comment by panayotisk** [comment]
I implemented my isSelectionEmpty as follows:
```
isSelectionEmpty() {
  const { view } = this.editor;
  const { selection } = view.state;
  return selection.empty;
}
```

**Comment by ligne13** [comment]
@panayotisk how/where do you implement this function ?

**Comment by panayotisk** [comment]
I have put the function inside the component that renders the editor-content component. 
I then decided to pass such functions as callbacks to the toolbar component (which in my case is custom), so that it can use them however it needs.

**Comment by ligne13** [comment]
OK thanks !

**Comment by ilya-bkv** [comment]
If someone like me comes across this question, then here is the current solution for 2023 `editor.state.selection.empty` ¯\_(ツ)_/¯
