### ISSUE TITLE
The placeholder extension shouldn't be active for readonly mode

### ISSUE THREAD

**Issue by philippkuehn** [scrumpy/tiptap#186]

**Comment by panayotisk** [comment]
Maybe you could leave this to be optional somehow, because there are cases I need to switch between readonly and edit mode and have the placeholder always showing.

**Comment by Alecyrus** [comment]
@panayotisk Agree

**Comment by philippkuehn** [comment]
this is fixed in `tiptap-extensions@1.12.0`. the placeholder isn't visible for read-only anymore. you can set `showOnlyWhenEditable` to `false` to always enable the placeholder extension.
