### ISSUE TITLE
add setContent to the README.md as it works and it is usefull

### ISSUE THREAD

**Issue by gabrielstuff** [scrumpy/tiptap#187]
The `setContent` method is not documented in the README.md. (https://github.com/scrumpy/tiptap/blob/89bdef6441b926aa1c4decba9bd5d489c63dbd45/packages/tiptap/src/Editor.js#L304)

I propose to add it.

Thanks!

**Comment by philippkuehn** [comment]
You are absolutely right! Added an [editor methods section](https://github.com/scrumpy/tiptap/blob/master/README.md#editor-methods) to the readme. Thanks!
