### ISSUE TITLE
Add `enabled` property to EditorMenu component.

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#189]
Like, when the editor is readonly, the menubar should be hidden (In my case). But if I use v-if or v-show, error will occur when some text are selected. 
![image](https://user-images.githubusercontent.com/13865581/52181050-5ae0de00-2828-11e9-8547-4149046fe1c4.png)

Therefore, adding `enabled ` property will be an elegant way to avoid the error above. Or, any advice or help please?

**Comment by philippkuehn** [comment]
this should be fixed with https://github.com/scrumpy/tiptap/commit/0742ca8abe913b1648a50da072075e424fe9b5d4
