### ISSUE TITLE
Copy / Paste inside embed input

### ISSUE THREAD

**Issue by Simon-Renault** [scrumpy/tiptap#199]
I wonder if anyone have a fix for this : 

I'm trying to build a rich text editor in vueJs but I have problems with Tiptap capturing all paste events.
In order to make a visuel image editor allowing to add special class and alt to images I based myself upon the Tiptap embed demo found at  https://tiptap.scrumpy.io/embeds.

Even in this demo you cannot paste url inside the input, it paste it above the block.

**Current behavior:**
Tiptap paste the url in the first block above the input.

**Desired behavior:**
Being able to paste content inside inputs.

The Tiptap embed demo present a working exemple of this problem : https://tiptap.scrumpy.io/embeds

Any ideas?  No doubt i'm missing something obvious but anyway it could be important to fix the exemple.

Best,
Simon

**Comment by Chrissi2812** [comment]
Have a look at https://deploy-preview-203--scrumpy-tiptap.netlify.com/embeds

**Comment by fxmouthuy** [comment]
This issue has been closed for a while but I stumbled upon it while searching for a solution to that exact issue. 
In the end, I found an obvious workaround by myself so for prosperity: you can just add a `@paste.stop` on the root element of your view component.
