### ISSUE TITLE
Support history custom settings

### ISSUE THREAD

**Issue by MatheusRich** [scrumpy/tiptap#211]
Currently, Tip Tap doesn't support custom settings on the history extension, like depth and the delay time to create a new history group.

It seems that **prosemirror-history** [has support for this feature](https://github.com/ProseMirror/prosemirror-history/blob/master/src/history.js#L388). I think tip tap could support this too.

I could work on this, if you guys are ok with it!

**Comment by alaxalves** [comment]
I could use this feature too :sweat_smile:
