### ISSUE TITLE
Wrong bubble position

### ISSUE THREAD

**Issue by alotex** [scrumpy/tiptap#215]
![ezgif-1-a99eb749f278](https://user-images.githubusercontent.com/47648493/53461924-5648c780-3a6c-11e9-9c46-bb16cb10d500.gif)

browser: latest chrome
os: macOS

**Comment by holtwick** [comment]
Here another example from [demo](https://tiptap.scrumpy.io/menu-bubble). In Safari double click on the word "about":

<img width="596" alt="screen shot 2019-02-27 at 11 17 48" src="https://user-images.githubusercontent.com/49557/53483245-63bc7c80-3a81-11e9-8160-f484ec9a3703.png">

**Comment by alotex** [comment]
Another screen record here.
![screencast 2019-02-28 06-46-04](https://user-images.githubusercontent.com/47648493/53533778-573e2f80-3b26-11e9-95cc-505e8127668d.gif)


I've got digging into the sources and found a place where prosemirror calculates coordinations
https://github.com/ProseMirror/prosemirror-view/blob/master/src/domcoords.js#L237

**Comment by Chrissi2812** [comment]
I have supplied a PR to prosemirror-view as their [example](https://prosemirror.net/examples/tooltip/) also suffers from wrong positioning.
So if they merge it should fix our menububble too.

![wrong-position](https://user-images.githubusercontent.com/6141652/53873306-5e6ead00-4000-11e9-890d-63279676bbc5.gif)

**Comment by Chrissi2812** [comment]
The PR won't get merged unless these two issues (Prosemirror/prosemirror#900 Prosemirror/prosemirror#899) are solved in Prosemirror.

So the only option would to implement the changed `cordsAtPos` function into the menuBubble itself.

If I got some time I can make that PR

**Comment by nutheory** [comment]
center on selection start?

**Comment by nutheory** [comment]
i can do this 10 ways from tuesday whats prefered?
