### ISSUE TITLE
Markdown shortcuts

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#218]
With the [basic example](https://tiptap.scrumpy.io/), click the `Bold` button in the Menu, then I can input some texts with `Bold` style, if I click the button again, the text I inputed will be no style.  
![123123123](https://user-images.githubusercontent.com/13865581/53779932-1aff3a80-3f3d-11e9-80d3-ed6106da2b90.gif)
However, If I switch to `Markdown Shortcuts` example and  move the cursor to the tail of some `Bold` text, I could only input `Bold` text. There is no way to clear the `Bold` marks. 

![44444](https://user-images.githubusercontent.com/13865581/53779936-1dfa2b00-3f3d-11e9-834b-4b5b0b82ac9d.gif)

I am thinking about exchanging `Backspace` behavior, but I don't know whether it works or not.  Anyone could help?

**Comment by Alecyrus** [comment]
Yeah, I found a workaround. Define `Tab` bindings to insert a blank with no style:
```javascript
 keys({ type }) {
    const command = chainCommands(exitCode, (state, dispatch) => {
  
      let marks = [];

      state.doc.nodesBetween(from - 1, to, (node) => {
        marks = [...marks, ...node.marks];
      });
      const transaction = state.tr;
      transaction.insertText(' ');
      if (marks.length) {
        transaction.removeMark(from, to + 1, marks[0].type);
      }
      dispatch(transaction.scrollIntoView());
      return true;
    });
    return {
      Tab: command,
    };
  }

```

**Comment by philippkuehn** [comment]
You can always use shortcuts to enable or disable marks. (cmd + b) for bold for example.

**Comment by Alecyrus** [comment]
Thank you, that's right. But for different marks , user have to use different shortcuts to disable marks.  And my solution I mentioned above could clear all marks for the next input, which meets my needs.
