### ISSUE TITLE
Highlight search results

### ISSUE THREAD

**Issue by holtwick** [scrumpy/tiptap#224]
It would be great to have an extension that allows to highlight search results or other plain text based features using Decorations, like this example:

https://gist.github.com/marijnh/cee01b30b1890a5947c0

**Comment by Alecyrus** [comment]
Nice work! @holtwick  Thank you for showing this example, that is very helpful.

**Comment by Alecyrus** [comment]
[Linter example](http://prosemirror.net/examples/lint/) may be helpful.

**Comment by Chrissi2812** [comment]
@holtwick I have finshed my work on a search extension.
Have a look at: https://deploy-preview-324--scrumpy-tiptap.netlify.com/search

**Comment by holtwick** [comment]
@Chrissi2812 Awesome!!! Thanks a lot. That's much more than I ever expected. Great work.
