### ISSUE TITLE
toDOM() and parseDOM()

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#226]
I implement `image` node with Vue Component, and I notice the line in the `README`:
> 
```JavaScript
 // parseDOM and toDOM is still required to make copy and paste work
      parseDOM: [{
        tag: 'iframe',
        getAttrs: dom => ({
          src: dom.getAttribute('src'),
        }),
      }],
      toDOM: node => ['iframe', {
        src: node.attrs.src,
        frameborder: 0,
        allowfullscreen: 'true',
      }],
```
I want to know what means `parseDOM and toDOM is still required to make copy and paste work`? 

If I export the document in HTML format, will the HTML code of the `node` with Vue Component be like what defined in `toDOM()` or `template`？

**Comment by inssitu** [comment]
In your code toDOM export an iframe instead of the the extension component view
