### ISSUE TITLE
Append text to current editor's content

### ISSUE THREAD

**Issue by emiltsang** [scrumpy/tiptap#230]
Is there any ways to append a text/paragraph to the editor's current content?
For example, the current content is "This is the first sentence."
Is there any ways to append "This is the second sentence." to the end?

I found there was a setContent() method, but it replaces all the text content instead.

**Comment by Alecyrus** [comment]
Get the last position of the document, and dispatch a new transaction where you can call [insertText](http://prosemirror.net/docs/ref/#state.Transaction.insertText)

**Comment by philippkuehn** [comment]
For adding text at the current cursor position you can do this:
```js
const transaction = this.editor.state.tr.insertText('hey!')
this.editor.view.dispatch(transaction)
```

**Comment by smkim02** [comment]
How to Append tag to current editor's content..?

**Comment by maxmonteiro** [comment]
> How to Append tag to current editor's content..?

var elem = "<p>Hey!</p>"
var editorHtml = this.editor.getHTML()
editorHtml += elem
this.editor.setContent(editorHtml)

**Comment by alancwoo** [comment]
Current syntax would be `this.editor.commands.setContent(editorHtml)` https://www.tiptap.dev/api/commands/set-content/

**Comment by ifndefdeadmau5** [comment]
`editor.chain().focus().insertContent('some content').run();`

**Comment by sipec** [comment]
> React version `editor.chain().focus().insertContent('some content').run();`

you should also do a [createPargraphNear()](https://github.com/manifoldmarkets/manifold/pull/725) so that if `focus()` would focus block content (like in image) it doesn't replace it. So:

`editor.chain().focus('end').createParagraphNear().insertContent('some content').run()`
