### ISSUE TITLE
Blue Border Around Editor?

### ISSUE THREAD

**Issue by orozcojd** [scrumpy/tiptap#234]
<img width="732" alt="Screen Shot 2019-03-08 at 4 39 48 PM" src="https://user-images.githubusercontent.com/9628095/54063391-dedc0c00-41c0-11e9-91cb-8eb7bcfb53e0.png">

Is anyone else getting a blue border around the editor? This is a screenshot with the most basic options and I can't seem to remove this border readonly or editable. 

Code taken from docs:
```
<template>
  <v-layout >
    <v-flex xs6 offset-xs3>
      <editor-content :editor="editor" />
    </v-flex>
  </v-layout>
</template>

<script>
import { Editor, EditorContent } from 'tiptap'
export default {
  name: 'login',
  data () {
    return {
      editor: null
    }
  },
  components: {
    EditorContent
  },
  mounted () {
    this.editor = new Editor({
      content: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>'
    })
  },
  beforeDestroy () {
    this.editor.destroy()
  }
}
</script>
```

**Comment by Alecyrus** [comment]
This is default `focus` outline style of browser. Like the default `padding` is `8px`.  You can overwrite it:
```css
*
  &:focus
    outline none
```

Please learn to use chrome Devtools and Vue DevTools which can help you to inspect all corners of your web app.

**Comment by orozcojd** [comment]
Thanks for the response. I've been trying to find the outline by searching for 'border'. I appreciate it!
