### ISSUE TITLE
Wrong behavior when pressing delete at the beginning of todo item text

### ISSUE THREAD

**Issue by elmasry** [scrumpy/tiptap#249]
When you press delete key at the beginning of todo item text, it should merge with the previous item, I think that's the correct behavior. right now it's selecting the text of the previous item, any idea how to fix that? 

![Untitled](https://user-images.githubusercontent.com/970314/55288308-f5d3df80-53b5-11e9-9590-6df36aea0164.gif)

**Comment by Chrissi2812** [comment]
In #278 The behavior is a little different. Instead of selecting the text it appends a new `paragraph` with the content of the old `todo_item`.
![nested-todos-delete](https://user-images.githubusercontent.com/6141652/57438475-4f94b880-7244-11e9-87ac-a3250443c6fd.gif)

**Comment by philippkuehn** [comment]
yeah this behavior changed in the latest version and I do not plan to change that again anytime soon, because this is the default behavior of `prosemirror-schema-list`.
