### ISSUE TITLE
Anyway TipTop to support Grammarly?

### ISSUE THREAD

**Issue by mehrunrasoli** [scrumpy/tiptap#255]
Hi there,

As you may know, there are so many people around the world using Grammarly to check their content's typo, etc.., but seems that it doesn't support contentEditable fields.

So any idea how to use it on the Tiptop?

**Comment by philippkuehn** [comment]
This is related to Prosemirror and can't be fixed in tiptap. Sorry! :/
https://github.com/grammarly/contenteditable
