### ISSUE TITLE
Hiding MenuBubble on editor blur

### ISSUE THREAD

**Issue by blangenfeld** [scrumpy/tiptap#256]
First, **thank you** for making tiptap available!

In our app, we'd very much like any shown menu bubble to be hidden when the user tabs out of the editor. I see tiptap listening for `blur` events, and the handler is being called... but it bails out any time `event.relatedTarget` is set.

https://github.com/scrumpy/tiptap/blob/24f61e02be0ed091f4735266df03433ceeda119c/packages/tiptap/src/Plugins/MenuBubble.js#L65

And I might be wrong, but I think `event.relatedTarget` will **always** be present when (e.g.) tabbing from one field to the next.

We can work around this by catching the `blur` event and re-dispatching another without a `relatedTarget`, but maybe this isn't the best way?

**Comment by Alecyrus** [comment]
"v-show"

**Comment by blangenfeld** [comment]
Ah, good thought; thanks. Went this route, for anyone else who comes by here:

```html
<editor-menu-bubble :editor="editor">
    <div
        slot-scope="{ commands, isActive, getMarkAttrs, menu }"
        :class="{ 'invisible opacity-0': !(menu.isActive && isEditorFocused)}"
    ....
```

```js
this.editor = new Editor({
    onBlur: ({ event, state, view }) => {
        vm.isEditorFocused = false;
    },
    onFocus: () => {
        vm.isEditorFocused = true;
    },
    ...
```

**Comment by Alecyrus** [comment]
`v-show` = `display: none`, if you use `opacity`, you'd better add  `pointer-events: none`.
