### ISSUE TITLE
this is undefined inside onBlur 

### ISSUE THREAD

**Issue by Abhay07** [scrumpy/tiptap#263]
I tried event binding by passing onBlur prop, didn't work
`<editor-content :editor="editor" class="text-content" @onBlur="onBlur"> </editor-content>`

what did work was 

`editor: new Editor({
        extensions: [
          new Blockquote(),
          new Heading({ levels: [1, 2, 3] }),
          new BulletList(),
          new OrderedList(),
          new ListItem(),
          new Bold(),
          new Italic(),
          new Strike(),
          new Underline(),
        ],
        content:null,
        onBlur:(event)=>{
        	console.log(event);
        	console.log(this);
        }
      })`

defining in data, but `this` is undefined, i need to call a method of the main component on blur of editor. 

Can someone point me in right direction ?

**Comment by philippkuehn** [comment]
Inside onBlur there should be everything accessible.

```js
export default {
  data() {
    return {
      editor: new Editor({
        onBlur: ({ event }) => {
          console.log(event) // blur event
          console.log(this) // your vue component
          console.log(this.editor) // tiptap editor instance
        }
      })
    }
  }
}
```
