### ISSUE TITLE
Is it possible to separate menubar and menu-content into different components?

### ISSUE THREAD

**Issue by Martin-Karsten** [scrumpy/tiptap#266]
Is it possible to separate the menubar and the menu-content into different components? 
I have two different components, one contains the menubar, the other one the content. If i try to edit the content by using the menubar, for example making it bold, i get the error message 
"addRange(): The given range isn't in document".

**Comment by philippkuehn** [comment]
Please provide a codesandbox.

**Comment by Martin-Karsten** [comment]
Thank you for your answer. I tried to recreate the problem https://codesandbox.io/s/jvr83p71m5
My real setup was basically the same but here i don't get the error message. Now nothing happens. I split the menubar and the content into two different components. My goal is to edit the content with the menubar in the other component. Is that possible or do the menubar and its content always belong into the same component?

**Comment by Chrissi2812** [comment]
Hi @Martin-Karsten, you should pass the editor instance to the child components that way it all stays in sync.

Working Example:
https://codesandbox.io/s/64lmxj5x5k

**Comment by Martin-Karsten** [comment]
Thank you @Chrissi2812, that solved my problem. I am going to close this issue.
