### ISSUE TITLE
No new line after click on Enter

### ISSUE THREAD

**Issue by starostin** [scrumpy/tiptap#269]
Hi, thanks for this plugin. It is very useful fo me)
Before I used version 1.4.0, and seems everything worked fine, but now I need some fixes that already exist in new version, so I decided to update to latest version. But when I tap on Enter on the keyboard (when cursor on the beginning of the raw) nothing happens. When there is text after cursor - then it works fine, but if the raw is empty - it does not. Help me please with this, I very want to update this package. Thanks!

**Comment by svennerberg** [comment]
+1 I have the same problem when upgrading from 1.9.0 to 1.16.2

**Comment by philippkuehn** [comment]
Hmm, I cant' reproduce this at https://tiptap.scrumpy.io on the latest Chrome or Firefox :/

**Comment by svennerberg** [comment]
It's weird, I tried to go back to 1.9.0 just to verify that it worked there, which it of course did. Then I went back to 1.16.2 again and then I didn't have the problem anymore. Very strange.

**Comment by philippkuehn** [comment]
@starostin can you provide a codesandbox or something?

**Comment by mariux** [comment]
we had run into the same problem and fixed it by a fresh install of all modules. so probably for us some outdated dependency happened to cause this issue.

**Comment by starostin** [comment]
Hi, sorry for delay. For now I am using "tiptap": "1.16.2" and "tiptap-extensions": "1.7.0". And it works, but with "tiptap-extensions": "1.16.2" it did not work for me. I will try to create some codesandbox today

**Comment by starostin** [comment]
Hi, I have just updated to the latest version, and everything works fine. Thanks!
