### ISSUE TITLE
Draggable Page Node

### ISSUE THREAD

**Issue by asseti6** [scrumpy/tiptap#270]
@philippkuehn is there already support for a draggable page node to allow the editor to span across multiple pages with `page-break-before` and/or `page-break-after` tags?  

I don't mind creating it and pushing over a PR, but wanted to make sure I am not duplicating work here.

**Comment by philippkuehn** [comment]
Hey, no there is no support and I don't have plans to support this in the core. But feel free to release a package on npm.

**Comment by rajajatayu** [comment]
is  there any package now for page break support ??
