### ISSUE TITLE
How to disable markdown behaviour and input/paste rules in Tiptap?

### ISSUE THREAD

**Issue by jgabis** [scrumpy/tiptap#271]
Hi,

I have noticed that because of the markdown conversion the copy/paste behaviour is not 100% correct. When I paste for example a file name 'file_name_example.pdf' I get a string without underscores but with one part marked as italic (which is kinda obvious). The thing is, I do not want that or any other paste/input rules because my client simply doesn't need it, but needs an easy to understand copy-paste behaviour instead.

The question is: **how to disable the markdown and input/paste rules in Tiptap?** I have found some ways to do this in ProseMirror, but I have no idea where to put it in my Tiptap component. I have tried without success:
1. setting autoInput to false (as mentioned here: https://prosemirror.net/docs/ref/version/0.3.0.html#autoInput) but have no idea where it should be defined in my tiptap instance
2. manipulate the copy/paste action on handlePaste and transformPasted
3. changing format markdown to false
4. setting the editor pasteRules and inputRules to empty arrays/null onInit

I do not want to edit each extension's js file and I am sure there is a way to set it in editor as a props or something similar, without changing the core code.

None of the ways mentioned above works and I am really running out of ideas how to do it. I am having problem understanding how to use proseMirror props/settings etc. in Tiptap. I will appreciate any hints and answers!

**Comment by philippkuehn** [comment]
Do you want to disable **all** or just **some** input/paste rules?

**Comment by Aymkdn** [comment]
For people looking at this, and using tiptap v1.13.0, see my answer there: https://github.com/ueberdosis/tiptap/discussions/850#discussioncomment-91532

Basically, you can pass `disablePasteRules:true` and `disableInputRules:true` to the `new Editor()`.
