### ISSUE TITLE
BubbleMenu and FloatingMenu do not work now.

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#289]
**Describe the bug**
BubbleMenu and FloatingMenu does not work now. I do NOT know what's going on ? When I rewrite my editor, I notice that the basic plugins does not Work. I add some `console.log()` in its `onUpdate()` like the following:
```javascript
// EditorMenuBubble.js 
 return editor.registerPlugin(MenuBubble({
                            element: this.$el,
                            keepInBounds: this.keepInBounds,
                            onUpdate: menu => {
                                console.log("on Update", menu);
                                // the second check ensures event is fired only once
                                if (menu.isActive && this.menu.isActive === false) {
                                    this.$emit('show', menu)
                                } else if (!menu.isActive && this.menu.isActive === true) {
                                    this.$emit('hide', menu)
                                }
                                this.menu = menu
                            },
                        }));
```
However, nothing happens in the output, selecting text do not trigger the menu to pop up. I try many times and can not figure it out. And further,  I found the bubblemenu in  [live demo](https://tiptap.scrumpy.io) does not work too and the floating menu as well. 

**Steps to Reproduce / Codesandbox Example**
Just open [live examples](https://tiptap.scrumpy.io/menu-bubble), and select some text.

**Screenshots**
![1222](https://user-images.githubusercontent.com/13865581/57221544-3f0cf400-7032-11e9-858e-d487f874029f.gif)
![May-06-2019 19-06-47](https://user-images.githubusercontent.com/13865581/57221545-4207e480-7032-11e9-984c-1c6c4b0419b7.gif)

**Environment**
 - OS: macOS Mojave 10.14.3
 - Browse:
     - Chrome Version  73.0.3683.103 && 74.0.3729.131
     - Safari 12.0.3 (14606.4.5)
 - Version: Latest
 - Mobile / Desktop:  Desktop

**Comment by philippkuehn** [comment]
oh no! looking into it.

**Comment by philippkuehn** [comment]
Hmm, this seems to be a bug with ProseMirror :(
You can follow up [here](https://discuss.prosemirror.net/t/state-reconfigure-do-not-apply-new-plugins/1931).

**Comment by Alecyrus** [comment]
Em, and I try this [tooltip](http://prosemirror.net/examples/tooltip/), not work too.

**Comment by philippkuehn** [comment]
Yeah state.reconfigure is not working anymore for view updates. This method is used for adding plugins after initializing the editor.

**Comment by Alecyrus** [comment]
@philippkuehn  Have you seen [this](https://glitch.com/edit/#!/determined-snowplow?path=index.js:53:38) ?

**Comment by Alecyrus** [comment]
So `reconfigure` is not the true reason now...

**Comment by philippkuehn** [comment]
Argh I don't get it :/

**Comment by Alecyrus** [comment]
Sorry for saying that. It's my mistake.  Have you figure it out ??

**Comment by philippkuehn** [comment]
Noo, I don't get it what's wrong. I don't changed anything there :D

**Comment by philippkuehn** [comment]
Okay, still seems to be the same bug with prosemirror. I've created a [codesandbox](https://codesandbox.io/s/wnjk2y0y95) where you can reproduce this error.

**Comment by dev7ch** [comment]
having the same problem :(

**Comment by HollyIT** [comment]
It appears to be a breaking change between prosemirror-view 1.8.9 and 1.9.0.  In [this commit](https://github.com/ProseMirror/prosemirror-view/commit/c99df74257fde328394cb30c9745d28cc958325c#diff-1fdf421c05c1140f6d71444ea2b27638L165) reconfigured appears to have been dropped as a parameter when updating plugin views.

I'm almost wondering if the way we were doing it before isn't rather hackish. The PM guide states plugins should be added when the state is created. A project I'm working on, I did a work around for this bug/change by adding a plugins:[] options to the Editor class, then merging it with the default plugins. That means plugins have to be added when the editor is created, but it's working fine in my scenario.

**Comment by Alecyrus** [comment]
I have a [PR](https://github.com/scrumpy/tiptap/pull/294) for this issue. unless further change happens in `prosemirror-view`, the possible solution is to call `updatePluginViews()` manually, which works temporarily now. See [#289 deploy preview ](https://deploy-preview-294--scrumpy-tiptap.netlify.com/)
