### ISSUE TITLE
[Question] Is there a way to make <div> default wrapper instead of <p>?

### ISSUE THREAD

**Issue by leandrowkz** [scrumpy/tiptap#291]
Every time we hit **enter** inside editor, the content is wrapped by a `<p>` element. Is there a way to change it to `<div>`?

Version:
**tiptap@1.18.0**
**tiptap-extensions@1.18.0**

Current behavior:
```html
<div contenteditable="true" tabindex="0" class="ProseMirror" style="white-space: pre-wrap;">
  <p>first content</p>
  <p>second content</p>
  <p>third content</p>
</div>
```

Expected:
```html
<div contenteditable="true" tabindex="0" class="ProseMirror" style="white-space: pre-wrap;">
  <div>first content</div>
  <div>second content</div>
  <div>third content</div>
</div>
```

**Comment by philippkuehn** [comment]
You can set `useBuiltInExtension` to `false` and use a custom paragraph extension. [This](https://github.com/scrumpy/tiptap/issues/96#issuecomment-441203743) should help.

**Comment by leandrowkz** [comment]
Thanks @philippkuehn! I've ended up with the following code (which worked for me):

```javascript
import {
  Editor,
  EditorContent,
  EditorMenuBar,
  Node,
  Text,
  Doc,
} from 'tiptap';

class Paragraph extends Node {
  get name() {
    return 'paragraph';
  }

  get schema() {
    return {
      content: 'inline*',
      draggable: false,
      group: 'block',
      parseDOM: [{
        tag: 'div',
      }],
      toDOM() {
        return ['div', 0];
      },
    };
  }
}

new Editor({
  useBuiltInExtensions: false,
  extensions: [
    new Doc(),
    new Text(),
    new Paragraph(),
    // ...
  ],
 // ...
});
```

If something does not agree with the rewrite of Paragraph then let me know ;)

**Comment by spencergritton** [comment]
For Tip Tap 2 Beta you just need to create an extension of the Paragraph extension that changes the default tag from `p` to `div` like so:

`ParagraphDiv.js`
```
import { Node, mergeAttributes } from '@tiptap/core'

// Tip Tap Paragraph Extension that changes the default tag to div from p
// Based on: https://github.com/ueberdosis/tiptap/tree/main/packages/extension-paragraph
const ParagraphDiv = Node.create({
	name: 'paragraphDiv',

	priority: 1000,

	defaultOptions: {
		HTMLAttributes: {},
	},

	group: 'block',

	content: 'inline*',

	parseHTML() {
		return [
			{ tag: 'div' },
		]
	},

	renderHTML({ HTMLAttributes }) {
		return ['div', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0]
	},

	addCommands() {
		return {
			setParagraph: () => ({ commands }) => {
				return commands.toggleNode('paragraphDiv', 'paragraphDiv')
			},
		}
	},
});

export default ParagraphDiv;
```
`Vue Component`
```
<script>
...
import ParagraphDiv from "./ParagraphDiv.js";
...
mounted() {
        this.editor = new Editor({
            extensions: [
                Document,
                ParagraphDiv, // Replaces Paragraph
                Text,
            ],
            content: this.value,
            editorProps: {
                attributes: {
                    class: "tailwind-classes",
                },
            },
            // Emit input on update for v-model
            onUpdate: () => {
                this.$emit(
                    "input",
                    this.editor.getHTML()
                );
            },
        });
    },
...
</script>
```

**Comment by JodliDev** [comment]
This solution seems to not work well with lists.
Thanks to the code provided by @spencergritton and [here](https://github.com/ueberdosis/tiptap/issues/426#issuecomment-845413710) I found a slightly different approach (by extending the existing Paragraph extension and just replacing the parts that control the tag type) that seems to work well for me:

```
import Paragraph from '@tiptap/extension-paragraph';

...

this.editor = new Editor({
	extensions: [
		StarterKit,
		Paragraph.extend({
			parseHTML() {
				return [{ tag: 'div' }]
			},
			renderHTML({ HTMLAttributes }) {
				return ['div', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0]
			},
		})
	]
});
```

**Comment by ardok** [comment]
> This solution seems to not work well with lists. Thanks to the code provided by @spencergritton and [here](https://github.com/ueberdosis/tiptap/issues/426#issuecomment-845413710) I found a slightly different approach (by extending the existing Paragraph extension and just replacing the parts that control the tag type) that seems to work well for me:
> 
> ```
> import Paragraph from '@tiptap/extension-paragraph';
> 
> ...
> 
> this.editor = new Editor({
> 	extensions: [
> 		StarterKit,
> 		Paragraph.extend({
> 			parseHTML() {
> 				return [{ tag: 'div' }]
> 			},
> 			renderHTML({ HTMLAttributes }) {
> 				return ['div', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0]
> 			},
> 		})
> 	]
> });
> ```

Just in case someone is wondering where `mergeAttributes` come from:
```
import { mergeAttributes } from '@tiptap/core';
```
