### ISSUE TITLE
Weird transparent rectangle

### ISSUE THREAD

**Issue by clemishow** [scrumpy/tiptap#292]
**Describe the bug**
Transparent rectangle with border at first line. 
When I update the DOM with Chrome debugger changing a width or height of class `.ProseMirror` It works.

**Steps to Reproduce / Codesandbox Example**
1. Init tiptap editor with content

**Expected behavior**
No rectangle

**Screenshots**
<img width="71" alt="Screenshot 2019-05-06 at 23 03 41" src="https://user-images.githubusercontent.com/9325482/57255269-a4bda800-7053-11e9-837e-7a383e90cad9.png">

**Environment**
 - OS: Mac OS 10.14.4
 - Browser [chrome]
 - Version [74.0.3729.131]
 - Mobile / Desktop: [Desktop]

**Comment by Alecyrus** [comment]
Maybe it caused by `:focus` that is set to `*` by default.

**Comment by clemishow** [comment]
<img width="1280" alt="Screenshot 2019-05-07 at 10 43 08" src="https://user-images.githubusercontent.com/9325482/57286130-f0546e00-70b4-11e9-9302-38af23eb2bd9.png">
Not working !

**Comment by Alecyrus** [comment]
Could you create a codesandbox to reproduce it ??

**Comment by clemishow** [comment]
I'm doing it tomorrow !

**Comment by clemishow** [comment]
I cannot reproduce this bug. But it seems to be happen when I use Ant Design library.
Thanks for your reactivity.
