### ISSUE TITLE
Limit number of characters in editor

### ISSUE THREAD

**Issue by kskrlin** [scrumpy/tiptap#293]
Is there any example/solution/feature/extension within this editor to limit number of characters?

For example, textarea has maxlength;
TinyMCE editor has examples how to make it.

**Comment by Alecyrus** [comment]
Write a `plugin` to count characters, see [this](http://prosemirror.net/examples/tooltip/)

**Comment by Chrissi2812** [comment]
I've written a basic demo https://codesandbox.io/s/3204l3on1q

*PS. Deletion doesn't quite work at the moment* (Maybe someone can fix this)

**Comment by philippkuehn** [comment]
Thanks @Chrissi2812! Something like that is the way to go so I'll close this here.

**Comment by usb248** [comment]
@Chrissi2812 your solution is so buggy.
Any working solution ?
It's a basic functionality

**Comment by marcpaskell** [comment]
Anyone found a reliable way to do this?

**Comment by medvinator** [comment]
An approximate solution could be like this (it remains to refine the cropping of pasted text)
```js
new Editor({
    ...
    editorProps: {
      handleTextInput: (view) => {
        if (this.maxlength && view.state.doc.textContent.length >= this.maxlength && view.state.selection.empty) {
          return true;
        }
      },
      handlePaste: (view, event, slice) => {
        if (this.maxlength && view.state.doc.textContent.length + slice.size > this.maxlength) {
          slice.content = new DocumentFragment();
        }
      },
    },
    ...
}); 
```

**Comment by usb248** [comment]
When i see the code :
![image](https://user-images.githubusercontent.com/7659927/73127563-8cffc880-3fc2-11ea-9a07-68b86f29b8cd.png)
Without any documentation a little bit detailed... Good luck !
