### ISSUE TITLE
Builtin webworker support and  debounce  support

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#295]
## Description
When many extensions is mounted on the `Editor` instance, for example, like some extension that includes some complex work, such as computing tasks like regular matching even I/O tasks like HTTP Request,  in my case, extensions with 10+ regular matching tasks,  could cost `62ms` to run on relatively largely documents(eg. 2000+ words)  after every `input` event.  

## Possible solutions
For now, I want to debounce the builtin `transaction( or document update)` event that creates a new state on old state, which means the transaction could be dispatched after users stop typing. Or another solution is  to run the complex and time-consuming  work in webworker or background so that it would not block the main UI thread, yes, like `vscode` does, which  enables `linter`,  `formater`, `hignlighting` run in background.

**Comment by philippkuehn** [comment]
I‘ve added a debounce option to the new collab extension but maybe it‘s more useful for the global update hook! Will try it.

But for now I have zero experience with webworkers so any help is welcome 😅

**Comment by Alecyrus** [comment]
I will be working on it with a practical benchmark later...

**Comment by philippkuehn** [comment]
for now I dont have plans to implement this.

**Comment by growupanand** [comment]
I want to use debounce in mention extension to reduce api calls while typing. Is there any solution for that ?

**Comment by growupanand** [comment]
I was using debounce from lodash, which was not async supported so it was not working before.

Now i switch to debounce from  [awesome-debounce-promise](https://www.npmjs.com/package/awesome-debounce-promise) , which support async and now it is working.

**Comment by kienmatu** [comment]
Hi @growupanand, can you share me your solution, big thanks!
