### ISSUE TITLE
Fixed / maximum height

### ISSUE THREAD

**Issue by RicLeP** [scrumpy/tiptap#302]
When editing long documents the text region becomes taller than the screen meaning users must scroll up to see the menu. Each time a button is pressed the screen then scrolls to the selected text meaning they must scroll up again to perform a section action. This makes it unwieldy to use.

It would be help to have a fixed or maximum height property.

Alternative the menu could be set to be sticky. This is different to the bubble or floating menu in that all controls are visible which is important in some cases.

**Comment by philippkuehn** [comment]
tiptap is renderless, so styling is all up to you.
