### ISSUE TITLE
Editable content inside a view not reflecting in the prosemirror document

### ISSUE THREAD

**Issue by dSolid** [scrumpy/tiptap#304]
**Describe the bug**
Something changed in one of the latest updates which causes the contenteditable inside the view of a component to not update the prosemirror document. In my case it was updating the caption of an image you add, it used to work as you'll see in the Codesandbox exemple, but in the latest version I can't seem to get it to work again.

**Steps to Reproduce / Codesandbox Example**
1. Add an image with the menu or drag and drop
2. Try to enter text inside the placeholder
3. The onUpdate method of the editor should trigger to see the changes made to the document

This is the Codesandbox setup that has the component inside which ironically doesn't have the issue:
https://codesandbox.io/s/5xrm89rmyx

**Screenshots**
This is an exemple of what it does when its not working:
![image](https://user-images.githubusercontent.com/1765255/57462601-232e6b80-7247-11e9-81ec-ac8b7bc1931e.png)

**Comment by philippkuehn** [comment]
Hmm, I think something changed in ProseMirror in the latest updates. The major issue is fixable with adding a `contenteditable="false"` to your wrapper div of your image node. But can see that your computed `captionEmpty` still isn't working after that. I think this is a new optimization of ProseMirror to not update node views whenever a child node (your image caption) is updated.

**Comment by Alecyrus** [comment]
I don't get it....I open the codesandbox, and it works well.

**Comment by dSolid** [comment]
Because the codesandbox is on an old version where it used to work

**Comment by philippkuehn** [comment]
okay I can reproduce this bug for some extension at scrumpy too.

**Comment by philippkuehn** [comment]
I hope this is a bug in ProseMirror. I created a [thread](https://discuss.prosemirror.net/t/ignoremutation-for-node-views-prevent-update-of-child-nodes/1944).

**Comment by dSolid** [comment]
Hopefully its an issue on their end as well, or theres a way to fix it.

**Comment by dSolid** [comment]
@philippkuehn now when I create that image node, it straight up goes on forever and locks everything up, did I have to change anything?

**Comment by philippkuehn** [comment]
oh no. I'm sorry. can't reproduce this in my local tests. will open up this issue again :(

**Comment by dSolid** [comment]
Apparently my is-empty computed is the issue, otherwise it works perfectly. How should I go around verifying if the content is empty in order to show a placeholder text?

**Comment by philippkuehn** [comment]
ah! the problem is this line: 
```
<p ref="content" :class="{ 'is-empty': captionEmpty }"></p>
```
It seems that this will cause an infinite loop, whenever you update node view children (the element with ref="content" – in ProseMirror it's called holes). Try to do something like that:

```
<div :class="{ 'is-empty': captionEmpty }">
   <p ref="content"></p>
</div>
```

BTW: you can check `this.node.content.size` instead of `this.$refs.content.innerHTML`

**Comment by dSolid** [comment]
I was quite literally typing that as you did, its why I closed the issue, and yeah its what I ended up doing to fix the issue. I will check node.content.size though, at the time I didnt know you could add props like node to a component. Thanks!

**Comment by philippkuehn** [comment]
Yeah this seems to be another issue. Interesting that only mouse selection is broken. Selection via keyboard is working fine.

**Comment by philippkuehn** [comment]
This behavior is because of your `selectNode` event handler. I'm not sure what you wanted to do and how it worked before. But since the latest versions the event handling for child nodes is probably a bit different.

**Comment by dSolid** [comment]
This still works, it is to show a contextual menu when you select the node and highlight it in blue in this case. Is there another way I can keep track of which node is selected? The prosemirror way to select node doesn't work too great with vue components it seems, whenever I click or try to select the node using this it would never work like I want.

**Comment by Sakessonholm** [comment]
> This still works, it is to show a contextual menu when you select the node and highlight it in blue in this case. Is there another way I can keep track of which node is selected? The prosemirror way to select node doesn't work too great with vue components it seems, whenever I click or try to select the node using this it would never work like I want.

Did you ever find a solution to this @dSolid ? Selecting content inside a vue component doesn't seem to play too well with prosemirror. It's as if prosemirror doesn't see it at all. I have a very similar case as yours described above and have the same logic for selecting an image to show a menu. Selecting it obviously works since the selection logic is inside the vue component, but I also have other menus outside of it and they don't play too well with each other since they don't "know" of each other.
