### ISSUE TITLE
Clean format on Paste

### ISSUE THREAD

**Issue by ligne13** [scrumpy/tiptap#306]
Is it possible to clear formatting when pasting some text ?
Can you add this feature ?

thanks

**Comment by philippkuehn** [comment]
you can create an extension for that and strip tags or something. there are some ProseMirror events you can look at:
- `transformPastedText` for pasted plain text
- `transformPastedHTML` for pasted HTML
- `transformPasted` after converting text/HTML to JSON

**Comment by ligne13** [comment]
OK thank you

**Comment by ilhamsabir** [comment]
can you show me how you can use transformPastedText ?

**Comment by domnantas** [comment]
@ilhamsabir here's an example: https://github.com/ueberdosis/tiptap/issues/943#issuecomment-923253918
