### ISSUE TITLE
Uncaught RangeError after setContent in onFocus function

### ISSUE THREAD

**Issue by CaptainYouz** [scrumpy/tiptap#307]
**Describe the bug**
I try to implement a placeholder-like feature in my tiptap component.
I get a placeholder and a content parameter from the parent component, and if the content parameter is empty, I put the placeholder parameter as the default text inside the tiptap-editor.
On the `onFocus` method, i want to make the placeholder disappear on the first focus. But when i try to use the `setContent` method, i get a Uncaught RangeError error in the console (see screenshot)

Here is my code component:
```

export default {
  name: 'quick-editor',
  components: {
    EditorContent,
    EditorMenuBar
  },
  props: ['parentContent', 'blur', 'placeholder'],
  data() {
    return {
      editorContent: this.parentContent,
      isFocus: false,
      editor: new Editor({
        extensions: [
          new Blockquote(),
          new BulletList(),
          new CodeBlock(),
          new HardBreak(),
          new Heading({ levels: [1, 2, 3] }),
          new HorizontalRule(),
          new ListItem(),
          new OrderedList(),
          new TodoItem(),
          new TodoList(),
          new Link(),
          new Bold(),
          new Italic(),
          new Strike(),
          new Underline(),
          new History()
        ],
        content: this.parentContent || '<i>' + this.placeholder + '</i>',
        onFocus: () => {
          if (!this.parentContent && !this.hasBeenUpdated) {
            this.editor.setContent(''); // here i get the uncaught rangeError
          }
          this.isFocus = true;
        },
        onBlur: () => {
          this.isFocus = false;
          this.blur(this.editorContent);
        },
        onUpdate: (e) => {
          if (!this.hasBeenUpdated) this.hasBeenUpdated = true;
          this.editorContent = e.getJSON().content[0].content ? e.getHTML() : '';
        }
      })
    };
  },
  beforeDestroy() {
    this.editor.destroy();
  }
};
```

<img width="473" alt="Screenshot 2019-05-09 at 19 42 48" src="https://user-images.githubusercontent.com/2973285/57475111-f48ab200-7293-11e9-8e7d-a75a52ceba2d.png">

**Environment**
 - OS: macOs Mojave 10.14.4
 - Browser: Chrome
 - Version: Version 74.0.3729.131 (Official Build) (64-bit)
 - Desktop

**Comment by philippkuehn** [comment]
you can use `this.editor.clearContent()` instead of `this.editor.setContent('')`

**Comment by CaptainYouz** [comment]
Hi Phillipp, thanks for the reply!
I already tried, and I still get the error.

**Comment by CaptainYouz** [comment]
Hi @philippkuehn ,
any news on this one ?

**Comment by philippkuehn** [comment]
I can reproduce this bug but I'm not sure whats wrong here. In my tests it has something to do with `prosemirror-gapcursor` which I'm using as a core plugin.

**Comment by CaptainYouz** [comment]
Alright, thank you for time. 
What about introducing a placeholder feature in tiptap? Do you think it's possible? If yes, I can try to do  a PR for that.

**Comment by philippkuehn** [comment]
There is already a [placeholder extension](https://tiptap.scrumpy.io/placeholder). But I think it doesn't  work for nested nodes at the moment.

**Comment by philippkuehn** [comment]
Can you please test it again with the latest version?

**Comment by CaptainYouz** [comment]
Hi @philippkuehn .
I just tested with the v1.19.6, and the bug is fixed! Many thanks :)

(i just had to change the style of the div with contenteditable at true to remove the outline, but that is not a bug ;))

Again, thanks!
