### ISSUE TITLE
Examples error in ie11

### ISSUE THREAD

**Issue by AlecTroemel** [scrumpy/tiptap#308]
**Describe the bug**
All examples at https://tiptap.scrumpy.io/ show the following errors

```
Unable to get property 'concat' of undefined or null reference
Object doesn't support property or method 'setTimeout'
```

in addition, the suggestions example doesnt show the popup

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.scrumpy.io/
2. open console
3. start typing 

**Expected behavior**
No errors printed to the console

**Environment**
 - OS: Windows 10
 - Browser ie11
 - Desktop

**Comment by AlecTroemel** [comment]
this is really caused by https://github.com/ProseMirror/prosemirror/issues/927

**Comment by philippkuehn** [comment]
Since this is caused by ProseMirror I'll close this here. Thanks for creating an issue at ProseMirror!
