### ISSUE TITLE
Hyperlinks inside of lists are opened 3+ times

### ISSUE THREAD

**Issue by bbbford** [scrumpy/tiptap#311]
**Describe the bug**
When you click on a hyperlink that is inside of a list (bullet, numbered, etc.), it will open 3 or more times, depending on the depth of the link inside of the list.

**Steps to Reproduce / Codesandbox Example**
1. Go to this example - https://tiptap.scrumpy.io/links
2. Paste a link into the editor and click on it - it will open the link once, as expected
3. Create a bulleted list and paste the link into the list. Click on the link - it will open 3 times
4. Add a sub-bullet and paste the link. Click on the link - it will open 5 times.

**Expected behavior**
Clicking on the link should open it one time.

**Screenshots**
![image](https://user-images.githubusercontent.com/5225875/57654400-acbca100-7599-11e9-8447-8130f463e8e6.png)

**Environment**
 - OS: Mac
 - Browser Chrome
 - Version 74.0.3729.131 (Official Build) (64-bit)
 - Mobile / Desktop: Desktop

**Comment by philippkuehn** [comment]
It's released. (tiptap-extensions@1.19.3)

**Comment by bbbford** [comment]
Thank you!
