### ISSUE TITLE
Is it possible to prevent new line by enter?

### ISSUE THREAD

**Issue by starostin** [scrumpy/tiptap#313]
**Describe the bug**
Right now when I tap Enter there is new line appear, is it possible to call some other action and prevent new line?

**Steps to Reproduce / Codesandbox Example**
Open https://tiptap.scrumpy.io/history
Click Enter

**Expected behavior**
I want to call another action by clicking on Enter

**Comment by philippkuehn** [comment]
I'm not sure why you labeled this as a bug, but you can create a custom Extension for it.

```js
import { Extension, Plugin } from 'tiptap'

export default class EnterHandler extends Extension {

  get name() {
    return 'enter_handler'
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          handleKeyDown: (view, event) => {
            if (event.key === 'Enter' && !event.shiftKey) {
              // do something
              return true
            }

            return false
          },
        },
      }),
    ]
  }

}
```

**Comment by starostin** [comment]
Yes, it works! Thanks a lot, specially for quick response.

**Comment by TheBestMoshe** [comment]
Here is a tiptap v2 example:

```typescript
import { Extension } from '@tiptap/core'
import { Plugin, PluginKey } from 'prosemirror-state'

export const NoNewLine = Extension.create({
  name: 'no_new_line',

  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey('eventHandler'),
        props: {
            handleKeyDown: (view, event) => {
                if (event.key === 'Enter' && !event.shiftKey) {
                    console.log("enter pressed")
                    return true
                }
          }
          // … and many, many more.
          // Here is the full list: https://prosemirror.net/docs/ref/#view.EditorProps
        },
      }),
    ]
  },
})
```

**Comment by ZizhengTai** [comment]
How can I prevent this from interfering with the Mention extension? With the example code above, I can't press Enter to select a suggested Mention item.

**Comment by ZizhengTai** [comment]
> How can I prevent this from interfering with the Mention extension? With the example code above, I can't press Enter to select a suggested Mention item.

Turned out I can just add the `Mention` extension after (not before) this one.

**Comment by apuntovanini** [comment]
@zizhengtai it seems I cannot make it work, despite importing the Mention extension after the other one. How did you solve it?
