### ISSUE TITLE
Cursor overlapping non-editable node

### ISSUE THREAD

**Issue by rodrigoterminus** [scrumpy/tiptap#315]
Hi. First of all, thank you guys for this awesome package. It has been helping me a lot to create the product I am working on.

In our implementation, we have to highlight the tags within a sentence. We have created a Node extension to achieve that and it works well, excepting the fact that the cursor overlaps the node, which is non-editable. 
![image](https://user-images.githubusercontent.com/8169941/57857879-4da49980-77f0-11e9-9aa0-e129a2a89241.png)

That only happens when the node is the first element in the editor. When it's placed in any other position the cursor behaves as expected, jumping over the node and staying around it.
![image](https://user-images.githubusercontent.com/8169941/57858036-952b2580-77f0-11e9-91b1-f6d68b5d0d74.png)

Here you can find our Tag Node implementation:
```
import { Node } from 'tiptap';

export default class Tag extends Node {
  get name() {
    return 'tag';
  }

  get schema() {
    return {
      inline: true,
      group: 'inline',
      content: 'text*',
      attrs: {
        class: {
          default: [],
        },
        contenteditable: {
          default: false,
        },
        'data-id': {
          default: null,
        },
        'data-type': {
          default: null,
        },
        'data-node-name': {
          default: null,
        },
        draggable: {
          default: true,
        },
      },
      parseDOM: [
        { tag: 'tag', getAttrs: this.readAttributes },
      ],
      toDOM: mark => ([
        'tag',
        mark.attrs,
        0,
      ]),
    };
  }

  readAttributes = (dom) => {
    this.options.tagName = dom.tagName;

    return {
      class: dom.classList.value,
      'data-id': dom.getAttribute('data-id'),
      'data-type': dom.getAttribute('data-type'),
      'data-node-name': dom.getAttribute('data-node-name'),
    };
  }
}
```

The element created by the node is an `inline-block` element with the following CSS as its base. Other styles might be applied on top of that depending on the kind of tag, but as pointed above, they work as expected when they are placed in any position other than the first one in the editor.

```
.tag {
  display: inline-block;
  min-height: 14px;
  background-color: grey;
  color: white;
  padding: 0 4px;
  margin: 0 1px;
  font-size: 9px;
  font-weight: 600;
  border-radius: 2px;
  cursor: pointer;
  vertical-align: middle;
}
```

**Expected behavior:**
The cursor should jump over a non-editable node no matter which position it is placed in the editor.

**Environment**
 - Browser: Chrome (76.0.3788.1)
 - Version 1.19.4
 - Mobile / Desktop: Desktop

Thank you all in advance. :)

**Comment by philippkuehn** [comment]
This seems to be related to ProseMirror, sorry!

**Comment by Art3miX** [comment]
@rodrigoterminus Did you find a fix to it by any chance? 

I'm trying to do a non-editable mark, the only issue I found was that when we move the cursor to the right of the mark, it edits the mark, when the cursor is on the left of the mark, its working as expected and writing outside the mark, but when the cursor is on the right its writing inside the mark.
