### ISSUE TITLE
Can't figure out how to render HTML with inline styles.

### ISSUE THREAD

**Issue by alekspetrov** [scrumpy/tiptap#319]
Hi, awesome plugin, but I can't render inline styles, all attributes cleanup after setContent(). 

I need to render HTML inside editor with inline styles on nodes. What should I do?

**Comment by alekspetrov** [comment]
Also it replaces `div` with `p` tags... I need to render all my HTML as it is, please let me know if it's possible.

**Comment by philippkuehn** [comment]
ProseMirror is very strict. You have to define a [schema](https://prosemirror.net/docs/guide/#schema) of how your content will be parsed. For every HTML tag you want to support you have to build an extension. By default all unnecessary tags and attributes will be stripped. And that's a good thing, because you'll have full control of how your content will be stored. This is definitely one of ProseMirrors biggest strengths.

In these core packages there is no extension that will keep divs or *all* attributes but it's up to you to build your own.

**Comment by alekspetrov** [comment]
Thanks for explanation, will explore a schema definition, but I think it'll be difficult to define all html tags =/

**Comment by philippkuehn** [comment]
Yeah maybe ProseMirror is not your editor then.

**Comment by alekspetrov** [comment]
I'll appreciate any recommendations, I'm building something like email templater and need to see all the things from html in preview and at the same time I need to edit this preview with simple wysiwyg editor.

**Comment by RyonMB** [comment]
@alekspetrov Did you find a solution?

**Comment by alekspetrov** [comment]
> @alekspetrov Did you find a solution?

Yes, but without the editor, now I have block editor with configurable inline styles as props for each block.

**Comment by kyonkopa** [comment]
Can anyone elaborate how to define a schema? ProseMirror docs is an API documentation and doesn't give much info on how to actually define a schema

**Comment by philippkuehn** [comment]
@kyonkopa https://www.tiptap.dev/api/schema/#schema

**Comment by jannikbuschke** [comment]
Feeling a little bit stupid, I just cannot get tiptap to allow any inline styles. Can someone give a code examples where i.e. these attributes would not get stripped?

```
<div style="margin-top:24px; margin-bottom:20px"><span style="font-size:24px; color:#252424">blaa</span>
```

**Comment by Le0nX** [comment]
@jannikbuschke Hi! Have you found the solution?

**Comment by rini001** [comment]
> Feeling a little bit stupid, I just cannot get tiptap to allow any inline styles. Can someone give a code examples where i.e. these attributes would not get stripped?
> 
> ```
> <div style="margin-top:24px; margin-bottom:20px"><span style="font-size:24px; color:#252424">blaa</span>
> `
Have you find the solution?

**Comment by rini001** [comment]
@jannikbuschke Have you found the solution?

**Comment by jlow2397** [comment]
After a bit of digging, it looks like you'll have to retrieve the styles via the `addAttributes` and `parseHtml` functions when defining the extension

https://tiptap.dev/guide/custom-extensions#schema

Here's how I implemented it on a Table:

```
      Table.extend({
        addAttributes() {
          return {
            style: {
              parseHTML: (element) => element.style?.cssText
            }
          }
        },
        renderHTML(props) {
          return ['table', props.HTMLAttributes, 0]
        }
      }),
```

**Comment by maggie-chintaro** [comment]
Has anyone managed to make a custom extension for maintaining styles?

**Comment by omarqra** [comment]
I encountered similar today, all the attributes were missing when i tried:
`
editor.commands.setContent('<span pragmatical_name="{{tem_ar_name}}" title="اسم الضيف بالعربية" class="custom-dynamic-info" style="color: #ec0c0c;">{{ar_name}}</span>');
console.log('Editor content:', editor.getHTML());
`
after search it seemed to be the priority property was missed so i added it and it worked like this:
`
parseHTML() {
	return [
		{
			tag: 'span.custom-dynamic-info',
			priority: 1000,
			getAttrs: dom => {
				return {
					pragmatical_name: dom.getAttribute('pragmatical_name')?.replaceAll("tem_", ""),
					title: dom.getAttribute('title'),
					class: dom.getAttribute('class'),
					textColor: dom.getAttribute('textColor'),
				}
			},
		},
	];
},
`

**Comment by maggie-chintaro** [comment]
> After a bit of digging, it looks like you'll have to retrieve the styles via the `addAttributes` and `parseHtml` functions when defining the extension
> 
> https://tiptap.dev/guide/custom-extensions#schema
> 
> Here's how I implemented it on a Table:
> 
> ```
>       Table.extend({
>         addAttributes() {
>           return {
>             style: {
>               parseHTML: (element) => element.style?.cssText
>             }
>           }
>         },
>         renderHTML(props) {
>           return ['table', props.HTMLAttributes, 0]
>         }
>       }),
> ```

this works really well for preserving inline styles but have you had any luck both extending and configuring the table settings? i also need to set the resize option to true, but at this stage I can only do one or the other.

**Comment by anatonokao** [comment]
@maggie-chintaro so have you found any solution?
