### ISSUE TITLE
SetContent shouldn't check editable

### ISSUE THREAD

**Issue by bvkimball** [scrumpy/tiptap#320]
The recent change to prevent `setContent` if `editable` is false make setting initial content difficult.

https://github.com/scrumpy/tiptap/commit/b7ed913860744c5615751877f8b23cac75f481cf

It seems like the requirement is to prevent `clearContents() `from clearing the editor.  IMHO i think that it makes more sense to put the `editable` check in the `clearContent` function and not in `setContents`.

I understand why it is there but i think the implementor should be responsible for that check.

**Comment by philippkuehn** [comment]
After thinking about it again I realized that this change wasn't good. There is already a release with a fix for that.
