### ISSUE TITLE
How to add/remove classes on span 

### ISSUE THREAD

**Issue by JBoenhoff** [scrumpy/tiptap#322]
Hi - I want to apply classes to parts of the text. I use the following extension (inspired by the Heading Extension):
```
import { Mark } from "tiptap";
import { updateMark } from "tiptap-commands";

export default class CustomStyle extends Mark {
  get name() {
    return "customstyle";
  }

  get defaultOptions() {
    return {
      levels: ["body-green", "body-red", "body-blue"]
    };
  }

  get schema() {
    return {
      attrs: {
        level: {
          default: "body-green"
        }
      },
      parseDOM: [
        {
          tag: "span.custom-style",
          getAttrs(dom) {
            console.log(dom.classList[1]);
            return { level: dom.classList[1] };
          }
        }
      ],
      toDOM: mark => {
        return ["span", { class: `custom-style ${mark.attrs.level}` }, 0];
      }
    };
  }

  commands({ type }) {
    return attrs => updateMark(type, attrs);
  }
}
```

In the menu I have these points:
```        
<button
class="menubar__button"
:class="{ 'is-active': isActive.customstyle({ level: 'body-green' }) }"
@click="commands.customstyle({ level: 'body-green' })">Body Green</button>
<button
class="menubar__button"
:class="{ 'is-active': isActive.customstyle({ level: 'body-blue' }) }"
@click="commands.customstyle({ level: 'body-blue' })">Body Blue</button>
<button
class="menubar__button"
:class="{ 'is-active': isActive.customstyle({ level: 'body-red' }) }"
@click="commands.customstyle({ level: 'body-red' })">Body Red</button>
```

I have also created a simple example here:
https://codesandbox.io/embed/vue-template-9x8fr

My questions/problems:

1. how can it remove the marker again? With a second command? The mark should be removed if the selected text already has the same class as the pressed button. `toggleMark` doesn't work for me because you can't add the attributes there.
2. how can i always mark only the corresponding class as Active in the menu? `isActive.customstyle({ level: 'body-green' })` always returns "true", no matter if the level matches the class.
3. is this the right way to reach my goal at all?

**Comment by pdiveris** [comment]
Hi there, I don't know if that helps but I seem to have resolved the issue by changing 
```
return attrs => updateMark(type, attrs);
```
to 
```
return attrs => toggleMark(type, attrs);
```
in your CustomStyle.js line 40.

**Comment by pat123456** [comment]
Hi,
Did you find a solution to resolve that problem ? 
 `isActive.customstyle({ level: 'body-green' })` always returns "true", no matter if the level matches the class.

**Comment by JBoenhoff** [comment]
> 
> 
> Hi,
> Did you find a solution to resolve that problem ? :
> `isActive.customstyle({ level: 'body-green' })` always returns "true", no matter if the level matches the class.

Yes, I use now
```js
getMarkAttrs('customstyle ').level === 'body-green'
```

You have to add to slot-scope `getMarkAttrs`
```js
slot-scope="{ commands, isActive, focused, getMarkAttrs }"
```


One of my initial Questions:
>how can it remove the marker again? With a second command? The mark should be removed if the selected text already has the same class as the pressed button. `toggleMark` doesn't work for me because you can't add the attributes there.

I fixed this by adding additional Menu-Button
```js
<button class="menubar__button" :class="{ 'is-active': getMarkAttrs('customstyle').level === null }" 
       @click="commands.customstyle({ level: null })">
       Remove Style
</button>
```

and to the commands I added it like this:
```js
commands({type}) {
    return attrs => {
        if (attrs.level === null) {
            return toggleMark(type, attrs)
        }
        return updateMark(type, attrs)
    }
}
```

**Comment by pat123456** [comment]
Hi, 
Thank you ! it work fine. Still mysterious why isActive doesn't work, may not correctly implemented with "Mark"
