### ISSUE TITLE
Collaboration - Invalid input for Step.fromJSON

### ISSUE THREAD

**Issue by bbbford** [scrumpy/tiptap#325]
**Describe the bug**
Uncaught RangeError when trying to send updates to the collaboration extension.

Error occurs when calling this.editor.extensions.options.collaboration.update

`          new Collaboration({
            version: this.thisDocument.version || 0,
            debounce: 250,
            onSendable: ( {sendable} ) => {
              this.editor.extensions.options.collaboration.update(sendable);
            }
          })
`

**Steps to Reproduce / Codesandbox Example**
https://codesandbox.io/embed/vue-issue-template-he812

**Expected behavior**
Error should not occur

**Screenshots**
![image](https://user-images.githubusercontent.com/5225875/58340010-6f190d00-7e10-11e9-92f9-059bc25d678d.png)
![image](https://user-images.githubusercontent.com/5225875/58340050-8b1cae80-7e10-11e9-9a83-9cd6bc588f1e.png)

**Environment**
 - OS: Mac
 - Browser Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)
 - Mobile / Desktop: Desktop

**Additional context**
Just trying to implement collaboration

**Comment by philippkuehn** [comment]
You try to update the editor itself. This does't make sense. The backend has to process and confirm all changes (steps). The response from the backend looks different then.

Here is an example of what I send to the backend:

![image](https://user-images.githubusercontent.com/2500670/58356944-4416d380-7e79-11e9-9232-3a26e958aee1.png)

And that's what the plugin expects to apply new steps locally:

![image](https://user-images.githubusercontent.com/2500670/58356969-598bfd80-7e79-11e9-8926-7e4c85c4fb35.png)
