### ISSUE TITLE
getHTML does not preserve styling

### ISSUE THREAD

**Issue by asseti6** [scrumpy/tiptap#331]
**Describe the bug**
When loading a JSON based document, if it is later retrieved via `getHTML()` then reset to the editor content, most styling will be lost.  This is important because sometimes it is appropriate to convert to HTML to manipulate the HTML content before loading it back into the editor.

**Steps to Reproduce / Codesandbox Example**
1. load editor with content
2. get content via `getHTML()`
3. Set content via `setContent` with the retrieved HTML
4. Most styling will be lost

**Expected behavior**
Tiptap should support at least switching between JSON and HTML on its own marks and nodes, but it would certainly be preferable for all direct properties in the style tag to be preserved.

**Comment by philippkuehn** [comment]
ProseMirror doesn't lose styling. All HTML will be normalized as defined in `toDOM` of each node/mark.

For example all of them will be converted to a basic `<strong>`:
```html
<p><strong>This is strong</strong></p>
<p><b>And this</b></p>
<p style="font-weight: bold">This as well</p>
<p style="font-weight: bolder">Oh! and this</p>
<p style="font-weight: 500">Cool! Right!?</p>
<p style="font-weight: 999">Up to 999!!!</p>
```

It's a feature to keep your stored HTML clean. If you want to support more stylings/attributes you have to define it in your schema. You can extend all extension or create your own, but I don't want to change this in the core at the moment.

**Comment by vortechron** [comment]
@philippkuehn can you show us how to preserve custom styles???

**Comment by ZolooAnzo** [comment]
how to set style in img tag in tip tap?

**Comment by piboistudios** [comment]
> ProseMirror doesn't lose styling. All HTML will be normalized as defined in `toDOM` of each node/mark.
> 
> For example all of them will be converted to a basic `\<strong\>`:
> 
> ```
> <p><strong>This is strong</strong></p>
> <p><b>And this</b></p>
> <p style="font-weight: bold">This as well</p>
> <p style="font-weight: bolder">Oh! and this</p>
> <p style="font-weight: 500">Cool! Right!?</p>
> <p style="font-weight: 999">Up to 999!!!</p>
> ```
> 
> It's a feature to keep your stored HTML clean. If you want to support more stylings/attributes you have to define it in your schema. You can extend all extension or create your own, but I don't want to change this in the core at the moment.

I'm pretty sure users looking to download a rich text editor don't care about clean HTML.

Actually I'm pretty sure literally no one anywhere cares about clean HTML because formatting literally any well-formed XML document is trivial.

Is this _really_ a feature? 😉

Seems more like an oversight.

Anyways I'm using TipTap for a webmail PWA. Just now realizing it strips out the styling on email replies.

Now I know my solution. :) I have to go through every single element in _the library_ and modify the `toDOM\`parseDOM` methods for each one.

That's a lot of boilerplate to workaround a "feature"

**Comment by philippkuehn** [comment]
@piboistudios Tiptap/ProseMirror is a semantic editor and that *is* a core feature. Feel free to use any other editor that allows any HTML. If you want to continue using Tiptap, it probably makes sense to use [global attributes](https://tiptap.dev/guide/custom-extensions#global-attributes) instead of modifying each extension.

**Comment by piboistudios** [comment]
> it probably makes sense to use [global attributes](https://tiptap.dev/guide/custom-extensions#global-attributes) instead of modifying each extension.

That was actually an incredibly helpful response.

@ZolooAnzo @vortechron 

See the above. This is a much more viable approach to tackling the problem.

**Comment by newboy2006hosur** [comment]
God, your words sound so complicated - WTF is semantic editor now? Do I have to learn prosemirror just to solve this one issue? This is very annoying.

**Comment by Rohan-FE-Solytics** [comment]
@newboy2006hosur did you find some work around?

**Comment by newboy2006hosur** [comment]
> @newboy2006hosur did you find some work around?

@Rohan-FE-Solytics i sorta wrote my own custom plugin, that preserves all the attributes of any given HTML tag.

**Comment by Rohan-FE-Solytics** [comment]
> > @newboy2006hosur did you find some work around?
> 
> @Rohan-FE-Solytics i sorta wrote my own custom plugin, that preserves all the attributes of any given HTML tag.

Can you share an example?

**Comment by newboy2006hosur** [comment]
> > > @newboy2006hosur did you find some work around?
> > 
> > 
> > @Rohan-FE-Solytics i sorta wrote my own custom plugin, that preserves all the attributes of any given HTML tag.
> 
> Can you share an example?

```

**Comment by Hrober0** [comment]
@newboy2006hosur Could you explain how to use your solution?
