### ISSUE TITLE
Application breaks when Markdown Shortcut is deleted using backspace

### ISSUE THREAD

**Issue by nkmnz** [scrumpy/tiptap#332]
1. open editor
2. use any markdown shortcut, e.g. # + space -> cursor size indicates H1
3. press 'delete' for the first time -> '# '
4. press 'delete' for the second time -> '#'
5. press 'delete' for the third time -> application crashes 

Expected behavior:
#-sign get's deleted

**Comment by philippkuehn** [comment]
I can't reproduce this in latest chrome/firefox/safari on [tiptap.scrumpy.io](https://tiptap.scrumpy.io/). Can you provide a codesandbox?

**Comment by nkmnz** [comment]
Using latest chrome on tiptap.scrumpy.io:

![out](https://user-images.githubusercontent.com/42554376/58693394-f88c8a00-8390-11e9-81b2-6464acb60c5e.gif)

Firefox and Safari working fine....

**Comment by philippkuehn** [comment]
Do you have the same problem on https://prosemirror.net? Which chrome version do you use? Can you please disable any chrome extension and test again?

**Comment by nkmnz** [comment]
Found the culprit. Thanks! https://chrome.google.com/webstore/detail/multi-highlight/pfgfgjlejbbpfmcfjhdmikihihddeeji
