### ISSUE TITLE
Image: Support `inputRules`

### ISSUE THREAD

**Issue by michalsnik** [scrumpy/tiptap#338]
**Is your feature request related to a problem? Please describe.**
Currently the only ways to insert images are:
- dragging image into the editor
- using command declared by `Image` to insert `<img>` tag with proper attribute

It's not possible however to use Markdown syntax to automatically insert images by using typing the following:
```
![Example alt text](image.jpg "Optional title")
```

**Describe the solution you'd like**
The proposed solution includes creating inputRule that would transform above syntax into Image node automatically.

**Describe alternatives you've considered**
This is a fairly simple feature to implement and I my current solution is creating new Image class that extends one provided by this lib, but as some of the other Nodes already have this feature and support Markdown syntax out of the box I though it might be a good addition to the core implementation too.

**Comment by philippkuehn** [comment]
It's released.
