### ISSUE TITLE
[IE 11] Todo List resize-handles

### ISSUE THREAD

**Issue by Chrissi2812** [scrumpy/tiptap#340]
**Describe the bug**
In IE 11 `todo_items` are resizable. Looks pretty funny though 😂

**Steps to Reproduce / Codesandbox Example**
![ie11_todo](https://user-images.githubusercontent.com/6141652/58941104-619e4400-877b-11e9-9ef9-c2fb3a67975f.gif)

**Expected behavior**
No resize handles should be shown

**Environment**
 - OS: Windows
 - Browser Internet Explorer
 - Version 11
 - Mobile / Desktop: Desktop

**Comment by philippkuehn** [comment]
LOL!?

**Comment by swuecho** [comment]
this could be a feature. the size indicate the importance or priority.

**Comment by Chrissi2812** [comment]
@swuecho Haha didnt thought of that 😅 But then it had to be working cross browser and not just IE 11.

**Comment by philippkuehn** [comment]
After thinking about this I decided to not support IE11 anymore.
