### ISSUE TITLE
Auto focus not working properly, focuses to starting of the content

### ISSUE THREAD

**Issue by rameezcubet** [scrumpy/tiptap#343]
Autofocus not working properly. it autofocuses the cursor to the starting of the content. 
is there a way to set the cursor position to end of the content?
please watch the gif for better understanding

Minimal code
---------------------
```
      const initialContent = `<p>Hi rameez,</p><p>second line</p>`
      this.editor = new Editor({
        content: initialContent,
        autoFocus: true,
        extensions: [
          new Blockquote(),
          new BulletList(),
          new CodeBlock(),
          new HardBreak(),
          new Heading({ levels: [1, 2] }),
          new ListItem(),
          new OrderedList(),
          new TodoItem(),
          new TodoList(),
          new Bold(),
          new Code(),
          new Italic(),
          new Link(),
          new Strike(),
          new Underline(),
          new History(),
          new Placeholder({
            emptyClass: 'is-empty',
            emptyNodeText: 'Write something…',
            showOnlyWhenEditable: true
          })
        ]
      })
```

![issue-tiptap](https://user-images.githubusercontent.com/41043647/59014248-cf20a200-8859-11e9-8db9-46af80a0aaf1.gif)

**Comment by philippkuehn** [comment]
Ah, good point! For now you can use `editor.focus('end')`. But it would make sense to allow this option for autofocus too.

**Comment by rameezcubet** [comment]
tried using 
```
this.editor.focus('end')
```
 after the plugin inited but same behaviour. ie focusing on start.

**Comment by philippkuehn** [comment]
In the lastest release you can set `autofocus: 'end'`.

**Comment by rameezcubet** [comment]
I tried updating to `"tiptap": "^1.22.2"` now my vue-nuxt-app crashes, no matter I set autofocus or not. i have added screencast below
![tiptap](https://user-images.githubusercontent.com/41043647/59327427-1cdc5500-8d07-11e9-8c73-a2a454134bbe.gif)

**Comment by philippkuehn** [comment]
@rameezcubet see #305

**Comment by rameezcubet** [comment]
Got it..
changed 
```
    "tiptap": "^1.22.2",
    "tiptap-extensions": "^1.22.2",
```
and removed `package-lock.json` file and `node_modules` folder then `npm install`

**Comment by jeremyphillipsfti** [comment]
Does `autofocus` take a 'start' option? I checked the docs but couldn't find any reference to the string arguments.

I'm running into a scenario where, when an editor loads with a partial mention at the end, the search popup is triggered automatically because of the cursor focus event.

![image](https://user-images.githubusercontent.com/34384982/69468599-a033b500-0d41-11ea-9424-977f04d02e1c.png)

**Comment by rameezcubet** [comment]
@jeremyphillipsfti this forked project of tip-tap seems to be a better version https://www.npmjs.com/package/tiptap-vuetify . it works in rapo with vuetify but you can style it for your needs without using vuetify. it also has v-model support by default.

**Comment by smylmrz** [comment]
When I delete something it focuses on the end, any idea why this might happen?

```
const editor = useEditor({
    extensions: [
        StarterKit,
        Link,
        Image
    ],
    onUpdate: ({ editor }) => {
        emit('update:modelValue', editor.getHTML())
    }
})

```
