### ISSUE TITLE
Error when putting tiptap in a component 

### ISSUE THREAD

**Issue by adronitis** [scrumpy/tiptap#344]
I tried putting the example in a component and reusing it on other view. Everything seems to be working fine itself with the editor.

But I am getting errors `[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot set property 'element' of null"
`

Any idea how I can resolve this? Thanks.

<img width="729" alt="Screenshot 2019-06-06 at 14 16 14" src="https://user-images.githubusercontent.com/1169705/59032573-e87c1b00-8866-11e9-96db-d3b39e8e2765.png">

**Comment by philippkuehn** [comment]
Please provide a codesacndbox

**Comment by philippkuehn** [comment]
closed due to inactivity

**Comment by MarvinMiles** [comment]
Just noticed that this error appears every time after hot reloading while developing. After manually reloading the page everything work smoothly until I changed something in my code again and trigger hot-reloading.

I am using nuxt

**Comment by ruslankonev** [comment]
I've got the same in nuxt component

**Comment by adronitis** [comment]
@MarvinMiles I know this is a bit late and not sure if it applys to Nuxt, but I notice that if I put tiptap under a v-show it gives such error, if is v-if then it'll be fine.

**Comment by jpparkin** [comment]
I am getting this same error when navigating away from, then back to a page that includes a tiptap editor. I am using the EditorMenuBubble as well.

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'unregisterPlugin' of null"

found in

---> <EditorMenuBubble>
       <TextAreaEditor> at src/components/ui/TextAreaEditor.vue
         <VCard>
           <EditModule> at src/components/edit/EditModule.vue
             <HelpsheetShow> at src/views/HelpsheetShow.vue
               <VContent>
                 <VApp>
                   <ApplicationLayout> at src/layouts/MainLayout.vue
                     <VApp>
                       <App> at src/App.vue
                         <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
callHook @ vue.runtime.esm.js?2b0e:4213
Vue.$destroy @ vue.runtime.esm.js?2b0e:3972
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
removeVnodes @ vue.runtime.esm.js?2b0e:6124
updateChildren @ vue.runtime.esm.js?2b0e:6229
patchVnode @ vue.runtime.esm.js?2b0e:6313
updateChildren @ vue.runtime.esm.js?2b0e:6187
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
eval @ vue-router.esm.js?8c4f:2748
eval @ vue-router.esm.js?8c4f:2747
updateRoute @ vue-router.esm.js?8c4f:2174
eval @ vue-router.esm.js?8c4f:2037
eval @ vue-router.esm.js?8c4f:2159
step @ vue-router.esm.js?8c4f:1843
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
eval @ vue-router.esm.js?8c4f:2154
step @ vue-router.esm.js?8c4f:1843
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ vue-router.esm.js?8c4f:1921
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ router.js?41cb:95
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
push @ vue-router.esm.js?8c4f:2365
eval @ vue-router.esm.js?8c4f:2779
push @ vue-router.esm.js?8c4f:2778
showHelpsheet @ HelpsheetCard.vue?a57e:82
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
Vue.<computed> @ backend.js:1793
click @ index.js?1c87:65
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
Show 80 more frames
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'unregisterPlugin' of null
    at VueComponent.beforeDestroy (tiptap.esm.js?cd42:1941)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js?2b0e:3972)
    at destroy (vue.runtime.esm.js?2b0e:3159)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6108)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6113)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6113)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6461)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js?2b0e:3995)
logError @ vue.runtime.esm.js?2b0e:1888
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
callHook @ vue.runtime.esm.js?2b0e:4213
Vue.$destroy @ vue.runtime.esm.js?2b0e:3972
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
removeVnodes @ vue.runtime.esm.js?2b0e:6124
updateChildren @ vue.runtime.esm.js?2b0e:6229
patchVnode @ vue.runtime.esm.js?2b0e:6313
updateChildren @ vue.runtime.esm.js?2b0e:6187
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
eval @ vue-router.esm.js?8c4f:2748
eval @ vue-router.esm.js?8c4f:2747
updateRoute @ vue-router.esm.js?8c4f:2174
eval @ vue-router.esm.js?8c4f:2037
eval @ vue-router.esm.js?8c4f:2159
step @ vue-router.esm.js?8c4f:1843
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
eval @ vue-router.esm.js?8c4f:2154
step @ vue-router.esm.js?8c4f:1843
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ vue-router.esm.js?8c4f:1921
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ router.js?41cb:95
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
push @ vue-router.esm.js?8c4f:2365
eval @ vue-router.esm.js?8c4f:2779
push @ vue-router.esm.js?8c4f:2778
showHelpsheet @ HelpsheetCard.vue?a57e:82
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
Vue.<computed> @ backend.js:1793
click @ index.js?1c87:65
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
Show 79 more frames
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot set property 'element' of null"

found in

---> <EditorContent>
       <TextAreaEditor> at src/components/ui/TextAreaEditor.vue
         <VCard>
           <EditModule> at src/components/edit/EditModule.vue
             <HelpsheetShow> at src/views/HelpsheetShow.vue
               <VContent>
                 <VApp>
                   <ApplicationLayout> at src/layouts/MainLayout.vue
                     <VApp>
                       <App> at src/App.vue
                         <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
callHook @ vue.runtime.esm.js?2b0e:4213
Vue.$destroy @ vue.runtime.esm.js?2b0e:3972
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6113
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
patch @ vue.runtime.esm.js?2b0e:6461
Vue.$destroy @ vue.runtime.esm.js?2b0e:3995
destroy @ vue.runtime.esm.js?2b0e:3159
invokeDestroyHook @ vue.runtime.esm.js?2b0e:6108
removeVnodes @ vue.runtime.esm.js?2b0e:6124
updateChildren @ vue.runtime.esm.js?2b0e:6229
patchVnode @ vue.runtime.esm.js?2b0e:6313
updateChildren @ vue.runtime.esm.js?2b0e:6187
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
eval @ vue-router.esm.js?8c4f:2748
eval @ vue-router.esm.js?8c4f:2747
updateRoute @ vue-router.esm.js?8c4f:2174
eval @ vue-router.esm.js?8c4f:2037
eval @ vue-router.esm.js?8c4f:2159
step @ vue-router.esm.js?8c4f:1843
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
eval @ vue-router.esm.js?8c4f:2154
step @ vue-router.esm.js?8c4f:1843
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ vue-router.esm.js?8c4f:1921
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ router.js?41cb:95
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
push @ vue-router.esm.js?8c4f:2365
eval @ vue-router.esm.js?8c4f:2779
push @ vue-router.esm.js?8c4f:2778
showHelpsheet @ HelpsheetCard.vue?a57e:82
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3882
Vue.<computed> @ backend.js:1793
click @ index.js?1c87:65
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
Show 80 more frames
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot set property 'element' of null
    at VueComponent.beforeDestroy (tiptap.esm.js?cd42:1575)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4213)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js?2b0e:3972)
    at destroy (vue.runtime.esm.js?2b0e:3159)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6108)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6113)
    at invokeDestroyHook (vue.runtime.esm.js?2b0e:6113)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6461)
    at VueComponent.Vue.$destroy (vue.runtime.esm.js?2b0e:3995)

**Comment by jpparkin** [comment]
This was a bug in my code. The way I was handling different layouts in the application was calling the components beforeDestroy and destroyed methods on loading a new view.

**Comment by FarhanKhalid** [comment]
For me this happened because I didn't have the tiptap editor within a <client-only> tag. It took me a long time to figure it out but that was all it was!

**Comment by JokerMartini** [comment]
This is happening to me, a buggy plugin

**Comment by hotdevcoder** [comment]
I also got same issue
