### ISSUE TITLE
Floating Menu doesn't receive `isActive` on initial focus

### ISSUE THREAD

**Issue by jackmcdade** [scrumpy/tiptap#347]
**Describe the bug**
If your editor is empty (e.g. starting a new document), focusing the editor will not open the floating menu. You need to enter a character and backspace to trigger `isActive` and pop it open.

**Steps to Reproduce / Codesandbox Example**
1. Go to <https://tiptap.scrumpy.io/floating-menu>
2. Delete the content
3. Blur out of the field
4. Focus the field - no floating menu (there should be)
5. Enter a character and backspace
6. Floating menu shows.

 Fork this or create a new Codesandbox replicating your error
 https://codesandbox.io/s/qxv5m9y6oq?fontsize=14

**Expected behavior**

**Screenshots**

**Environment**
 - OS: MacOS latest
 - Browser Chrome latest
 - Mobile / Desktop: Desktop

**Additional context**

**Comment by philippkuehn** [comment]
Should be fixed in tiptap@1.22.1

**Comment by jackmcdade** [comment]
❤️
