### ISSUE TITLE
Include small image in "Suggestion" and respond to click event?

### ISSUE THREAD

**Issue by softwareguy74** [scrumpy/tiptap#350]
In building on the "Suggestions" feature (as shown here: [https://tiptap.scrumpy.io/suggestions](url)), I have a need to allow displaying a small image in the suggestion and respond to click event. This may be useful for example, to allow one click delete of the suggestion.

Is this possible?  If so, example code would be greatly appreciated.

**Comment by philippkuehn** [comment]
Yes this is possible by creating your own suggestions extension. create a copy of the official mentions node and you're good to go.
