### ISSUE TITLE
The "Suggestions" feature is adding a space after hitting enter

### ISSUE THREAD

**Issue by softwareguy74** [scrumpy/tiptap#351]
I'm not sure if this is just a bug on the sample implementation as seen here: [https://tiptap.scrumpy.io/suggestions](url) or if it's a bug in the code.

When typing @ to bring up the list of available mentions, and hitting return to accept it, it adds an additional space after it.  So for example, if I started off with:  "Some text", and I enter a suggestion as "Some @ text", it ends up with: "Some @person`<space><space>`text".  Notice the extra space between "person" and "text".

Can this be fixed?

**Comment by philippkuehn** [comment]
This is intended behavior. Slack also add a white space after confirming a mention. I'm not sure of make this an option in the mentions node. But of course you can create your own extension by copying the mentions extension.

https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Mention.js#L62
