### ISSUE TITLE
Table example: Not able to click after table

### ISSUE THREAD

**Issue by softwareguy74** [scrumpy/tiptap#352]
In the Tables example, when adding a Table, you are unable to click in the editor after the table.  This makes it impossible to add additional text after a table.  It would be helpful if when adding a Table, a carriage return is added immediate after the table so you can place your cursor there and start typing.

**Comment by Chrissi2812** [comment]
tiptap uses `prosemirror-gapcursor` but currently is missing it's styling. 
You can however add a padding-bottom to the `.ProseMirror` Element so you can click below the table, this will trigger the gapcursor. 

With the styles from [`prosemirror-gapcursor`](https://github.com/ProseMirror/prosemirror-gapcursor/blob/master/style/gapcursor.css)
![7cfab620-4cda-423f-bec6-85b7c68c1a8a](https://user-images.githubusercontent.com/6141652/59342622-6a0df600-8d0a-11e9-810f-576b967ccfa2.gif)

**Comment by philippkuehn** [comment]
@Chrissi2812 ahhh! Yeah... this is on my list for so long I completely missed it. At the moment I'm not sure what's the best way to include some styling in a renderless editor (maybe what tippy.js does for example?). The only thing I do is to set manually `white-space: pre-wrap;` to the editor but there are some other basic stylings in `prosemirror-view` too.

**Comment by Chrissi2812** [comment]
@philippkuehn The approach by tippy.js seems not bad. 

As an alternative:
I wonder if an option on the editor instance would also work? So we have still one bundle and the css only get's loaded when enabled. Would it be treeshakable (does it even matter considering how small the css part would be)? 

The styles from `prosemirror-tables` should be included as well (resize handles)

**Comment by philippkuehn** [comment]
basic styles of `prosemirror-view` and `prosemirror-gapcursor` will be injected to the head now.

**Comment by halafi** [comment]
@philippkuehn I think this should be reopened, at least in the examples it's not working at the moment https://tiptap.dev/examples/tables

**Comment by Chenuc1107** [comment]
> @philippkuehn我认为这应该重新打开，至少在示例中它目前不工作，你只能用键盘到达表格前后的光标，而不是鼠标https://tiptap.dev/examples/tables
> 
> 看起来这可以通过[https://tiptap.dev/api/extensions/gapcursor/来完成](https://tiptap.dev/api/extensions/gapcursor/)

i try https://tiptap.dev/api/extensions/gapcursor/ with table,but invalid.

**Comment by andrewlu0** [comment]
Also running into this issue, and gapcursor doesn't work for me. Is there a known workaround?

**Comment by philiprenich** [comment]
Agree with @halafi - this is only working with keyboard navigation, not a pointer - mouse or finger on touch device. The latter is an issue as documents with tables at the end are no longer able to be continued.

@philippkuehn Would you prefer a new issue to be created to track this?

**Comment by Encoded2** [comment]
This is still an issue, or has reoccurred.  Can this be reopened or duplicated?

**Comment by gotoAndBliss** [comment]
Look into tiptap extension - GapCursor FTW!
