### ISSUE TITLE
Regression making floating-menu unclickable

### ISSUE THREAD

**Issue by jackmcdade** [scrumpy/tiptap#353]
**Describe the bug**
After the b381e500 commit and 1.22.1 release, I can no longer interact with the `editor-floating-menu` component. Trying to click it results in `isActive` being flipped to `false` and hiding it.

Any ideas on that?

**Comment by jackmcdade** [comment]
Here's a quick video of the issue in action.

![2019-06-10 16 52 22](https://user-images.githubusercontent.com/44739/59226081-3adb7580-8ba0-11e9-868e-6784cae44b4d.gif)

**Comment by jasonvarga** [comment]
When we click that button in Jack's gif, this is what's getting fired:

https://github.com/scrumpy/tiptap/commit/b381e50043baee0f2594d212e30ab0750bf7df80#diff-1fcbad22612f4e7fc6b4b4d9dae86289R21

**Comment by philippkuehn** [comment]
@jasonvarga hmm strange. but that blur event was already there before 🤔
did you try to call `event.stopPropagation()` on your button click?

**Comment by jackmcdade** [comment]
Yes, no luck.

**Comment by jackmcdade** [comment]
For what it's worth, I was seeing this behavior in Firefox before this update, and now I'm seeing it all browsers.

**Comment by jasonvarga** [comment]
It seems to blur before any click events happen on any buttons inside the menu.

**Comment by philippkuehn** [comment]
Ah, the code on the demo page is only working because of a fade transition. So quick fix for you: add a transition.

But I have to find a solution for this.

**Comment by jackmcdade** [comment]
You folks are *awesome*! ❤️
