### ISSUE TITLE
Underline mark throws "Content hole not allowed error"

### ISSUE THREAD

**Issue by jeremyphillipsfti** [scrumpy/tiptap#355]
When the editor contains underlined text, a "Content hole not allowed in mark or leaf node spec" error is thrown when the editor.getHTML() method is called.

**Steps to reproduce the behavior:**
1. Underline some text
2. Call the getHTML() method on the editor.

**Expected behavior**

**Environment**
Chrome 74 IE 11
tiptap 1.20.1
tiptap-extensions 1.20.1

**Comment by philippkuehn** [comment]
I can't reproduce this on the [example page](https://tiptap.scrumpy.io/export). Please provide a codesandbox.

**Comment by jeremyphillipsfti** [comment]
I looks like this may be an issue with a couple of my dependencies. When I install / upgrade tiptap I get two warnings.

1. warning "tiptap-extensions > prosemirror-utils@0.8.3" has incorrect peer dependency "prosemirror-tables@^0.7.9".
2. warning "tiptap-extensions > tiptap-commands > prosemirror-utils@0.9.2" has incorrect peer dependency "prosemirror-tables@^0.7.9".

I installed the correct prosemirror packages individually and the warnings went away, but the Underline marks started throwing the error. When I only have tiptap in my package.json it works fine.

I will close this and continue to look into it.
