### ISSUE TITLE
 $scopedSlots.default is not function

### ISSUE THREAD

**Issue by xkubow** [scrumpy/tiptap#359]
I'm using vue-cli and trying your [example](https://tiptap.scrumpy.io/docs/api/extensions.html#bold). I got error  $scopedSlots.default is not function at tiptap.ems.js EditorMenuBar component.

What should I do to get it working correctly.

**Comment by philippkuehn** [comment]
Ah, I think you'll need vue 2.6. which version of vue do you use?

**Comment by xkubow** [comment]
^2.5.17
Thanks I will try. Didn't know that I could have lower than newest vue when I did npm install :)

**Comment by xkubow** [comment]
Worked. thanks

**Comment by philippkuehn** [comment]
Yeah sorry. I should mention that in the docs.
