### ISSUE TITLE
Infinite loop when loading the view of a node

### ISSUE THREAD

**Issue by dSolid** [scrumpy/tiptap#364]
**Describe the bug**
I get an infinite loop caused by seemingly the view portion of a node. Not too sure what changed and in which version the issue appeared in. I know it does the bug in all of 1.22, and it doesn't in the old version included in the default codesandbox template.

**Steps to Reproduce / Codesandbox Example**
1. go to https://codesandbox.io/s/vue-issue-template-7be48
2. select any text
3. click footnote in the menu
4. see infinite loop

**Expected behavior**
If you go to the default codesandbox setup on tiptap 1.16.2, it works as expected, it will create a footnote similar to https://prosemirror.net/examples/footnote/ since its a ported implementation from prosemirror to tiptap

**Environment**
 - OS: Win10
 - Browser Chrome
 - Version 76.0.3809.21 (Official Build) dev (64-bit)
 - Mobile / Desktop: Desktop

**Additional context**
If I comment out the view portion, doesn't do an infinite loop so the cause is definitely the view.

**Comment by philippkuehn** [comment]
Try to avoid manipulating DOM elements (adding classes) with `ref="content"` because ProseMirror will detect these changes and trigger a re-rendering (infinte loop).

**Comment by dSolid** [comment]
indeed, didnt know that changed. Thanks!

**Comment by dSolid** [comment]
Actually I might have closed this issue too fast but now I cant edit the content itself of the footnote itself, at least it doesn't do an infinite loop anymore.

**Comment by philippkuehn** [comment]
No, you'll need this `ref="content"`. Try to add that `:class="{ 'is-empty': captionEmpty }"` to a wrapping element instead of the element itself.

**Comment by SivaRSR** [comment]
Was this resolved?
