### ISSUE TITLE
 How do I get the cursor position?

### ISSUE THREAD

**Issue by Dangary-pleiades** [scrumpy/tiptap#367]
Sorry for the poor English.
Thanks for using tiptap.

Ask about the position of the cursor on the tip tap editor.
(I'm sorry if it was the question of "prosemirror")

- the purpose
I want to track the cursor position on the editor in real time.
I want to use the handleKeyDown event to get the cursor position when I enter some characters.

- Question
The current cursor position was found by referring to "editor.view.state.selection. $ Anchor.pos".
However, if you press the arrow keys, the position information will appear to point to the previous position.(The same is true for Backspace.)
In this case, how can I get the correct cursor position information?

I am very happy if you can give me your advice.
Thank you.

**Comment by kshitizshankar** [comment]
Maybe this would help - https://github.com/scrumpy/tiptap/issues/346

**Comment by Dangary-pleiades** [comment]
Thank you for your reply!

I saw the contents of that thread.
The ultimate goal was the same.

However, I did not know how to get the correct cursor position ...
What is the tip for getting the cursor position of the user who is operating the editor?

(Do you want to ask questions in your thread?)

**Comment by philippkuehn** [comment]
@Dangary-pleiades This should work:

```js
new Editor({
  onTransaction: ({ state }) => {
    console.log(state.selection.anchor)
  },
})
```

**Comment by Dangary-pleiades** [comment]
Thank you!
It worked as expected.

Thank you both!

**Comment by KiresMA** [comment]
@philippkuehn I need to get the last non-whitespace character before the cursor.
I noticed that `state.selection.anchor` adds 2 with each new line.
That makes a problem when I try to correlate anchor position with state.doc.textContent.
In short, I'm not able to get a match between anchor index and the textContent when there are multiple lines.

For example I have this content in the tiptap editor:
```
1

{3
```
Cursor stayed in-between { and 3. In this situation anchor position is `7`, but textContent is just `1{3`.
Which means that when I try to get a substring  from textContent based on this anchor I'm not getting a curly brace.
To get the last character I'm using `textContent.substring(0, anchor).trim().slice(-1)`.

Here is the same scenario step by step:
1. Focus tiptap editor (anchor = 1, textContent = "")
2. type `1` (anchor = 2, textContent = "1")
3. hit `Enter` (anchor = 4, textContent = "1")
4. hit `Enter` (anchor = 6, textContent = "1")
5. type `3` (anchor = 7, textContent = "13")
6. `move cursor one position to the left`, type `{` (anchor = 7, textContent = "1{3")

I tried to use `textBetween` as described here and separator '\r\n'
https://discuss.prosemirror.net/t/node-textcontent-returns-text-without-whitespace-between-nodes/3109
However it doesn't add block separator for empty lines (like in the example above), so again there is a mismatch with the anchor value.

Could you explain to me why each new line adds 2 to the anchor and how can I get a cursor position relative to the plaint text (textContent)?

Thanks

**Comment by softmarshmallow** [comment]
How about the clientX, Y pos?

**Comment by JoeRoddy** [comment]
`editor.state.selection.$anchor.pos` got it working for me

**Comment by mepc36** [comment]
I'm using a `useEditor` hook to create the editor, and none of the posted solutions or object pathways quite worked for me. Instead I got the line by accessing it like this:

```
  const editor = useEditor({
    onTransaction: ({ editor }) => {
      const cursorLine = editor.view.state.selection.$anchor.path[1]
      console.log('cursorLine:', cursorLine)
    },
  })
```

**Comment by reubenv** [comment]
> Could you explain to me why each new line adds 2 to the anchor and how can I get a cursor position relative to the plaint text (textContent)?
> 
> Thanks

Did you ever get a good response for this?? I am trying to work through something similar and not figure out at all how to properly use the position to get the accurate location in what is being returned with getText().

**Comment by vknowles-rv** [comment]
Just incase it's helpful, I ended up tracking navigation position within a storage mechanism. Not sure if this is provided by tiptap or prosemirror, but the example extension is tiptap

```typescript
export const ExampleExtension = Mark.create<ExtensionOptions, ExtensionStorage>({
    name: "block-system",

    onCreate() {
        this.editor.storage.navigationPos = this.editor.view.coordsAtPos(1).left;
    },

    onSelectionUpdate() {
        this.storage.navigationPos = this.editor.view.coordsAtPos(this.editor.view.state.selection.$anchor.pos).left;
    },

    addStorage() {
        return {
            navigationPos: undefined,
        };
    },
    // Other code leveraging this.storage.navigationPos
});
```

**Comment by reubenv** [comment]
That's actually pretty nifty to grab the actual screen position like that. Thanks for sharing! 

What I'm trying to do is grab the cursor position (basically the "character location" for lack of a better explanation) within the editor. So, for example, if there are 25 characters in the editor, and I set the cursor at the beginning of the editor, I'm expecting a position of 1 or 26 if I'm at the very end, 13(ish) if I'm in the middle. 

In practice, this works great as long as you have a string with no line breaks. Once you start introducing line breaks, things get a little funky. If you press the Enter key, it inserts a \n in to the content returned by getText(), and if you check the position, the position jumps by TWO. However if you do a Shift+Enter, it also inserts \n in to the content, but the position is only incremented by one. I have a work around in place now, but it is far from ideal cause it doesn't resolve EVERY issue.

**Comment by henningsieh** [comment]
> grab the cursor position

Hey. Did you find a solution for receiving the current cursor position from within the TipTap Editor's TextArea?

**Comment by reubenv** [comment]
> > grab the cursor position
> 
> Hey. Did you find a solution for receiving the current cursor position from within the TipTap Editor's TextArea?

Unfortunately, no. I mean, not in the context of when nodes get added to the editor, that continued to throw off our count, but our requirements changes so we were able to move ahead without needing the exact cursor position.

**Comment by rocher71** [comment]
I don't know if anybody needs this, but I am using `useEditor` hook, and for me this line worked to get the cursor position!
```javascript
const anchorPosition = editor.state.selection.$anchor.pos;
```

and to check if the cursor is at the end, this worked for me 🙂
```javascript
useEffect(() => {
  const anchorPosition = editor.state.selection.$anchor.pos;
  if (anchorPosition === editor.state.doc.content.size - 1) { 
// Not sure why, but the anchor position equals to minus 1 of the doc size!!
    setIsAnchorAtEnd(false);
    return;
  }
  setIsAnchorAtEnd(true);
}, [editor?.state]);
```

**Comment by raumildhandhukia** [comment]
I am looking for cursor's X position and Y position relative to text area. I want to show floating toolbar on cursor. How can I get cursor's X, Y position using TipTap's API ?

**Comment by nperez0111** [comment]
@raumildhandhukia for x, y position you can use `posToDOMRect` which if given `posToDOMRect(editor.view, editor.state.selection.from, editor.state.selection.to)` would give you the bounds of the cursor within the document

https://github.com/ueberdosis/tiptap/blob/e97630c63927b3c05e75882975ea12c4d364acd3/packages/core/src/helpers/posToDOMRect.ts#L5
