### ISSUE TITLE
Collaboration - Conceptual/Demo Code

### ISSUE THREAD

**Issue by kshitizshankar** [scrumpy/tiptap#368]
Hey - I've been playing around with the Collaboration code from the demo and I've been trying to port it to a FeathersJS backend.

From what I understand - the flow for collaboration goes this way - 
1. Vue Component gets mounted
2. Component requests initial document & version from the server
3. Editor is initialized with this data 

There are 2 events that need to be handled - 
1. Outgoing Updates - Any changes made by the local editor
2. Incoming Updates - Server pushing changes by other editors

Outgoing Updates event sends the Steps to the server, the server applies the steps, creates a new document, saves it and sends the steps to other active editors.

Incoming Updates routes all the steps to the collaboration plugin.

**Question**
1. What's wrong here? I keep getting "Version Mismatch" with only 1 editor (no parallel editing) 
If the understanding above is correct - Version Mismatch shouldn't be happening here with single user scenario right?

Seems like I missed something...

**Comment by kshitizshankar** [comment]
Ahh ok - Think I found the problem - 
```
    // send update to everyone (me and others)
    io.sockets.emit('update', {
      version: newVersion,
      steps: getSteps(version),
    })
```
Steps need to be sent back to ALL the editors for them to update their versions

**Comment by kshitizshankar** [comment]
Another related question - On the server, I need the document schema to be able to transform and apply the steps. How do I export my schema from the frontend to be able to use it in the backend?

I tried to hack around it and constructing it from the frontend - Not sure if there is a way to get this more easily as this feels too hackish..
```
exportSchema () {
        let specs = this.editor.view.state.schema.spec
        let exportedSchema = { nodes: {}, marks: {} }
        if (specs.nodes && specs.nodes.content && specs.nodes.content instanceof Array) {
          for (let i = 0; i < specs.nodes.content.length; i++) {
            if (typeof specs.nodes.content[i] === 'string') {
              exportedSchema.nodes[specs.nodes.content[i]] = {}
              if (typeof specs.nodes.content[i + 1] === 'object') {
                exportedSchema.nodes[specs.nodes.content[i]] = specs.nodes.content[i + 1]
                i = i + 1
              }
            }
          }
        }

        if (specs.marks && specs.marks.content && specs.marks.content instanceof Array) {
          for (let i = 0; i < specs.marks.content.length; i++) {
            if (typeof specs.marks.content[i] === 'string') {
              exportedSchema.marks[specs.marks.content[i]] = {}
              if (typeof specs.marks.content[i + 1] === 'object') {
                exportedSchema.marks[specs.marks.content[i]] = specs.marks.content[i + 1]
                i = i + 1
              }
            }
          }
        }

        console.log(JSON.stringify(exportedSchema))
```

**Comment by kshitizshankar** [comment]
I am getting this error sometimes with the collaboration in place. I haven't been able to trace it exactly when/where it happens..
```
Uncaught TypeError: Cannot read property 'matchesNode' of null
    at EditorView.updateStateInner (index.js?703f:4398)
    at EditorView.updateState (index.js?703f:4375)
    at Editor.dispatchTransaction (tiptap.esm.js?cd42:1223)
    at EditorView.dispatch (index.js?703f:4622)
    at Proxy.update (extensions.esm.js?f23d:2203)
    at VueComponent.onRemoteUpdate (index.vue?6ced:260)
    at Socket.eval (index.vue?6ced:132)
    at Socket.Emitter.emit (index.js?db1a:133)
    at Socket.onevent (socket.js?2851:278)
    at Socket.onpacket (socket.js?2851:236)
```

Any suggestions on where to look?

**Comment by philippkuehn** [comment]
Hey!

> Steps need to be sent back to ALL the editors for them to update their versions

Yeah, all steps also have to go back to the current client to **confirm** these changes, so the client don't have to send these steps again.

> Another related question - On the server, I need the document schema to be able to transform and apply the steps. How do I export my schema from the frontend to be able to use it in the backend?

You can get the schema for your backend with `editor.getSchemaJSON()`. 

> I am getting this error sometimes with the collaboration in place. I haven't been able to trace it exactly when/where it happens..

Maybe this could be a timing problem? Maybe you'll get some updates after the editor is already destroyed?

**Comment by kshitizshankar** [comment]
Hey @philippkuehn - Thanks! I got the collaboration working with FeathersJS now (haven't fully tested it yet - but I can add some context/code once it's stable for anyone else looking to get something similar done

> 
> You can get the schema for your backend with `editor.getSchemaJSON()`.
>
Oh perfect! Didn't know about that - Couldn't find it anywhere in the prosemirror documentation either - So Thanks!!
> 
> Maybe this could be a timing problem? Maybe you'll get some updates after the editor is already destroyed?
>
Yeah - Think I have that problem because of the live dev server ("vue-cli-service serve") - I don't really get why it happens as the editor should get reinitialized - but I've left it as is for now and might revisit it later if it becomes an issue.

Cheers!

**Comment by philippkuehn** [comment]
Any updates on this? Please re-open if there are still problems.

**Comment by markneub** [comment]
@kshitizshankar I would love to see your code for the FeathersJS integration if you can share
