### ISSUE TITLE
How to get selected text?

### ISSUE THREAD

**Issue by ageeye-cn** [scrumpy/tiptap#369]
Can you provide a method?

**Comment by philippkuehn** [comment]
This is already possible with [textBetween](https://prosemirror.net/docs/ref/#model.Node.textBetween):

```js
const { selection, state } = this.editor
const { from, to } = selection
const text = state.doc.textBetween(from, to, ' ')
```

**Comment by albanafmeti** [comment]
@philippkuehn 
Is there possible to get the selected part but the HTML version? So, not only text.

**Comment by hanspagel** [comment]
That gets only the text, not a structured kind of content (e. g. headlines, paragraphs), so there’s nothing that can be transformed to HTML.

If your editor looks like that:

```md

# Headline

Text
```

And you select `#Head` only. What would you expect?

This: 
```<h1>Head```

Or this:
```<h1>Head</h1>```

Both is wrong for different reasons. The first wouldn’t be the HTML you’d need to work with. And the second wouldn’t be the structure from the document.

**Comment by goamn** [comment]
It would be really good to have this in the documentation somewhere. Took 3 searches and checking all search result pages to finally find the answer here

**Comment by HarmNullix** [comment]
@goamn , you could put in an effort and add it yourself somewhere you think is helpful for others in the docs..

**Comment by Somethingideally** [comment]
Here is extension for this, just create with any name and include in extensions()

```
import { Extension } from '@tiptap/core'

export default Extension.create({
    addCommands: () => {
        return {
            getSelectedText: () => ({ editor }) => {
                const { from, to, empty } = editor.state.selection

                if (empty) {
                    return null
                }

                return editor.state.doc.textBetween(from, to, ' ')
            },
        }
    },
})


```

**Comment by philippkuehn** [comment]
@Somethingideally Commands should not be used for custom methods. Use [storage](https://tiptap.dev/guide/custom-extensions#storage) instead.

**Comment by RicoTrevisan** [comment]
> @goamn , you could put in an effort and add it yourself somewhere you think is helpful for others in the docs..
> 
> https://tiptap.dev/api/commands#write-your-own-commands

@matheusleo 's solution has been extremely helpful to me. I would love to give back and help others (I'm already a sponsor). I'm a zero at open source projects and Github.

How can I help with the documentation? Do I just edit the https://github.com/ueberdosis/tiptap/blob/main/docs/api/commands.md file? Is there a style guide to follow?

**Comment by joaopcm** [comment]
Here's a function to get the HTML from a selected content using TipTap 2:
```ts
import { DOMSerializer } from 'prosemirror-model'

export function getHTMLContentBetween(
  editor: Editor,
  from: number,
  to: number
) {
  const { state } = editor
  const nodesArray: string[] = []

  state.doc.nodesBetween(from, to, (node, pos, parent) => {
    if (parent === state.doc) {
      const serializer = DOMSerializer.fromSchema(editor.schema)
      const dom = serializer.serializeNode(node)
      const tempDiv = document.createElement('div')
      tempDiv.appendChild(dom)
      nodesArray.push(tempDiv.innerHTML)
    }
  })

  return nodesArray.join('')
}
```

**Comment by tiavina-mika** [comment]
> Here's a function to get the HTML from a selected content using TipTap 2:
> 
> ```ts
> import { DOMSerializer } from 'prosemirror-model'
> 
> export function getHTMLContentBetween(
>   editor: Editor,
>   from: number,
>   to: number
> ) {
>   const { state } = editor
>   const nodesArray: string[] = []
> 
>   state.doc.nodesBetween(from, to, (node, pos, parent) => {
>     if (parent === state.doc) {
>       const serializer = DOMSerializer.fromSchema(editor.schema)
>       const dom = serializer.serializeNode(node)
>       const tempDiv = document.createElement('div')
>       tempDiv.appendChild(dom)
>       nodesArray.push(tempDiv.innerHTML)
>     }
>   })
> 
>   return nodesArray.join('')
> }
> ```

@joaopcm , where it will be used?

**Comment by tiavina-mika** [comment]
Here is my solution, it returns a node / element or a text

```javascript
import { Editor } from "@tiptap/react";
import { DOMSerializer } from 'prosemirror-model'

export const getSelectedText = (editor: Editor, returnType = "text"): string | null => {
  if (!editor) return null;
  const { state } = editor;
  const { from, to, empty } = state.selection;

    if (empty) return null;

    // -------- html element --------- //
    if (returnType === "node") {
      const nodesArray: string[] = [];

      state.doc.nodesBetween(from, to, (node, pos, parent) => {
        if (parent === state.doc) {
          const serializer = DOMSerializer.fromSchema(editor.schema);
          const dom = serializer.serializeNode(node);
          const tempDiv = document.createElement('div');
          tempDiv.appendChild(dom);
          nodesArray.push(tempDiv.innerHTML);
        }
      })
  
      return nodesArray.join('');
    }

    // -------- text --------- //
    return editor.state.doc.textBetween(from, to, ' ')
}
```

**Comment by KevinTss** [comment]
Solution of @joaopcm works quite well, but where limitation are is when you're selecting a part of a content.

Ex:
```
<p>some text</p>
<p>some other ones</p>
```
Select from `text` to `other`
The function will return the whole text.
Same for list and nested lists.
Does anyone have tried a solution for that?

I'm happy to work on that and get help to fix this

**Comment by guirlviana** [comment]
@joaopcm @KevinTss your solutions helped me!
