### ISSUE TITLE
EditorMenuBar not rendered

### ISSUE THREAD

**Issue by shepelevstas** [scrumpy/tiptap#370]
**Describe the bug**
the **EditorMenuBar** component is not rendered at all

**Steps to Reproduce / Codesandbox Example**
 https://codesandbox.io/s/vue-tiptap-no-editormenubar-din74

**Expected behavior**
A MenuBar above the EditorContent

**Environment**
 - Windows 8.1
 - Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)
 - Desktop

**Additional context**
in dev tools of chrome, in Elements tab there is just  instead.

**Comment by philippkuehn** [comment]
There are some errors in the console. `[Vue warn]: Multiple root nodes returned from render function. Render function should return a single root node.`. You have to wrap your buttons in a div or something.

**Comment by shepelevstas** [comment]
Thank you! That was fast! =D And that in deed was the problem. After enclosing all buttons in a div MenuBar appeared! =D
