### ISSUE TITLE
Title demo placeholders

### ISSUE THREAD

**Issue by holtwick** [scrumpy/tiptap#381]
**Describe the bug**
The title demo is awesome! A minor issue is the placeholder handling

**Steps to Reproduce**
1. Enter 2 paragraphs by pressing RETURN twice
2. Write some text

**Expected behavior**
At least the second placeholder should disappear.

**Screenshots**
<img width="345" alt="image" src="https://user-images.githubusercontent.com/49557/60892970-4fbf2d80-a260-11e9-8d32-ea2da0d70ee5.png">

**Environment**
 - macOS Firefox

**Comment by philippkuehn** [comment]
Yeah, with a small change to the CSS styling this is already possible.

```diff
- .editor *.is-empty:nth-child(2)::before
+ .editor *.is-empty:nth-child(2):last-child::before
```
