### ISSUE TITLE
links params not detected

### ISSUE THREAD

**Issue by NikitaIT** [scrumpy/tiptap#384]
insert link
`https://localhost:8081/?utm_source=1231&utm_medium=123&utm_campaign=1233&4f=3234&utm_content=v_{ad_id}`
to https://tiptap.scrumpy.io/
![image](https://user-images.githubusercontent.com/16810067/61083974-ae89d000-a435-11e9-97b8-b696c2b9353b.png)
And:
This is broken https://github.com/scrumpy/tiptap/issues/47 Links clickable.

**Comment by reza-akbari** [comment]
`localhost:8081` is not a valid domain name but you can extend the `Link` mark and change the regex used in `pasteRules` also adding `Link` mark before `Italic` and `Bold` marks fixes the underline issue

**Comment by NikitaIT** [comment]
@reza-akbari I'm talking about a problem with a text like `my_name_nikita`
just compare in https://prosemirror.net/ and https://tiptap.scrumpy.io/
