### ISSUE TITLE
Editor method `focus()` doesn't work

### ISSUE THREAD

**Issue by KevinNTH** [scrumpy/tiptap#389]
**Describe the bug**
Editor method `focus()` doesn't work.
![image](https://user-images.githubusercontent.com/1632391/61307287-587aab00-a7ee-11e9-89f0-80397f73d72e.png)

This does not work on `tiptap 1.23.2` and used to work. This is likely a regression.

**Steps to Reproduce / Codesandbox Example**
1. init the editor via `const editor = new Editor()`
2. call to `editor.focus()`
3. does not focus.

https://codesandbox.io/s/editor-focus-does-not-work-g48i0?fontsize=14

**Expected behavior**
Focus the editor :P

**Screenshots**
![image](https://user-images.githubusercontent.com/1632391/61307760-346b9980-a7ef-11e9-872c-820facfeb3df.png)

**Environment**
 - Mobile / Desktop: [eg. Desktop]

**Additional context**

**Comment by screets** [comment]
The same here. Focus doesn't work properly.

**Comment by vitaliy-grusha** [comment]
I found a solution - `editor.view.dom.focus()`

**Comment by screets** [comment]
Hey Scrumpy/tiptap,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *Screets API key* which is
required for support questions. If you already included in your message,
you don't need to do anything else.
{#HS:907031428-4609#}

**Comment by screets** [comment]
You're the king!

However, there is one more think i should add. That one works better when you use it for **click** events:

```
this.$nextTick( () => {
   this.editor.view.dom.focus()
})
```

**Comment by screets** [comment]
Hey Scrumpy/tiptap,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *Screets API key* which is
required for support questions. If you already included in your message,
you don't need to do anything else.
{#HS:907925000-4624#}

**Comment by philippkuehn** [comment]
@screets please stop that.

**Comment by screets** [comment]
Hey Scrumpy/tiptap,

We got your help request!
One of our agents will respond to you, asap (usually in *1 business day*).

Note that we don't work on weekends.
However, if we release a major update recently, we are following the
issues.

For support questions, please also email us *Screets API key* which is
required for support questions. If you already included in your message,
you don't need to do anything else.
{#HS:907926243-4625#}

**Comment by andreasvirkus** [comment]
Thanks @vitaliy-grusha, `editor.view.dom.focus()` still works, but is there a way to set the cursor to the very end?

**Comment by hanspagel** [comment]
Try editor.focus('end')! Hope that helps.

**Comment by andreasvirkus** [comment]
Thanks for the quick reply @hanspagel!
Neither `this.editor.view.dom.focus('end')` nor `this.editor.focus('end')` seem to have any effect on the cursor position (but both focus the editor successfully).

**Comment by Humeira** [comment]
Any idea why this `editor.focus('end')` does not work on Safari?

They cursor only shows up after I have typed something on Safari, on other browsers I see the cursor when the editor is in focused.

**Comment by Arturexe** [comment]
In case you're using `vue`, try:

`editor.value.commands.focus()`

**Comment by lokge** [comment]
> Any idea why this `editor.focus('end')` does not work on Safari?
> 
> They cursor only shows up after I have typed something on Safari, on other browsers I see the cursor when the editor is in focused.

Have you been able to solve this problem?
