### ISSUE TITLE
TipTap with axios

### ISSUE THREAD

**Issue by konstantinvoronoy** [scrumpy/tiptap#393]
Hi! I couldn't find in documentation something about using this awesome editor with axios.

`axios.post('/api/post', {
                title: this.title,
                body: this.content
            })`

Here 'content' isn't working. Would you please tell me what should I use here?

Maybe, it's just stupid. I'm really sorry about that, I just recently started learning Vue

**Comment by afwn90cj93201nixr2e1re** [comment]
```js
editor: new Editor({onUpdate: ({ getHTML }) => {
						this.html=getHTML();
						if (this.html === '<p></p>')this.content = '';
						else this.content = this.html;
					}
				})
```

**Comment by konstantinvoronoy** [comment]
Thank you! When it posts a request, the title works. But the body literally does not exist.

<img width="295" alt="Снимок экрана 2019-07-22 в 10 42 21" src="https://user-images.githubusercontent.com/53155077/61606755-9b64d480-ac6d-11e9-866a-6779252d5f80.png">

The 'title' works because I use input tag. And the 'body' is from Editor which I guess 'content'. And it doesn't work. 

Right now I got:

`data() {
        return {
            editor: new Editor({

                extensions: [
                  new Blockquote(),
                  new BulletList(),
                  new CodeBlock(),
                  new HardBreak(),
                  new Heading({
                      levels: [1, 2, 3]
                  }),
                  new ListItem(),
                  new OrderedList(),
                  new TodoItem(),
                  new TodoList(),
                  new Link(),
                  new Bold(),
                  new Code(),
                  new Italic(),
                  new Strike(),
                  new Underline(),
                  new History(),
                  new Table({
                      resizable: true,
                  }),
                  new TableHeader(),
                  new TableCell(),
                  new TableRow(),
              ],
                onUpdate: ({ getHTML }) => {
            this.html=getHTML();
            if (this.html === '<p></p>')this.content = '';
            else this.content = this.html;
          },

          content: '',


            }),
            title: '',           

        }
    },


    methods: {
        AddPost() {
            axios.post('/api/posts', {
                title: this.title,
                body: this.content
            })
          }
        },


    beforeDestroy() {
        this.editor.destroy()
    }

}`

And the editor: 

`<editor-content class="editor__content" :editor="editor" />`

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you post screenshot of your webpage? And try to use vue extensions for browser, or add some log's.
Give some example on jsfiddle or codepen.

**Comment by afwn90cj93201nixr2e1re** [comment]
```js
<template>
	<div class="editor">
		<div @click=AddPost>Click on me for send request</div>
		<input v-model="title"/>
		<editor-content class="editor__content" :editor="editor" />
	</div>
</template>

<script>
    import { Editor, EditorContent } from 'tiptap';
    
	export default {
		components: {
			EditorContent,
		},
		data() {
			return {
				html: '',
				content: '',
				title: '',
				editor: new Editor({onUpdate: ({ getHTML }) => {
						this.html=getHTML();
						if (this.html === '<p></p>')this.content = '';
						else this.content = this.html;
					}
				}),
			}
		},
		methods: {
			AddPost() {
				console.log(this.title,this.content);
				axios.post('/api/posts', {
					title123: this.title,
					body123: this.content
				})
			}
		},
		beforeDestroy() {
			this.editor.destroy()
		}
		//mounted () {
//     this.unwatch = this.$watch('value', this.setInitialContent)
//   },
// methods: {
//     setInitialContent (content) {
//       if(this.editor.getHTML() == '<p></p>') {
//         this.editor.setContent(content)
//         this.unwatch()
//       }
//     }
//   }
	}
```
Try this.
Check console.

**Comment by konstantinvoronoy** [comment]
Man, I don't know how to thank you! It works perfectly! Thank you so-so much!
