### ISSUE TITLE
Configure keymap of History extension

### ISSUE THREAD

**Issue by Naoray** [scrumpy/tiptap#396]
**Is your feature request related to a problem? Please describe.**
I really like using `ctrl + z` for undoing and `ctrl + y` for redoing things. I've reviewed the History extension and it seems that `ctrl + y` is by default used only on windows machines.

**Describe the solution you'd like**
Adding a `keymap` option to the History extension which would enable to change the default used keymap.

**Describe alternatives you've considered**
Adding a simple option like `enableWindowsKeymap` which would use `ctrl + y` as 'redoing'.

**Comment by philippkuehn** [comment]
I removed the windows check. You can now `mod + y` on your mac.

**Comment by Naoray** [comment]
@philippkuehn thanks!
