### ISSUE TITLE
How out from codeblock?

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [scrumpy/tiptap#398]
Every tiptap component's is latest.
Check comment for gif.

**Comment by afwn90cj93201nixr2e1re** [comment]
![GIF2](https://user-images.githubusercontent.com/9306996/61644876-99733380-acb6-11e9-8286-e3048ec7d1ce.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
Shift enter. Ok.

**Comment by deepaksisodiya** [comment]
How about on mobile :)

**Comment by philippkuehn** [comment]
you can now leave code blocks with triple enter like in slack
