### ISSUE TITLE
How to detect focus in Pre?

### ISSUE THREAD

**Issue by nezzard** [scrumpy/tiptap#408]
I need to add class to **pre** which is focused now, onFocus has no target for detect current **pre** tag, how to do it?

**Comment by vitaliy-grusha** [comment]
You can use plugin https://prosemirror.net/docs/ref/#state.Plugin_System.
If you discover FloatingMenuPlugin.js, that is a part of tiptop, you can see update method, that receives all update in editor including cursor move.

Something like that in update method can solve you task:
```
const currentDom = view.domAtPos(state.selection.anchor)
if (currentDom.node.tagName === 'PRE') {
    currentDom.node.className = "class";
}
```

**Comment by nezzard** [comment]
The class disappears after being added

**Comment by vitaliy-grusha** [comment]
Maybe  **pre** node is not configured to has a class name.
By default, class name in **pre** is not allowed. It is described in node's schema:

```
  get schema() {
    return {
      content: 'text*',
      marks: '',
      group: 'block',
      code: true,
      defining: true,
      draggable: false,
      parseDOM: [
        { tag: 'pre', preserveWhitespace: 'full' },
      ],
      toDOM: () => ['pre', ['code', 0]],
    }
  }
```

**Comment by philippkuehn** [comment]
DOM manipulations are not a good idea because this will trigger ProseMirror to re-render this node.

@nezzard Would it be enough to check if the current selection (cursor) is within this node?

**Comment by nezzard** [comment]
@philippkuehn 
Yes, that will be enough.
I want the message to be displayed inside the "pre"
Something like CTRL + SHIFT to exit "pre"

For this, I thought of adding a class to pre which I am editing now.

**Comment by philippkuehn** [comment]
I've added a [focus extension](https://tiptap.scrumpy.io/focus) for this use case.
