### ISSUE TITLE
Add classes to default extensions

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [scrumpy/tiptap#410]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by afwn90cj93201nixr2e1re** [comment]
So, as one of contibutor suggested - there issue template, but not filled, bye.

How we can add custom classes to table?
I need this because some frameworks reset all default

![изображение](https://user-images.githubusercontent.com/9306996/61896317-be211280-af25-11e9-8a13-1f0020598da5.png)

https://bulma.io/documentation/elements/table/

![изображение](https://user-images.githubusercontent.com/9306996/61896404-f7598280-af25-11e9-9daf-79cd70691691.png)

So, then i need to add class to default table extension, but i didnt found any props for that in table node.
https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Table.js#L24

https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/TableNodes.js

https://bulma.io/documentation/elements/table/#modifiers

**Comment by hanspagel** [comment]
this is the default issue template. you need to fill out the issues.
