### ISSUE TITLE
Empty paragraphs contains <br> which is not in getHTML

### ISSUE THREAD

**Issue by chris-converdy** [scrumpy/tiptap#412]
I might be overlooking something but when you enter a few empty paragraphs it will render a <p> tag with a <br> inside. This <br> is not present when getting the HTML with getHTML. Is there a way to solve this?

 https://tiptap.scrumpy.io/export 

**HTML in browser**

<img src="https://cl.ly/8e4f3a6b36cc/Image%2525202019-07-27%252520at%2525204.01.21%252520PM.png"/>

**HTML from getHTML, no br tags here**

<img src="https://cl.ly/8a51492e1185/Image%2525202019-07-27%252520at%2525204.02.55%252520PM.png"/>

**Comment by philippkuehn** [comment]
This is intended behavior by ProseMirror. Otherwise you won‘t be able to type inside of empty paragraphs in some situations.

**Comment by chris-converdy** [comment]
I see. I'm using the editor as an inline editor and it's crucial that the text looks identical whether the editor is initiated or not. Do you have any suggestions for a workaround? Or are you familiar with a way of disabling this behavior?

**Comment by philippkuehn** [comment]
Hmm maybe you can solve it with CSS in this case? Something like:

```css
.ProseMirror > p > br:first-child:last-child {
  display: none;
}
```

**Comment by patrikengborg** [comment]
Any way to keep that `<br>` in an otherwise empty paragraph?

**Comment by chrisjbrown** [comment]
Also looking for a way to keep the `<br>` tags when calling `getHTML()`

**Comment by tjerman** [comment]
One solution would be to just use view's `innerHTML` (`view.dom.innerHTML`) - this will preserve those `<br>`'s.

This probably isn't the best idea (skipping `DOMSerializer`) in all cases, but for my use-case, it's good enough for now.

**Comment by ajgagnon** [comment]
One workaround I found it just to style things at the end so they work like <br> tags:

```css
p:empty::after {
    content: "\00A0";
}
```

**Comment by iannator10** [comment]
One solution that I'm currently using is that you can replace the "`<p></p>`" tags with "`<br>`" using Regex.

For Example:

```
methods: {
    removeP: function() {
         var removeRegexP = /<p><\/p>/g
         this.html = this.html.replace(removeRegexP, "<br>");
    }
}
```

You can now use this.html which is a string that has no "`<p></p>`" but with "`<br>`"

**Comment by gordilovvv** [comment]
Regex is a good solution for me. Like how talked @iannator10.

So, you can add `<br>` tag to empty `<p></p>` tag. Important, that you should check empty p tag with style attribute. Cause there may be tags like this `<p style="text-align: right"</p>` (with text align)

```
const P_REGEX = /(<p\s?((style=")([a-zA-Z0-9:;.\s()\-,]*)("))?>)(<\/p>)/g;

function insertBrTags(str) {
    return str.replaceAll(EMPTY_P_TAG_REGEX, '$1<br>$6');
}
```


And after that you should remove `<br>` tags before put it to editor:

```
const BR_REGEX = /(<br>)/g;

function removeBrTags(str) {
    return str.replaceAll(BR_TAG_REGEX, '');
}
```
I chose for this a computed property.

**Comment by tiendatleo** [comment]
> Regex is a good solution for me. Like how talked @iannator10.
> 
> So, you can add `<br>` tag to empty `<p></p>` tag. **Important, that you should check empty p tag with style attribute.** Cause there may be tags like this `<p style="text-align: right"</p>` (with text align)
> 
> ```
> const P_REGEX = /(<p\s?((style=")([a-zA-Z0-9:;.\s()\-,]*)("))?>)(<\/p>)/g;
> 
> function insertBrTags(str) {
>     return str.replaceAll(EMPTY_P_TAG_REGEX, '$1<br>$6');
> }
> ```
> 
> And after that you should remove `<br>` tags before put it to editor:
> 
> ```
> const BR_REGEX = /(<p\s?((style=")([a-zA-Z0-9:;.\s()\-,]*)("))?>)<br>(<\/p>)/g;
> 
> function removeBrTags(str) {
>     return str.replaceAll(BR_TAG_REGEX, '$1$6');
> }
> ```
> 
> I chose for this a computed property.

Recently I have an issue when I remove tag <br> from html content includes table. The empty <p /> tag has double <br /> tags, and the cursor be moved to the end of the editor.
Are you facing to this issue?
#2940

**Comment by craxrev** [comment]
In my case I have two components, an `Editor` and a `Viewer`, when switching between them both in the same screen, I can see the difference where in the `Viewer` component, "some" linebreaks gets "removed", so I ended up doing the same thing as ProseMirror does in the `Editor` component, which is:
- adding `<br>` to empty `<p></p>`
- also in case a paragraph has already a trailing `<br>` (new line) like for example: `<p>Lorem<br></p>` when rendered inside the ProseMirror, it will be `<p>Lorem<br><br></p>`

I don't know if there are any other cases, but this the final `Viewer` component I have so far:
```tsx
const Viewer: React.FC<Props> = ({
  className,
  html,
}) => {
  html = html.replaceAll('<br></', '<br><br></');
  html = html.replaceAll('<p></p>', '<p><br></p>');

  return (
    <div
      className={`prose max-w-none ${className}`}
      dangerouslySetInnerHTML={{
        __html: html,
      }}
    />
  );
};

export default Viewer;
```

And you call it like so:
```tsx
<Viewer
  className='h-full'
  html={editor?.getHTML()}
/>
```

Hope it help someone

**Comment by philippviereck** [comment]
You can use this [pm2html](https://github.com/mailbean/pm2html) to create a custom DOMSerializer and then serialize the JSON to HTML the way you want it. There is a transformer included to add `<br>` tags to all empty Textblocks, like TipTap (ProseMirror) does

**Comment by teslor** [comment]
While I like having `<br>` for line breaks in saved html, assume that using of Regex to add/remove `<br>` tag is quite error-prone and may lead to unpredictable bugs.
Styling of empty paragraphs to imitate empty lines as a simple workaround looks good enough. In [Chrome/Edge/Opera](https://caniuse.com/mdn-css_types_length_lh) it's already possible to use `lh` units which is semantically a more cleaner solution than pseudoelements. Here is the CSS to use `lh` units if it's supported by a browser and `:after` pseudolement otherwise.
```css
@supports (height: 1lh) {
  p:empty {
    height: 1lh;
  }
}
@supports not (height: 1lh) {
  p:empty::after {
    content: "\00A0";
  }
}
```

**Comment by varave** [comment]
My solution to the problem:
```
const CustomHardBreak = HardBreak.extend({
  addKeyboardShortcuts() {
    return {
      Enter: () => this.editor.commands.setHardBreak()
    }
  }
})
```
Editor instance:
```
this.editor = new Editor({
  extensions: [
    Paragraph,
    CustomHardBreak
  ]
})
```

**Comment by robinclaes** [comment]
Just came here to say, that if you use Tailwind, you can use the [Tailwind Typography](https://github.com/tailwindlabs/tailwindcss-typography) plugin.

The `prose` class will add the necessary spacing to empty `p`-tags.

**Comment by ebeigarts** [comment]
The issue is not just with empty `<p></p>` but also with `<p>line1<br></p>` when using HardBreak extension.

Currently i'm adding missing `<br>` in ruby when sanitizing/rendering safe html:

```ruby
class TipTapScrubber < Loofah::Scrubber
  # Add <br> to match editor's dom with `ProseMirror-trailingBreak`
  # https://github.com/ueberdosis/tiptap/issues/412
  # https://github.com/ProseMirror/prosemirror-view/blob/2da3ae3/src/viewdesc.ts#L1323-L1338
  def scrub(node)
    return unless node.node_name == 'p'

    if node.children.empty? || (
      node.children[-1].node_name == 'br' &&
      node.children[-1].classes.exclude?('ProseMirror-trailingBreak')
    )
      node.add_child('<br class="ProseMirror-trailingBreak">')
    end
  end
end

tiptap_scrubber = TipTapScrubber.new

html_fragment = Loofah.fragment(content.to_s)
# html_fragment.scrub!(permit_scrubber)
html_fragment.scrub!(tiptap_scrubber)
html_fragment.to_html(encoding: 'UTF-8').html_safe
```

**Comment by sankaSanjeeva** [comment]
> One workaround I found it just to style things at the end so they work like `<br>` tags:
> 
> ```css
> p:empty::after {
>     content: "\00A0";
> }
> ```

This is perfect, but I am going with regex since I store HTML content in the database. This way, I’m confident it can be used everywhere without this issue.

```
onUpdate={({ editor }) => {
  const html = editor.getHTML().replace(/<p><\/p>/g, '<br>');
  ...
}}
```

**Comment by thecodermehedi** [comment]
> const html = editor.getHTML().replace(/<p><\/p>/g, '<br>');

This will cause problem if you try press backspace
