### ISSUE TITLE
vee-validate how to validate editor content

### ISSUE THREAD

**Issue by 4spen** [scrumpy/tiptap#413]
Need to validate editor-content input field for any data inputed.

Tried to use something like this with no luck: 
` <editor-content :editor="editor" class="editor__content" v-validate="'max:10'" name="editor"/>`
 vee-validate does not show error if more than 10 characters inputed.

Thanks for any advice.

**Comment by philippkuehn** [comment]
This is not how v-validate will work because <editor-content> is not an input element. You have to manually validate the content with the update event of tiptap.
