### ISSUE TITLE
Cannot read property 'props' of undefined in get view()

### ISSUE THREAD

**Issue by Mehdi-Hp** [scrumpy/tiptap#415]
Using, [Create a Node as a Vue Component](https://github.com/scrumpy/tiptap#create-a-node-as-a-vue-component), it works fine, but if I extract component to a SFC like below, I get `Cannot read property 'props' of undefined`.
```vue
<template>
    <div class="iframe">
        <iframe class="iframe__embed" :src="src"></iframe>
        <input class="iframe__input" type="text" v-model="src" v-if="view.editable" />
    </div>
</template>

<script>
export default {
    name: 'Iframe',
    props: ['node', 'updateAttrs', 'view'],
    data() {
        return {};
    },
};
</script>
```
And using it like:
```js
import Iframe from './iframe.vue';

get view() {
        return Iframe;
    }
```
![image](https://user-images.githubusercontent.com/8641684/62125687-0f911f00-b2e3-11e9-897d-d2a7473f60bc.png)

**Comment by philippkuehn** [comment]
Please provide a codesandbox.

**Comment by Mehdi-Hp** [comment]
I can't currently provide any example for different reasons. so I'm gonna close this issue for now.
