### ISSUE TITLE
Behaviour different from scrumpy website (ordered list to bullet list)

### ISSUE THREAD

**Issue by languagesai** [scrumpy/tiptap#418]
when I copy the code the code given at https://github.com/scrumpy/tiptap/tree/master/examples/Components/Routes/Basic in index.vue I have a behaviour slightly different from the one on https://tiptap.scrumpy.io/ first example  : 
when I have an ordered list item selected and I click on the bullet list action nothing happen on my page, but on scrumpy it is perfectly working, I can't figure out what I am missing here...

**Comment by philippkuehn** [comment]
Please provide a codesandbox.

**Comment by languagesai** [comment]
Ok I figured it out because it worked on the codesandbox, in fact I had a former version of tiptap-extensions... sorry for that !
