### ISSUE TITLE
Link's pasteRules compete with Italic's pasteRules

### ISSUE THREAD

**Issue by roschaefer** [scrumpy/tiptap#421]
**Describe the bug**
This is an interesting glitch, which is hard to reproduce. I am however able to fix the bug on our side so assume a bug in `tiptap` itself.

**Steps to Reproduce**

Given your editor looks llike this:
```
      editor: new Editor({
        content: '',
        extensions: [
          new Italic(),
          new Link(),
          ...
        ]
      })
```

If you paste a link like this:
https://de.wikipedia.org/wiki/Yin_und_Yang

Sometimes, the `_und_` will be recognized as italic. This results in the following markup:
```html
<p class=""><a href="https://de.wikipedia.org/wiki/Yin" rel="noopener noreferrer nofollow" target="_blank" class="embed" contenteditable="false"><!----> <em> https://de.wikipedia.org/wiki/Yin </em></a><em>und</em>Yang</p>
```

This is how it looks:

![Screenshot - 2019-08-05T173704 547](https://user-images.githubusercontent.com/2110676/62476944-41552a80-b7a8-11e9-8ecf-a04359b7312d.png)

Interestingly I could only reproduce the error when copy+pasting the link to my programming editor (neovim) first and then to the browser editor.

**Expected behavior**
I expect the **entire** URL to get parsed as a link.

**Environment**
https://github.com/Human-Connection/Human-Connection/pull/952
My browser version:
```
$ chromium --version
Chromium 76.0.3809.87 Arch Linux
```

**Additional context**
Here's the fix on our side: https://github.com/Human-Connection/Human-Connection/pull/952/commits/52e03610876b4a580951315ab2c5dc477dad0c79

We simply disable copy+paste of markdown into our editor.

**Comment by philippkuehn** [comment]
See #286. You have to pass `Link()` before `Italic()`.
