### ISSUE TITLE
Latex Math

### ISSUE THREAD

**Issue by themindstorm** [scrumpy/tiptap#422]
**Describe the solution you'd like**
Similar to there being a code editor, there could be an editor for LaTeX math. Users can type in latex math, which will be rendered

**Describe alternatives you've considered**
Using images. Images of math equations can be generated [here](https://www.codecogs.com/eqnedit.php). These images can be [embedded](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cdpi%7B300%7D%20%5Chuge%20x%20%3D%20y%5E2)

**Comment by Alecyrus** [comment]
Try to use `Vue Component` to implement the feature on you own.

**Comment by njoguamos** [comment]
+1 for this.

**Comment by philippkuehn** [comment]
Latex will not be part of the core. Feel free to publish an extension.
