### ISSUE TITLE
onUpdate() callback, read key pressed

### ISSUE THREAD

**Issue by patelravi** [scrumpy/tiptap#425]
I need to handle key change and perform some logic based on enter pressed or other key pressed.

I am new to prosemirror and tip-tap.
I am using onUpdate() method to detect changes in editor. Is there any way i can find which key pressed in onUpdate() callback?

Or if not, can we add this functionality, also I tried to use `keymap` but I couldn't find any tiptap example with `keymap` implemented. If someone can give reference to example where `keymap` used, that would be helpful to me.

**Comment by philippkuehn** [comment]
Please check `onTransaction(transaction)` for any changes to the document.
