### ISSUE TITLE
autoFocus does not work anymore

### ISSUE THREAD

**Issue by KevinNTH** [scrumpy/tiptap#429]
**Describe the bug**
(Regression) Set `autoFocus` to true triggers an error: `RangeError: Position NaN out of range`.

**Steps to Reproduce / Codesandbox Example**
Set `autoFocus` to true

https://codesandbox.io/embed/tiptap-autofocus-does-not-work-l9vzs

**Expected behavior**
Should focus correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/1632391/63263210-41652800-c288-11e9-8a3b-6b38d14bba43.png)

**Environment**
 - OS: MacOS
 - Browser: Chrome
 - Version 1.24.2
 - Mobile / Desktop: Desktop

**Additional context**
It's a regression: happened after update.

**Comment by cswkim** [comment]
autoFocus does not bring up the keyboard in iOS (using 13.4.1). This has to do with iOS not allowing the keyboard without user interaction right? Has anyone found a workaround to programmatically bring up the keyboard in iOS browsers? I tried triggering `editor.focus()` or `editor.view.dom.focus()` in another element's `click()` event to no avail.

**Comment by lokge** [comment]
> autoFocus does not bring up the keyboard in iOS (using 13.4.1). This has to do with iOS not allowing the keyboard without user interaction right? Has anyone found a workaround to programmatically bring up the keyboard in iOS browsers? I tried triggering `editor.focus()` or `editor.view.dom.focus()` in another element's `click()` event to no avail.

have you solved the problem?
@cswkim
