### ISSUE TITLE
 Whether the image supports object storage oss

### ISSUE THREAD

**Issue by MoonCheung** [scrumpy/tiptap#435]
**Is your feature request related to a problem? Please describe.**
When I saw that your tiptap component library has `images` function and only requires us to provide the image URL, I felt a little troublesome. Could you please tell me whether you should submit the image to qinuyun object storage oss to process the HTTPS link address for generating new `images`

**Comment by MoonCheung** [comment]
@philippkuehn Please tell me if this supports uploading images instead of copying them to the HTTPS connection address here

**Comment by hlipeter** [comment]
@MoonCheung 问了那么多，过了这么久，你找到方法了嘛、、？

**Comment by hlipeter** [comment]
@MoonCheung 问了那么多，过了这么久，你找到方法了嘛、、？
