### ISSUE TITLE
Disable Paste

### ISSUE THREAD

**Issue by jankin-l** [scrumpy/tiptap#456]
Is there an easy way to disable being able to paste things into the editor?

**Comment by jankin-l** [comment]
onPaste(view, event, slice, moved = false) {
   // can intercept paste handle
   // How to make the paste invalid ？
}

**Comment by pju-** [comment]
You should be able to use Prosemirror handlePaste :
http://prosemirror.net/docs/ref/#view.EditorProps.handlePaste

Just return `true` and it will prevent the paste

You can use a Plugin for this, follow this template:
https://github.com/scrumpy/tiptap/issues/313

**Comment by jankin-l** [comment]
3q~,it's work well
