### ISSUE TITLE
Tab key behavior

### ISSUE THREAD

**Issue by Alecyrus** [scrumpy/tiptap#457]
**Describe the bug**
`Tab` kay would blur the editor, how should i do to prevent this behavior ?  It seems like the editor could not receive the `tab` input

**Expected behavior**
Four space or normal behaviors like vs code. 

**Environment**
 - macOS Catalina
 - Chrome 76
 - Version Latest
 - Desktop

**Comment by Alecyrus** [comment]
I modify the `ListItem.js` file, not sure it is an appropriate way...
```javascript
 keys({ type }) {
    return {
      Enter: splitListItem(type),
      Tab: chainCommands(sinkListItem(type), insertText("    ")),
      "Shift-Tab": liftListItem(type)
    };
  }
```

**Comment by arpitchaudhari** [comment]
Where is `ListItem.js` ? i.e. what is the location of `ListItem.js` in the diretory.

**Comment by PrimozRome** [comment]
@Alecyrus  Has this been fixed. TAB behaviour is still broken... It is a major issue!

**Comment by Alecyrus** [comment]
> Where is `ListItem.js` ? i.e. what is the location of `ListItem.js` in the directory.

You might be just import `ListItem` from `tiptap-extension`.  I copy these `nodes` and `marks` file from source code of  `tiptap-extension`.

**Comment by Alecyrus** [comment]
> @Alecyrus Has this been fixed. TAB behaviour is still broken... It is a major issue!

It works for me now. Could you please offer more information about this?

**Comment by PrimozRome** [comment]
@Alecyrus it is not working for me. I am using version `"tiptap": "^1.11.0"` and here is my implementation:

```
    this.editor = new Editor({
      extensions: [
        new Bold(),
        new Italic(),
        new Strike(),
        new Underline(),
        new Link(),
        new Heading({ levels: [1, 2, 3] }),
        new BulletList(),
        new ListItem(),
        new OrderedList(),
        new History(),
        new Placeholder({
          emptyNodeText: this.$t(this.placeholder)
        })
      ],

```

**Comment by Alecyrus** [comment]
Where you import `ListItem ` from ? ` tiptap-extension`? If so, you need to copy `ListItem.js` file from ` tiptap-extension` and edit related files, then import  `ListItem` from the modified version of `ListItem.js`, and then it should work.

**Comment by Alecyrus** [comment]
> > @Alecyrus Has this been fixed. TAB behaviour is still broken... It is a major issue!
> 
> It works for me now. Could you please offer more information about this?

That is because the editor do not capture `TAB` key event when you are typing in `paragraph`, we need to add `TAB` shortcuts in our editor instance, but it should not be added to `Paragraph` node, which will cause other unexpected behavior when the cursor in `ListItem` node. So, we need to add the `TAB` shortcut to `ListItem` node with `chainCommands` function.

**Comment by iannator10** [comment]
@Alecyrus Where can you find the `chainCommands` function? also the `insertText` function?

What I did is I copied the listItem.js in the tiptap-extensions folder, then I paste it on my main components folder. After that I import it on my editor.vue component, but it did not work,

Also, I edited the listItems.js on the tiptap-extensions folder like this:

```
import { Node } from 'tiptap'
import { splitListItem, liftListItem, sinkListItem } from 'tiptap-commands'

export default class ListItem extends Node {

  get name() {
    return 'list_item'
  }

  get schema() {
    return {
      content: 'paragraph block*',
      defining: true,
      draggable: false,
      parseDOM: [
        { tag: 'li' },
      ],
      toDOM: () => ['li', 0],
    }
  }

  keys({ type }) {
    return {
      Enter: splitListItem(type),
      Tab: chainCommands(sinkListItem(type), insertText("    ")),
      "Shift-Tab": liftListItem(type)
    };
  }

}
```

But it's  still not working. Thank you in advance!

**Comment by Alecyrus** [comment]
tiptap-commands

**Comment by iannator10** [comment]
Bro @Alecyrus Thank you so much. I have been looking for tab key solutions for about 2 days now :) It's now working

**Comment by kyleslight** [comment]
From my perspective it's a common case to avoid editor's blurring after typing `Tab`...

There should be a more elegant (and official) way to do so 😂

**Comment by MiloLug** [comment]
So is there any "official" way to deal with tabs now..?

**Comment by jetacpp** [comment]
So how do I replicate this with `tiptap v2` ?

I tried this code and it appeared to insert 4 spaces for a tab but the tab still tabbed. I don't want the tab key to be tabbing :(

`      Tab: () => this.editor.chain().sinkListItem('listItem')
        .command( ({tr}) => {
          tr.insertText('    ')
          return true
        })
        .run(),`

**Comment by kachmul2004** [comment]
@jetacpp found any solution for this?

**Comment by cbeninati** [comment]
@kachmul2004 

Maybe try this:

```js
addKeyboardShortcuts() {
  return {
    'Tab': (editor) => {
        // Do whatever you want here...

      return true // <- make sure to return true to prevent the tab from blurring.
    },
  }
},
```

Or, using @jetacpp 's example:

```js
addKeyboardShortcuts() {
  return {
    'Tab': () => {
      this.editor.chain()
        .sinkListItem('listItem')
        .command(({ tr }) => {
          tr.insertText(' ')

          return true
         })
        .run()

      return true // <- make sure to return true to prevent the tab from blurring.
    },
  }
},
```

**Comment by bonn-jaredbuttars** [comment]
@cbeninati, I'm running 2.0.3 and have edited ListItem with your suggested code but it's still blurring the editor on Tab. It successfully sinks the list item and inserts the text then blurs. Are you or anyone else still able to reproduce this problem?

Google Chrome Version 114.0.5735.91
Microsoft Edge Version 113.0.1774.57

**Comment by braden-w** [comment]
For those still visiting the thread in 2024, this is an extension that I passed into the `extensions` array. You can replace `TAB_CHAR` with anything of your choosing (spaces, etc.)

```typescript
const TAB_CHAR = '\u0009';

const TabHandler = Extension.create({
  name: 'tabHandler',
  addKeyboardShortcuts() {
    return {
      Tab: ({ editor }) => {
        // Sinks a list item / inserts a tab character
        editor
          .chain()
          .sinkListItem('listItem')
          .command(({ tr }) => {
            tr.insertText(TAB_CHAR);
            return true;
          })
          .run();
        // Prevent default behavior (losing focus)
        return true;
      },
    };
  },
});
```

**Comment by rchasman** [comment]
Following @braden-w to help out, I've extended the above to work well with Shift-Tab, and some nice considerations that prevent unexpected behaviours and losing focus :)

https://gist.github.com/rchasman/1504332a3b50eb4aa616f1d9341d4001

**Comment by fbt0wizard** [comment]
> ```ts
> Extension
> ```

this work but after saving the content in html the space gets cleaned out. 

so i was able to make it work like this. 

`const TAB_CHAR = '\u00A0\u00A0\u00A0\u00A0';`

I inserted an HTML entity (like &nbsp; for spaces). This ensures that the spacing is preserved when the content is serialized as HTML and later re-rendered

**Comment by martinstoeckli** [comment]
Implemented a minimal invasive extension, which handles tab keys only when outside of lists and keeps the list indentation intact. Wanted to share the [code](https://github.com/martinstoeckli/SilentNotes/blob/main/src/ProseMirrorBundle/src/tab-handler-extension.ts), because the thread was useful to me.

**Comment by OSZII** [comment]
I for the life of me can't figure out how to make Tab work...

This is my extensionsArray:
```js
let extensions: Extensions = [
		Text,
		IndentHandler,
		oneLiner,
		Paragraph.extend({
			addKeyboardShortcuts: () => {
				return {
					Enter: (): boolean => {
						onEnter?.();

						if (labelSuggestion.open || projectSuggestion.open || prioritySuggestion.open) {
							return false;
						}
						onCreate?.();
						return true;
					},
					Escape: (): boolean => {
						onEnter?.();

						if (labelSuggestion.open || projectSuggestion.open || prioritySuggestion.open) {
							return false;
						}
						onCreate?.();
						return true;
					}
				};
			}
		}),
		createCustomPlaceholder(`${taskDisplayName} name`),
		Mention.extend({
			name: 'suggestion-label'
		}).configure({
			deleteTriggerWithBackspace: true,
			HTMLAttributes: {
				class: 'suggestion-label'
			},
			suggestion: labelSuggestion.init(),
			renderHTML({ options, node }) {
				return renderHTMl(options, node);
			}
		}),
		Mention.extend({
			name: 'suggestion-project'
		}).configure({
			deleteTriggerWithBackspace: true,
			HTMLAttributes: {
				class: 'suggestion-project'
			},
			suggestion: projectSuggestion.init(),
			renderHTML({ options, node }) {
				return renderHTMl(options, node);
			}
		})
	];
```

I add these to my Editor here:
```js
editor = new Editor({
			extensions: extensions,
			element: editorEl,
			content: value,
			onUpdate(propsInput) {
				clearTimeout(inputTimeout);
				let textContent = propsInput.editor.getText().trim();
				inputTimeout = setTimeout(() => {
					onUpdate?.({ name: textContent });
					value = propsInput.editor.getHTML();
				}, props.delay);

				if (onUpdate) {
					return;
				}

				// Clear state if no suggestions are present
				if (!document.querySelector('.suggestion-label') && labelSet) {
					newTaskModalState.label = null;
					labelSet = false;
				} else if (document.querySelector('.suggestion-label')) {
					labelSet = true;
				}
				if (!document.querySelector('.suggestion-project') && projectSet) {
					newTaskModalState.project = null;
					projectSet = false;
				} else if (document.querySelector('.suggestion-project')) {
					projectSet = true;
				}

				if (taskDisplayName != 'Task') {
					return;
				}
				if (!document.querySelector('.suggestion-priority') && prioritySet) {
					newTaskModalState.priority = DropdownPriorities[1];
					prioritySet = false;
				} else if (document.querySelector('.suggestion-priority')) {
					prioritySet = true;
				}
				// Parse text as date
				const parsedResults = parseTextAsDate(textContent);

				const parsedResult = parsedResults?.[parsedResults.length - 1];
				if (parsedResult) {
					newTaskModalState.panelDate = parsedResult.date();
				} else {
					newTaskModalState.panelDate = initialPanelDate;
				}
				highlightText('', propsInput.editor);
				if (!parsedResult) return;
				let parsedText = parsedResult.text.trim();
				highlightText(parsedText, propsInput.editor);

				processing = false;
			},

			onTransaction(transaction) {
				editor = transaction.editor;
			},
			editorProps: {
				attributes: {
					class: `prose dark:text-white dark:prose-invert prose-2xl focus:outline-none max-w-full w-full dark:text-white text-neutral-950 ${textSize}`,
					tabindex: '0'
				}
			}
		});
```

This is my IndentHandler extension that should enable Tab:
```js
const IndentHandler = Extension.create({
		name: 'indentHandler',
		addKeyboardShortcuts() {
			return {
				Tab: ({ editor }) => {
					console.log('tab');

					return false;
				},
			};
		}
	});
```

But it still doesn't work.

I also tried in editorProps handleKeyDown and handleKeyPress event but it still won't work, can anyone help me?
