### ISSUE TITLE
How can I send a command (ex. commands.image) directly from a method instead of passing command from menubar to method?

### ISSUE THREAD

**Issue by zillazillazilla** [scrumpy/tiptap#460]
I have a modal that is used to upload an image to an API and return the hosted direct link. Ideally this modal should be opened when clicking a custom button in the editor, the user then uploads image, image link is stored and then after closing the modal/completing upload it passes the url to the tiptap component, presumably to a method that then sends the command 'commands.image'.

However no matter how I go about this I am getting:
`No value supplied for attribute src` and I am not sure exactly what this means. I am assuming it has something to do with not properly accessing the state of the editor as using the example at https://tiptap.scrumpy.io/images works fine.

I suppose I am asking how can I send a command out of scope?

````
insertImage(imgURL) {
      var command = this.editor.commands.image
      console.log(imgURL)
      if (imgURL !== null) {
        command({ imgURL })
      }
    },
````
As a blind stab in the dark `var command = this.$refs['editorMenuBar'].editor.commands.image` and a ref on the editor-menu-bar component also does not work.

I am going to assume I am doing something drastically wrong here and am misunderstanding. I can't seem to figure out how to send data/commands to tiptap from another component if I cannot access commands from a method? Perhaps I have missed an example that might help with this?

**Comment by zillazillazilla** [comment]
ahem... `command({ imgURL, src:imgURL })`

Sorted now, my mistake

**Comment by tonywong625** [comment]
I think I am having similar issue, I want to be able to pass in some custom variable when the command is triggered.

`commands.note({ src: 'url' });`

however I am not able to get that src in my custom plugin
