### ISSUE TITLE
Unable to add and use a text input in the MenuBar

### ISSUE THREAD

**Issue by pkkid** [scrumpy/tiptap#462]
**Describe the bug**
Adding a text input into the menubar doesn't work correctly as we are unable to click on it to edit text. The TipTap plugin MenuBar is swallowing all mouse click events (see line 12 in MenuBar.js).

**Steps to Reproduce**
1. Add an input type=text in a editor-menu-bubble.
2. Try clicking and adding text in said input.

**Expected behavior**
I should be able to add arbitrary elements to a menu bar and have them work as expected. In this case, I was trying to integrate a Links input into the non-floating menubar.

**Additional context**
I believe all that needs to be done here is more explicitly capture and preventDefault() on the MenuBar.js mousedown event.

**Comment by jonasdumas** [comment]
It's the same bug described here:
https://github.com/scrumpy/tiptap/issues/454

Hope we'll have a solution quickly

**Comment by pkkid** [comment]
Cool, thanks.
