### ISSUE TITLE
Placeholder appeared when content is not empty

### ISSUE THREAD

**Issue by Leecason** [scrumpy/tiptap#463]
**Describe the bug**
In my project, placeholder is only visible when the editor is completely empty, but i'm just empty in the first line, and have content the next line, now i focus the first line, placeholder appeared. 

**Steps to Reproduce / Codesandbox Example**
1. Empty first line.
2. Input some content in the second line.
3. Focus the first line.
4. Placeholder appeared.

Can reproduce in https://tiptap.scrumpy.io/placeholder

**Expected behavior**
Only show placeholder when the editor is completely empty.

**Screenshots**
<img width="465" alt="屏幕快照 2019-09-26 14 47 57" src="https://user-images.githubusercontent.com/17562078/65664782-ab81a180-e06c-11e9-8569-d3d168d518b2.png">

**Environment**
 - OS Mac
 - Browser Chrome
 - Desktop

**Comment by usb248** [comment]
Same on FF (i think this bug isn't specific to a browser/OS)
![image](https://user-images.githubusercontent.com/7659927/66261006-945a5680-e7c6-11e9-95b4-3765043b6558.png)

**Comment by philippkuehn** [comment]
i've added a fix for this in 1472254

there is a new `emptyEditorClass` option you can use for `Placeholder`

**Comment by usb248** [comment]
RangeError: Duplicate use of selection JSON ID cell 🤔

**Comment by usb248** [comment]
Works well 👍 thanks

**Comment by iliyaZelenko** [comment]
This does not work as needed if you take [this example](https://tiptap.scrumpy.io/title) from the site.
