### ISSUE TITLE
Safari crashes on input

### ISSUE THREAD

**Issue by winterdedavid** [scrumpy/tiptap#464]
**Describe the bug**
The most recent desktop version(s) of Safari (13.0.1 and also 12.1) seem to completely crash (permanent spinning beach ball) when inputting the first character into the tiptap editor, requiring a force quit of Safari itself. The Javascript console itself shows no error logs when this happens. We originally noticed this in our own application, but it appears to also occur on the demo editor on the tiptap homepage, identical behaviour.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.scrumpy.io/ 
2. Input some text in the demo editor

**Environment**
 - OS: macOS Mojave
 - Browser Safari
 - Version 13.0.1 (and apparently also 12.1)
 - Mobile / Desktop: Desktop (confirmed that it does not occur on mobile)

**Comment by techouse** [comment]
I can confirm the behaviour.

*Environment*

- OS: macOS Mojave 10.14.6
- Browser: Safari 13.0.1 (14608.2.11.1.11)

**Comment by philippkuehn** [comment]
omg… this took me a long time. the crash was caused by `font-family: -apple-system;` on the demo page. it's a safari bug 🤦‍♂️

**Comment by winterdedavid** [comment]
Big thanks for the quick solution @philippkuehn ! ;)
