### ISSUE TITLE
CodeBlockHighlight not highligting until first edit in a code block

### ISSUE THREAD

**Issue by pkkid** [scrumpy/tiptap#465]
**Describe the bug**
When I first load a page containing the editor, the code blocks are not highlighting. However, as soon as I edit a code block they all get highlighted properly. Even something as simple as adding a space gets it all looking correct.

Unfortunately, I'm unable to reproduce this in codesandbox (it works as expected there). But thought I might ask here in case you've seen this behavior before. Is there a method I can call within Tiptap to trigger highlight.js to do its work after I initialize the editor? Maybe I can manually call the function that is triggered when I edit a code block. https://codesandbox.io/s/vue-template-ozu7u

There are no errors displayed in the console.

**Environment**
OS: Linux
Browser: Chrome
Tiptap: 1.25.0
Tiptap-extensions: 1.27.0
Vue: 2.6.10

**Comment by pkkid** [comment]
OK, I'm closing this one.

After a lot of debugging in the code I have found it was something bad in the content I was pulling from my server. Creating a second page of content with a short code snippet showed everything working as expected. Then I tried copying the content from the broken entry and pasting it onto the working page, and it started working as expected as well! :angry:

**Comment by mekery** [comment]
> OK, I'm closing this one.
> 
> After a lot of debugging in the code I have found it was something bad in the content I was pulling from my server. Creating a second page of content with a short code snippet showed everything working as expected. Then I tried copying the content from the broken entry and pasting it onto the working page, and it started working as expected as well! 😠

@pkkid I encountered the same problem.

I save the json to the sever, when pull it from server and load it to editor using setContent, the code was not highlighted until edit.

How do you solve this problem?

**Comment by LinLinQiQi** [comment]
@mekery You should edit the Highlight.js to trigger the code highlight [https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/plugins/Highlight.js#L73](url)
example:
`if( content has been set ){
return getDecorations({ doc: transaction.doc, name })
}`

**Comment by getflourish** [comment]
@LinLinQiQi Can you provide more details? What should go inside the if clause?

**Comment by samiell** [comment]
@getflourish, the condition triggers in the second case only when the page is loaded. if the document is updated, it never triggers. If you reload the page it triggers
``if ( (transaction.docChanged && [nodeName, previousNodeName].includes(name)) ||
         transaction.updated === 1
   ) {
           return getDecorations({ doc: transaction.doc, name })
  }
