### ISSUE TITLE
Provide proper docs on how to use this component in an app

### ISSUE THREAD

**Issue by bhaidar** [scrumpy/tiptap#466]
I tried to use this component in a Vue app however I was not lucky in terms of maintaining the styles and look and feel of that of the examples pages.

I would be great if you can provide a docs to explain in detail how to integrate this component in a Vue app and maintain the proper styling.

For instance all H1 tags were converted to P tag in the app. Maybe there are missing files or some classes need to be registers with Vue component? 

Thanks

**Comment by philippkuehn** [comment]
duplicate of #162
