### ISSUE TITLE
Avoid links from opening

### ISSUE THREAD

**Issue by rodrigopedra** [scrumpy/tiptap#479]
**Is your feature request related to a problem? Please describe.**

I am always frustrated when I cannot avoid the links created in my editor to open. I would like the editor to work as an editor where the links can be selected by clicking as all the other text without any navigation 

**Describe the solution you'd like**

When some click a link in the editor no navigation should happen just move the cursor to the link as with all other text

**Describe alternatives you've considered**

Currently I am extending the Link class from the tiptap-extensions and overriding the plugins getter to return an empty array.

I tried adding event listeners to parent elements, with capture but could not prevent the handler added by the plugin to fire. Currently it checks if the target is an anchor tag and opens a new tab with `window.open`

https://github.com/scrumpy/tiptap/tree/master/packages/tiptap-extensions/src/marks#L54-L70

The ideal solution, in my opinion, is to add a way to configure this behavior. I fear that, with my current approach, it could break as I am extending an underlying class. Below is a snippet of my approach:

~~~js
import {Link as BaseLink} from 'tiptap-extensions';

class Link extends BaseLink {
    get plugins() {
        return [];
    }
}
~~~

**Additional context**

**Comment by philippkuehn** [comment]
There is a new setting for links:

```js
new Link({
  openOnClick: false,
})
```

**Comment by rodrigopedra** [comment]
Thanks!

**Comment by goamn** [comment]
Would be great to extend this so that we can provide it with a UI to render so it's a more polished and standard behavior.

**Comment by xkubow** [comment]
How should I enable the click on ctrl key? Can I change openOnClick to true when ctrl key is down? 

Thanks
