### ISSUE TITLE
It should be possible to not include Paragraph if another block type node is being used

### ISSUE THREAD

**Issue by mithrilstar** [scrumpy/tiptap#483]
**Describe the bug**
I am trying to develop an editor that only allows BulletList Nodes. However it seems like it's not possible to skip having a Paragraph extension in the editor. I do not understand why this should be so if I am allowing a top level block node of type bulletList instead... 

**Steps to Reproduce / Codesandbox Example**
1. When configuring editor instance, do like
![image](https://user-images.githubusercontent.com/6938589/66268228-febbd700-e858-11e9-96db-5918d07f7bd3.png)

2. The editor looks like : (menubar disappears and can not click inside)

![image](https://user-images.githubusercontent.com/6938589/66268503-93bfcf80-e85b-11e9-94a0-47c03c5e6ab3.png)

3. Error in console : 
`[Vue warn]: Error in data(): "SyntaxError: No node type or group 'paragraph' found (in content expression 'paragraph block*')"`

![image](https://user-images.githubusercontent.com/6938589/66268314-d385b780-e859-11e9-99fd-7529fc1386cd.png)

4. if I uncomment `new Paragraph()` line, the errors go away and I see
![image](https://user-images.githubusercontent.com/6938589/66268535-d1245d00-e85b-11e9-8f28-22c9015932f6.png)

**Expected behavior**
Paragraph should only be required if there is no other block Node configured at all

**Comment by mithrilstar** [comment]
I looked at some more and it seems paragraph is required since list item's content is of type paragraph... which is fair i suppose.. 

In which case how should I go about restricting the top level entries to only be of type bulletList?

**Comment by mithrilstar** [comment]
I was able to figure out an approach after going through some prosemirror docs. For anyone else in a similar situation, the solution was to have another Doc analogous node like this

![image](https://user-images.githubusercontent.com/6938589/66290025-d9cc7000-e8fb-11e9-89ae-69aefdfa9a96.png)
and use that in place of Doc() I have left Paragraph as it is since ListItem uses Paragraph but I bellieve I've hit upon the approch that I should use for my use case.

Closing the issue.

**Comment by natemwilson** [comment]
For those on a more modern version, here is how I solved this problem:

```js
  const editor = useEditor({
    extensions: [
      Document.extend({ content: "bulletList" }),
      Paragraph,
      Text,
      BulletList,
      ListItem.extend({ content: "paragraph" }),
    ],
  });
```
