### ISSUE TITLE
Editor loses focus if clicked on menu-bar in Vue-Portal in version 1.26.2

### ISSUE THREAD

**Issue by thettler** [scrumpy/tiptap#485]
I have an` <editor-menu-bar>` inside a vue-portal (https://github.com/LinusBorg/portal-vue).
If i click on the menu bar the onBlur() will be called and i lose focus on the Editor. 
This behavior is new in 1.26.2. I installed version 1.26.1 again to check. 

Here is the Code:
https://codesandbox.io/s/vue-issue-template-c3m2y?fontsize=14

**Expected behavior**
The onBlur() method should not be called.

Thank you for the awsome Editor and your work 😄 ❤️

**Comment by eric-addcream** [comment]
This happens for us without vue-portal as well.
Editor loses focus when clicking on a button in the menu bubble. The command then never runs since the text selection is lost, making the bubble menu non-functional at this point.

Downgrading to 1.26.1 solves the problem.

**Comment by colq2** [comment]
I can confirm this behavior. The interesting part is: If you set a debugger and go through the code step by step the buttons in the menu bubble are working as expected.

**Comment by Neophen** [comment]
Still reproduces in `v1.26.6`

**Comment by itsnwa** [comment]
Having the same issue in `1.26.6`. I'm using the `editor-menu-bar` element and hiding it with css transform on `!editor.focused` as soon as I click on a command, the editor blurs and click is not registered.

**Comment by Nastalgua** [comment]
Still reproduces in `v1.27.1`.

**Comment by chrishessler** [comment]
I have this issue in `1.29.6`.

**Comment by amiceli** [comment]
Same in 1.30.0, any news about this bug ?

**Comment by zcserei** [comment]
+1, same happening on `1.31.0`.

**Comment by TechnoPvP** [comment]
Using the editor in SvelteKit 1.0.0.230, the editor doesn't completely lose focus but it does flicker when formatting from a menu bar, any thoughts on how to fix this?

**Comment by pam81** [comment]
same issue with beta version. any suggestion to avoid it ?
