### ISSUE TITLE
Position -2 out of range

### ISSUE THREAD

**Issue by rosnaib11** [scrumpy/tiptap#488]
Throwing an error when clicking table if the content are empty.  I have to type first before table works. Even on the docs you can see it https://tiptap.scrumpy.io/tables. Try to clear all text and click the table button

![image](https://user-images.githubusercontent.com/26837762/66706680-6e095d80-ed68-11e9-92b6-f96155d17d74.png)

**Comment by guillaumeperes** [comment]
Got this error too... :(

**Comment by Chrissi2812** [comment]
I screwed this up with my changes made in #474.
Should be fixed however in this https://deploy-preview-496--scrumpy-tiptap.netlify.com/tables
