### ISSUE TITLE
Table Borders Doesn't appear

### ISSUE THREAD

**Issue by gkandemi** [scrumpy/tiptap#498]
**Table Borders Doesn't appear**
When I tried making table, I couldn't see table borders. Also I couldn't select any row and cols as demo page. 

Could you please help me about this situation?

Thanks in advance!

![image](https://user-images.githubusercontent.com/5469995/67053074-fad96000-f148-11e9-9edb-64b4a927b4af.png)

**Comment by oliverhoad** [comment]
I'm having the same issue. Are you using Vuetify?

**Comment by philippkuehn** [comment]
tiptap comes without styling.

**Comment by dsheehan101** [comment]
> I'm having the same issue. Are you using Vuetify?

Hi @oliverhoad , Im having the same issue using Vuetify. Did you ever find a way around this?
Thanks

**Comment by curtaandrei** [comment]
An easy way to apply a border to the table is to create a css class with the desired styling and then apply it to the `editor-content`

Example that I got by inspecting the demo page:
`.editor__content table td, .editor__content table th {
    min-width: 1em;
    border: 2px solid #ddd;
    padding: 3px 5px;
    vertical-align: top;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    position: relative;
}`
this has to be global styling 

and then you just apply it to the editor:
 `<editor-content
      :editor="editor"
      class="editor__content"
      />`

**Comment by JohnyIrush** [comment]
> An easy way to apply a border to the table is to create a css class with the desired styling and then apply it to the `editor-content`
> 
> Example that I got by inspecting the demo page:
> `.editor__content table td, .editor__content table th { min-width: 1em; border: 2px solid #ddd; padding: 3px 5px; vertical-align: top; -webkit-box-sizing: border-box; box-sizing: border-box; position: relative; }`
> this has to be global styling
> 
> and then you just apply it to the editor:
> `<editor-content :editor="editor" class="editor__content" />`

Thanks, This worked

**Comment by AryNoe** [comment]
Hi! In order to display border styles or any other style outside the editor, you need to extend the TableCell extension and define the renderHTML function. Here an example:

const CustomTableCell = TableCell.extend({
  addAttributes() {
    return {
      // extiendo los atributos del padre, luego defino los propios
      ...this.parent?.(),

      borderStyle: {
        default: '2px solid #ced4da',
        parseHTML: element => element.style.borderStyle || '2px solid #ced4da',
        renderHTML: attributes => {
          return {
            style: `border: ${attributes.borderStyle}`,
          };
        },
      },
      backgroundColor: {
        default: null,
        parseHTML: element => element.getAttribute('data-background-color'),
        renderHTML: attributes => {
          return {
            'data-background-color': attributes.backgroundColor,
            style: `background-color: ${attributes.backgroundColor}`,
          }
        },
      },
      style: {
        default: 'height: 28px; padding: 3px 5px'
      }
    }
  },
})

Remember to include it in the array of extensions on the constructor:

 extensions: [
          CustomTableCell ,
          StarterKit,
          otherExtensions
          ]
          
If you don't display borders inside the editor, just use the suggested css classes on the Tiptap documentation:

.tiptap {
  table {
    border-collapse: collapse;
    table-layout: fixed;
    width: 100%;
    margin: 0;
    overflow: hidden;

    td,
    th {
      min-width: 10em;
      border: 2px solid #ced4da;
      padding: 3px 5px;
      vertical-align: top;
      box-sizing: border-box;
      position: relative;

      > * {
        margin-bottom: 0;
      }
    }

    th {
      font-weight: bold;
      text-align: left;
      background-color: #f1f3f5;
    }

    .selectedCell:after {
      z-index: 2;
      position: absolute;
      content: "";
      left: 0;
      right: 0;
      top: 0;
      bottom: 0;
      background: rgba(200, 200, 255, 0.4);
      pointer-events: none;
    }

    .column-resize-handle {
      position: absolute;
      right: -2px;
      top: 0;
      bottom: -2px;
      width: 4px;
      background-color: #adf;
      pointer-events: none;
    }

    p {
      margin: 0;
    }
  }
}

Hope it was useful to someone 🤓
