### ISSUE TITLE
add  href dynamically to each url

### ISSUE THREAD

**Issue by darbaoui** [scrumpy/tiptap#500]
hi guys .
i m using `tiptap` as editor to create a post like twitter and facebook post, my **probleme** is if a user tap some text and this text include a url, the editor convert it dynamically to href

> `hello world https://twitter.com`

convert to dynamically

> hello word [https://twitter.com](https://twitter.com)

any suggestion

**Comment by Auxxxxlx** [comment]
`inputRule` may help you.
