### ISSUE TITLE
`doc` property

### ISSUE THREAD

**Issue by slava-vishnyakov** [scrumpy/tiptap#504]
**Describe the bug**
https://tiptap.scrumpy.io/export says that you need to use `doc` property to pass in JSON. In reality it seems to me you need to use `content` property, passing an object:

![image](https://user-images.githubusercontent.com/817931/67495944-55604800-f684-11e9-8c67-eda4886c78e4.png)

![image](https://user-images.githubusercontent.com/817931/67495964-5d1fec80-f684-11e9-8922-0c25c283b7aa.png)

(removed the rest of the sections as they seem non-relevant)

P.S. I tried using `doc` property - it doesn't work, using `content` and passing in an object - works.

**Comment by philippkuehn** [comment]
You can pass a html string:

```js
new Editor({
  content: '<p>This is just a boring paragraph</p>',
})
```

or a json object:

```js
new Editor({
  content: {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "This is just a boring paragraph"
          }
        ]
      }
    ]
  },
})
```

please re-open if there is any problem with it.

**Comment by slava-vishnyakov** [comment]
@philippkuehn My problem is not with the code, my problem is that the docs are incorrect.

> https://tiptap.scrumpy.io/export says that you need to use `doc` property to pass in JSON. 

![image](https://user-images.githubusercontent.com/817931/67496933-dec44a00-f685-11e9-992d-a5e09c870650.png)

It really seems to me that docs say I need to pass in `doc`, where in reality I need to use `content` property.

Thanks for the TipTap BTW! It's awesome!

**Comment by slava-vishnyakov** [comment]
To be clear - I think that docs need to be fixed.

**Comment by philippkuehn** [comment]
ah! you are right. fixed now.

**Comment by slava-vishnyakov** [comment]
@philippkuehn Awesome! Thank you!
