### ISSUE TITLE
Custom data attributes are stripped

### ISSUE THREAD

**Issue by fvanhove** [scrumpy/tiptap#520]
Hey, i'm having an issue when adding custom data attributes. 

I have made an annotation feature that will include a data-annotation-id to the html. 
This can be added to any element.

The difference with the build in mention feature is that the data attributes are not added in the TipTap editor itself. 

The problem i'm facing is when (after adding a data-attribute) I update the html using the editor all data attributes are stripped. 

Would it be possible to add the option to allow a preset of data-attributes not to be stripped? 

Kind regards

**Comment by fvanhove** [comment]
I found a solution for my problem
I extended the base nodes in order to allow specific data-attributes if present. 

`import { Node } from 'tiptap'
import { setBlockType } from 'tiptap-commands'

export default class Paragraph extends Node {

    get name() {
        return 'paragraph'
    }

    get schema() {
        return {
            attrs: {
                annotationId: {
                    default: null
                },
            },
            content: 'inline*',
            group: 'block',
            draggable: false,
            parseDOM: [{
                tag: 'p',
                getAttrs(dom) {
                    console.log(dom);
                    return { annotationId: dom.dataset.annotationId };
                }
            }],
            toDOM: node => ['p', { 'data-annotation-id': node.attrs.annotationId }, 0],
        }
    }

    commands({ type }) {
        return () => setBlockType(type)
    }

}`

**Comment by jeremybenaim** [comment]
Hey @fvanhove! I'm considering using tiptap to create an editor with annotations too. I would be curious to learn more about your solution if you don't mind sharing a bit more? Thanks 🙏
