### ISSUE TITLE
Remove focuse outeline of editor

### ISSUE THREAD

**Issue by BiswasSuman** [scrumpy/tiptap#526]
I am unable to remove the outline of the editor when clicking it.
**Please help me to do this**
![tiptap-editor - Google Chrome_041](https://user-images.githubusercontent.com/36669638/69306742-98dfaf00-0c4e-11ea-9048-42a29b2c8f7c.png)

**Comment by chkb** [comment]
I have the same issue, it looks like the ProseMirror-focused class gets appends when you click.
But it seems impossible to overwrite that specific :focus class.

**Comment by philippkuehn** [comment]
Styling is not part of tiptap. It's renderless. Removing focus is basic CSS.

```css
.ProseMirror:focus {
    outline: none;
}
```

**Comment by chkb** [comment]
@philippkuehn your solution does not work.

**Comment by BiswasSuman** [comment]
@philippkuehn Thank you very much. Actually I am also tried this. The first time it not worked because I add CSS under  **scoped**, But after adding this CSS globally it working.

@chkb Please add this code globally, it will work

```html
<style >

.ProseMirror:focus {
    outline: none;
  }

</style>
```

**Comment by imfunniee** [comment]
or just use /deep/ .ProseMirror:focus

**Comment by chkb** [comment]
@BiswasSuman That worked! - Thanks!

**Comment by rbrace** [comment]
> @philippkuehn your solution does not work.

of course it doesn't

**Comment by bill-dou** [comment]
```
.ProseMirror-focused:focus {
    outline: none;
}
```

**Comment by milahu** [comment]
```css
.ProseMirror-focused {
  outline: none;
}
```

**Comment by Nirav-Gaglani** [comment]
> Styling is not part of tiptap. It's renderless. Removing focus is basic CSS.
> 
> ```css
> .ProseMirror:focus {
>     outline: none;
> }
> ```

@philippkuehn  Thank you, it worked!

**Comment by yoannes** [comment]
This worked for me

```
  &:focus {
    outline: none !important;
  }
```

**Comment by apodacaduron** [comment]
Was able to remove it adding a class to the editorProps
```ts
editor.value = new Editor({
    content: 'Yessss',
    ....
    editorProps: {
      attributes: {
        class: `text-editor__editor`,
      },
    },
  });
```
And then in scss
```sass
.text-editor__editor {
      &:focus {
           outline: none;
      }
}
```

**Comment by pbell23** [comment]
If you're using tailwindcss and don't want to add a css file, you can do : 
```javascript
const editor = useEditor({
    editorProps: {
      attributes: {
        class: 'focus:outline-none',
      },
    }
});
```

**Comment by benthecoder** [comment]
> If you're using tailwindcss and don't want to add a css file, you can do :
> 
> ```js
> const editor = useEditor({
>     editorProps: {
>       attributes: {
>         class: 'focus:outline-none',
>       },
>     }
> });
> ```

You're a life saver thank you!!

**Comment by incodeuz** [comment]
> Styling is not part of tiptap. It's renderless. Removing focus is basic CSS.
> 
> ```css
> .ProseMirror:focus {
>     outline: none;
> }
> ```

Bro, really usable, thanks

**Comment by C-W-D-Harshit** [comment]
> If you're using tailwindcss and don't want to add a css file, you can do :
> 
> ```js
> const editor = useEditor({
>     editorProps: {
>       attributes: {
>         class: 'focus:outline-none',
>       },
>     }
> });
> ```

You are a life saver!

**Comment by abhavsarMedhavyn** [comment]
.ProseMirror:focus {
    outline: none;
}

This worked for me!!

**Comment by Vituli** [comment]
Some help ?? 

ididnt figure how to remove the border and the focus 
```

<RichTextEditor
            editable={editable}
            editorProps={{
              attributes: {
                class: 'focus:outline-none',
              },
            }}
            ref={rteRef}
            content={comment.content}
            extensions={extensions}
          />
```

**Comment by Vituli** [comment]
> Someone help ?? i am using [Tiptap & MUI ](https://github.com/sjdemartini/mui-tiptap)
> 
> ididnt figure how to remove the border and the focus
> 
> ```
> 
> <RichTextEditor
>             editable={editable}
>             editorProps={{
>               attributes: {
>                 class: 'focus:outline-none',
>               },
>             }}
>             ref={rteRef}
>             content={comment.content}
>             extensions={extensions}
>           />
> ```

<RichTextEditor
            editable={editable}
            RichTextFieldProps={{
              variant: editable ? 'outlined' : 'standard',
            }}
            
            ref={rteRef}
            content={comment.content}
            extensions={extensions}
          />

**Comment by RainCount** [comment]
> If you're using tailwindcss and don't want to add a css file, you can do :
> 
> ```js
> const editor = useEditor({
>     editorProps: {
>       attributes: {
>         class: 'focus:outline-none',
>       },
>     }
> });
> ```

All the solutions above are not working for me
This does help

**Comment by akreienbring** [comment]
Had to add both custom styles to react to get completely rid of the editor outline:

```
/* disable the focus outline of tiptap editor */
.ProseMirror-focused {
  outline: none;
}
.ProseMirror:focus {
  outline: none;
}
```

**Comment by silas546** [comment]
For those using React & MUI, I wound up having to create a styled component (something I loathe doing) to override this behavior:


```typescript
export const TipTapEditorContent = styled(EditorContent)(({ theme }) => ({
  flexGrow: 1,
  height: '100%',
  padding: theme.spacing(2),
  overflowY: 'auto',
  '& > div': {
    minHeight: '4rem',
    outline: 'none',
  },
}));
``` 

```typescript
<TipTapEditorContent editor={useEditorConfig} />
```

**Comment by IcyFoxe** [comment]
I would say this is default browser behavior for `contenteditable` elements, so maybe removing the outline by default for those elements is better approach? Then you can style them however you like.

```css
[contenteditable] {
  outline: none;
}
```

**Comment by DRodrigues17** [comment]
@philippkuehn thank you very much
