### ISSUE TITLE
import Icon from 'Components/Icon' not found

### ISSUE THREAD

**Issue by woerdeman** [scrumpy/tiptap#528]
**Describe the bug**
import Icon from 'Components/Icon'  

gives Module not found: Error: Can't resolve 'Components/Icon'

**Steps to Reproduce / Codesandbox Example**

 Fork this or create a new Codesandbox replicating your error
 https://codesandbox.io/s/qxv5m9y6oq?fontsize=14

**Expected behavior**

**Screenshots**

**Environment**
 - Mobile / Desktop: [eg. Desktop]

**Additional context**

**Comment by philippkuehn** [comment]
Duplicate of #125
