### ISSUE TITLE
How to create a custom dropdown in the menu

### ISSUE THREAD

**Issue by damonjanis** [scrumpy/tiptap#532]
I'd like to create a custom dropdown menu item that will insert merge codes into the document at the cursor position. In the ProseMirror docs it describes doing this by defining a schema via a node spec.

In reviewing the tiptap documentation I'm not recognizing how to leverage this capability. How would this be done in tiptap? Thank you!

**Comment by damonjanis** [comment]
Actually I just found it on the github readme: https://github.com/scrumpy/tiptap#create-custom-extensions so closing this out.

**Comment by arthabus** [comment]
Hi @damonjanis, were you able to achieve that? Do you maybe have any code reference you could share?

Trying to do the same thing for my project
