### ISSUE TITLE
Space removed by markdown bold and italic shortcuts

### ISSUE THREAD

**Issue by rdela** [scrumpy/tiptap#546]
When one surrounds text with *, **, _, or __ to create bold or italic text, trailing spaces are removed, while using menu buttons to bold or italicize text preserves trailing spaces.

**Steps to reproduce the behavior:**
1. Go to any of the examples, such as [Basic](https://tiptap.scrumpy.io/)
2. Add * before and after "this"
3. Observe that while "this" is now italicized, the space before "is" has been removed

**Expected behavior**
Trailing spaces after text bolded or italicized text should be preserved.

**Environment**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Version: 78.0.3904.108 (or 79.0.3945.79) 
 - Mobile/Desktop: Desktop

**Comment by philippkuehn** [comment]
fixed with #502
