### ISSUE TITLE
Prevent new line after pressing enter to create code block

### ISSUE THREAD

**Issue by philippkuehn** [scrumpy/tiptap#57]
![oct-10-2018 10-56-38](https://user-images.githubusercontent.com/2500670/46724949-5ee66000-cc7b-11e8-9173-f21285121e54.gif)

We should prevent this. With pressing space everything is fine but uncommon.

**Comment by jimjja** [comment]
I would like to tackle this one.

**Comment by philippkuehn** [comment]
This would be great! 👍

**Comment by philippkuehn** [comment]
@jimjja no luck? 😅

**Comment by jimjja** [comment]
@phillippkuehn I had a look at the project but couldnt get my head around it... it might be helful if there is more documentation of the project.

**Comment by philippkuehn** [comment]
This behavior changed in the latest versions of prosemirror.
