### ISSUE TITLE
Empty content keeps empty html tags. How to check if content is empty?

### ISSUE THREAD

**Issue by kikky7** [scrumpy/tiptap#579]
As mentioned in title, empty content keeps empty htmls tags (p, h1, h2, ...), but through Placeholder extension I can add class when content is empty. Is there any method on Editor which can check for empty content which returns true/false or at least get content (there are only getHtml and getJSON methods mentioned in docs); based on this I could just update data to an empty string instead of empty html tags.
I can write custom method which extracts it from getJSON method, but I was wondering if there is already method for that, but it's missing from docs.

**Comment by portikM** [comment]
@kikky7 did you find solution? Thanks in advance

**Comment by kikky7** [comment]
@portikM I implemented small custom script which handles my use case. I will share the code this week

**Comment by portikM** [comment]
@kikky7 I ended up writing a small check using getJSON, but if you have a cleaner/more sophisticated solution I'd be interested to take a look. thanks!

**Comment by oggo** [comment]
A better way should be available :\ I am also interested if someone can offer!

**Comment by kikky7** [comment]
This is my solution:

under data:
```
editor: new Editor({
        ...
        onUpdate: () => {
          this.$emit("input", this.getValue());
        }
})
```

under methods:
```
getValue() {
      let content = this.editor.getHTML(),
        json = this.editor.getJSON().content;

      if (
        Array.isArray(json) &&
        json.length === 1 &&
        !json[0].hasOwnProperty("content")
      ) {
        content = null;
      }

      return content;
}
```

**Comment by hanspagel** [comment]
Thanks for sharing!
