### ISSUE TITLE
Mention: onMouseMove, mention pops for 1 second then disappears 

### ISSUE THREAD

**Issue by NitzanShifrin** [scrumpy/tiptap#606]
**Describe the bug**
when adding '@', then clicking with mouse somewhere, then clicking right after the '@', the popup menu pops and disappears 

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.scrumpy.io/suggestions - the official demo
2. Remove all text
3. add Hello @ - then the mention menu opens.
4. **use the mouse** to move cursor between the H and the e, so it will look like H|ello @ 
5. **use the mouse** again to move cursor to right after the '@'
6. the menu pops and disappears

**Expected behavior**
The menu will open up

**Environment**
Your demo

**Comment by siegerts** [comment]
Hey! The settings specifically pertaining to the behavior of the tooltip can be adjusted to your specific use case.  Please see https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Suggestions/index.vue#L220 for the implementation and the [tippy](https://atomiks.github.io/tippyjs/all-props/) for all available options.

**Comment by NitzanShifrin** [comment]
Thanks! Ill look into it.
in my opinion, in your demo, it should be either displayed after the mousemove, or not displayed at all, the blinking part looks buggy.

**Comment by siegerts** [comment]
Hi, I appreciate your comment.  I think that it makes sense to close this as it is not a bug, but a detail. 
The above shared examples are not mine, but the implementation itself.

**Comment by NitzanShifrin** [comment]
Sure, thanks for the answer!
