### ISSUE TITLE
Sanitize unwanted HTML content

### ISSUE THREAD

**Issue by stritti** [scrumpy/tiptap#618]
**Describe the bug**
I created an editor which should use just H3, P, OL>LI and UL>LI elements. It is important because other content would probably damage the application.

**Steps to Reproduce / Codesandbox Example**
1. Create an Editor using just following actions: H3, P, OL>LI and UL>LI 
2. Copy from another HTML-page some HTML-Fragments containing e.g. an hyperlink
3. Paste it in the editor
4. See error: the content is pasted contain the links:

 Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/vue-issue-template-ppmn4?fontsize=14

**Expected behavior**
If there is no action for A-Elements defined, A-elements should be sanitized on copy&paste too.
Or on the other hand it is in addition configurable which elements are sanitized.

**Screenshots**
![image](https://user-images.githubusercontent.com/184547/75521223-90de9a80-5a07-11ea-83f8-e3166d044a3f.png)

**Environment**
 - OS: Windows 10
 - Browser chrome
 - Version  80.0.3987.122
 - Mobile / Desktop: Desktop

**Comment by philippkuehn** [comment]
You are using all extension in your example (including the link extension).

```js
extensions: [
          new Blockquote(),
          new BulletList(),
          new CodeBlock(),
          new HardBreak(),
          new Heading({ levels: [1, 2, 3] }),
          new HorizontalRule(),
          new ListItem(),
          new OrderedList(),
          new TodoItem(),
          new TodoList(),
          new Bold(),
          new Code(),
          new Italic(),
          new Link(),
          new Strike(),
          new Underline(),
          new History()
],
```

If you don't want to support links you have to remove `new Link()`.

**Comment by stritti** [comment]
🙈 oh. yes. you are right. 
I updated the example and it works like a charm. Sorry.
