### ISSUE TITLE
add getNodeAttrs in menu's scope slot

### ISSUE THREAD

**Issue by dongnaebi** [scrumpy/tiptap#622]
**Is your feature request related to a problem? Please describe.**
when I create a node with attrs, I cant edit it

**Describe the solution you'd like**
getNodeAttrs API in menu's scope slot

**Describe alternatives you've considered**
I'm not very familiar with source code

Just like getMarkAttrs

**Comment by gambolputty** [comment]
Hey @philippkuehn, I'm missing this slot property as well. For now I'm getting the attributes of the currently selected node via a computed property. But it's being recalculated every time the selection changes of course :/

```js
  computed: {
    selectedNodeAttrs () {
      const { node } = this.editor.state.selection
      if (node && node.type.name === 'my_node_name') {
        return node.attrs
      }
      return null
    }
  },
```

Or is there a better solution for this already?

**Comment by tvld** [comment]
Is there an example how to use this? I cant figure it out... must be trivial I suppose ))

**Comment by tvld** [comment]
This was indeed simple, needed to upgrade tiptap to latest version and then this works:
```vue
<template v-if="isActive.image()">
        Your image info:
        alt={{ getImageAttr.alt }}
        src= {{ getImageAttr.src }}
        title ={{ getImageAttr.title }}
      </template>
```

**Comment by tvld** [comment]
Except that I also need ``updateAttrs`` .. :-(

Created new issue for that #676
