### ISSUE TITLE
Question: Insert text in nodeView

### ISSUE THREAD

**Issue by jdospina95** [scrumpy/tiptap#627]
I am trying to render a custom node inside tiptap. I need to set the text of the component however I am not sure how to include it inside the toDom. I can include it in the template view and whenever I insert the node into my editor it works fine. The problem is once I load the saved text in the editor it just omits the text of the span.

My template is as follows:

```html
<div class="tiptap-token-input-field">
  <label>
    <input type="text" :id="node.attrs.id" v-model="node.attrs.value" @change="onChange" :readonly="node.attrs.readonly" />
    <span class="placeholder" :class="{ 'not-empty': node.attrs.value !== '' }" v-html="node.attrs.placeholder" />
  </label>
</div>
```

and then my node view is as follows:

```javascript
toDOM: node => {
  const { placeholder, value, id, readonly } = node.attrs;
  return ['div', { class: 'tiptap-token-input-field' },
      ['label', {}, ['input', {
        type: 'text',
        id: id,
        'v-model': value,
        readonly: JSON.parse(readonly),
      }], ['span', {
        class: value !== '' ? 'placeholder not-empty' : 'placeholder',
      }]]];
}
```

When the span is inserted in the dom it has the correct value for the placeholder attribute, however the value is only set in the dom and not in the value of the editor. I know this has to do with the toDom value but I am not quite sure how to assign that value.

I tried setting a v-html value like

```javascript
['span', { class: value !== '' ? 'placeholder not-empty' : 'placeholder', v-html="placeholder" }]
```

which stores the value but then it doesnt render it into the editor. 

I also tried the following way but it crashes my editor when I save and throws `TypeError: Cannot read property 'nodeType' of null`

```javascript
['span', { class: value !== '' ? 'placeholder not-empty' : 'placeholder' }, placeholder]
```

Even though it crashes it is the only solution that generated the expected html value. 

```html
<div class="tiptap-token-input-field"><label><input type="text" id="27" v-model="" readonly="true"></input><span class="placeholder">Test input</span></label></div>
```

Any idea how I can achieve this?

Thanks in advance for your time

**Comment by BrianHung** [comment]
Try adding a `ref="content"` attribute to the template:
```js
<div class="tiptap-token-input-field">
  <label>
    <input type="text" :id="node.attrs.id" v-model="node.attrs.value" @change="onChange" :readonly="node.attrs.readonly" />
    <span class="placeholder" :class="{ 'not-empty': node.attrs.value !== '' }" v-html="node.attrs.placeholder" ref="content"/>
  </label>
</div>
```
I believe the TypeError occurs because ProseMirror is trying to find the node / contentDom to store the content in but it can't without that attribute.

**Comment by jdospina95** [comment]
Unfortunately that doesn't solve the problem. It keeps on throwing the same error. Thanks for your help anyways :+1:

**Comment by shiwei2019** [comment]
Did you get this problem solved? Waht's the solution? Thanks.
