### ISSUE TITLE
Collab example is not working

### ISSUE THREAD

**Issue by joorce** [scrumpy/tiptap#637]
**Describe the bug**
In the example for [Collaborative Editing](https://tiptap.scrumpy.io/collaboration) if I access with two diferent browsers I'm not seeing any changes. In fact when I write in one browser the text in the other browser disappear.

**Steps to Reproduce / Codesandbox Example**
1. Go to [Collaborative Editing](https://tiptap.scrumpy.io/collaboration) with two different browsers
2. Write something in one editor
3. Write something in the other editor
4. The text from first editor is deleted

**Expected behavior**
The changes made in one editor should be reflected in the other editor.
 
**Environment**
Tested in Chrome and Firefox.

**Comment by philippkuehn** [comment]
it's fixed now.

**Comment by promocare** [comment]
Looks like it's not working now, no changes are showing if you open the window on another browser.

Seems like the db_locked.json file is always set to true on the glitch server.

Tested on Chrome and Firefox on MacOs 10.14.6
