### ISSUE TITLE
Paste rules applied inside Code Block

### ISSUE THREAD

**Issue by michalsnik** [scrumpy/tiptap#643]
**Describe the bug**
Pasting code from the editor like WebStorm / VSCode that contains markdown shorrtcuts, e.g. `const something = FOO_BAR_BAZ;` results is creating Code Block that has `<em>` tags inside `<code>` essentially displaying `BAR` italic and removing surrounding underscores `_`.

![image](https://user-images.githubusercontent.com/4093559/77780484-5db61800-7054-11ea-9be3-841ac7885226.png)

This leads to a various other problems parsing the content of code_block.

**Steps to Reproduce**

1. Open Webstorm / VSCode
2. Create new .js file with the following content: 
```js
const something = FOO_BAR_BAZ;
```

3. Copy the code from the IDE
4. Paste in tiptap editor that has `Italic` and `CodeBlock` extensions enabled
5. You should see what I uploaded above.

This issue can be easily reproduced on the tiptap homepage: https://tiptap.scrumpy.io/
Pasting above code and clicking enter causes weird behavior, pasting other code in place of these `<em>` tags too.

**Essentially the behavior of pasting code from the IDE into the TipTap editor is different than pasting the same code directly to opened code block in TipTap editor.**

**Expected behavior**
I would expect that inside of the CodeBlock other paste rules would not apply, same as they don't apply when we try to paste something in already preset CodeBlock. But for some reason that I couldn't crack myself they are applied when the CodeBlock itself is being created via `parseDOM`.

**Environment**
- not relevant

**Comment by philippkuehn** [comment]
Yeah, paste rules have some limitations at the moment. For now you can only disable paste rules:

```
new Editor({
  disablePasteRules: ['italic'],
})
```

**Comment by michalsnik** [comment]
Alright, thanks for the answer @philippkuehn I guess I'll disable parseDOM for code_block then, so the only way to get it is to explicitly create it prior pasting the code from IDE :)

**Comment by michalsnik** [comment]
If anyone else is looking for a solution, here's what I did to mitigate this problem:
```js
import { CodeBlock as BaseCodeBlock } from "tiptap-extensions";

class CodeBlock extends BaseCodeBlock {
  get schema() {
    return {
      content: "text*",
      marks: "",
      group: "block",
      code: true,
      defining: true,
      draggable: false,
      parseDOM: [], // setting this to empty array so the 'pre' tag is not parsed automatically
      toDOM: () => ["pre", ["code", 0]]
    };
  }
}

// ...
```

**Comment by philippkuehn** [comment]
I'm checking now for supported marks (none in a code block) while pasting, so this should be fixed now!
