### ISSUE TITLE
Avoid adding P tag inside LI

### ISSUE THREAD

**Issue by amraei** [scrumpy/tiptap#654]
While running `commands.ordered_list`, it appends a `p` tag inside `li` which is not  proper behavior. You can reproduce it [here](https://tiptap.scrumpy.io/) (use browser inspector). 

**Expected behavior**
`li` tags shouldn't contain anything. I expect this:

``` <li>List item</li>```

not this:

``` <li><p>List item</p></li>```

**Comment by philippkuehn** [comment]
duplicate of #118
