### ISSUE TITLE
How do I get access to the underlying schema?

### ISSUE THREAD

**Issue by zimmicz** [scrumpy/tiptap#656]
Hey,
first of all let me thank you for creating tiptap, it's really great! However, I probably need some clarification on how to use pass content around.
I'm using vuex to store the editor content while writing.

```
new Editor({
        extensions: [
          new Heading({
            levels: [2, 3, 4],
          }),
        ],
        content: this.$store.state.story.text,
        onUpdate: function(payload) {
          this.$store.commit(UPDATE_STORY_TEXT, payload);
        }.bind(this),
      });
```

It stores `getHTML`, `getJSON`, `state` and `transaction` keys as well. I use this together with [prosemirror-utils](https://github.com/atlassian/prosemirror-utils) package inside one of my getters like this:

```
const getters = {
  features: state => {
    return state.story && state.story.text && state.story.text.state
      ? findChildrenByMark(state.story.text.state.doc, state.story.text.state.config.schema.marks.featureMark)
          .map(obj => obj.node.marks[0])
          .filter(mark => mark.attrs[STORY_LINK_LAT_ATTR])
          .map(mark => ({ lat: mark.attrs[STORY_LINK_LAT_ATTR], lng: mark.attrs[STORY_LINK_LNG_ATTR]}))
      : [];
  },
};
```
This works just fine while I'm writing, because the `state.config.schema` is available inside my vuex store. Once I save the content and load it again (see [here](https://gist.githubusercontent.com/zimmicz/c8ce2eadcf15b42fa42198717ade6907/raw/77ef5bd1767814b7bf3a4076d9451346fc500b76/Cartostory%2520test%2520story)), I lose my `getters.features`, because there is no `state.story.text.state` anymore.

Should I just go for some general nested array function, or is there a way to do that with tiptap?

**Comment by kshitizshankar** [comment]
You can use the `this.editor.getSchemaJSON()` to get the schema.
https://github.com/scrumpy/tiptap/issues/368
