### ISSUE TITLE
How do you render html without the Editor ?

### ISSUE THREAD

**Issue by ThomasKientz** [scrumpy/tiptap#657]
Hi, 

I don't find a clear way of how to consume the templates produced with the editor. 

Once your users have created some nice templates with the editor (eg in a "Edit" page), how do you render them if you just want to display them without any editing functionalities (eg in a "Blog" page in a read only mode) ? 

To avoid spin up again a full editor in read only mode (`:editable="false"`), I am trying to naively create a minimalist renderer component that takes in parameters the compiled template string (produced from `getHTML()`) and render it with all my custom nodes/components. But compiling templates downloaded from a backend on the fly its not straightforward. 

How do you process for this kink of scenery ?

Thanks !

**Comment by BrianHung** [comment]
What's the issue with using serialized HTML from `getHTML()`? As long as you have the same css, I would guess the rendered HTML from that should appear the same although with no editing capabilities.

**Comment by ThomasKientz** [comment]
@beeplin You mean with `v-html` ? Cause the serialized html can includes custom components (eg `<div><custom-component /></div>`). How do you do in this case ?

**Comment by ThomasKientz** [comment]
@BrianHung  I think I got your answer wrong.

> What's the issue with using serialized HTML from `getHTML()` ?
There is none. 

If you store it in a DB and retrieve it later, how would you render it ?

**Comment by BrianHung** [comment]
@ThomasKientz 

I think I understand your question better now: you want to render the HTML into normal Vue Components. I would look at [Editor.js](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/Editor.js) and try to isolate the parts which renders the components, like `initNodeViews` and `DOMParser.fromSchema`.

**Comment by ThomasKientz** [comment]
@BrianHung Yes, but I don't understand why I am the first to ask this, I must have missed something.

How do you (tiptap's users) consume the serialized HTML generally ? Editing is on part of the story, you have to consume the content next, don't  you ?

**Comment by BrianHung** [comment]
I just use the editor to render the HTML and use read-only.

**Comment by ThomasKientz** [comment]
Ok got it. I don't know why it did not seem intuitive to me to use the editor to only display content at first glance. I am working on a CMS app where most of users are in a "consume only" mode. At first I thought that the serialized HTML was meant to be used with the `v-html` attribute but I am using custom components. Anyway, I will be using the editor with read-only. Thanks for the clarification.

**Comment by hanspagel** [comment]
That’s what we made the read-only mode for, so it’s fine. 👍️

**Comment by jonathanmach** [comment]
Hi @ThomasKientz, would you care to share any experience you had with this suggested approach (ie. using the read-only mode)?
I was also trying to find something that would be responsible for rendering the JSON without the editor.

I tried to build a minimal project with TipTap using the read-only mode to see what would be the final bundle size and wasn't surprised to see a 316Kb(parsed), gzipped: 96Kb, since it packs everything required for the actual editor with all its editing functionality.
I feel like I'm after a lighter library that is simply responsible for rendering the JSON content to HTML on the client.
@hanspagel, would love to hear your thoughts on this!

Thanks so much in advance, guys!

<img width="1788" alt="Screenshot 2020-11-21 at 19 15 58" src="https://user-images.githubusercontent.com/12788052/99885959-bdd77b00-2c30-11eb-8503-616ae121921a.png">

**Comment by philippkuehn** [comment]
There are three ways:

1. you don't have any nodes with node views: you can simply store and render `getHTML()`

2. you have some nodes with complex node views: store the output of `getJSON()` and render the editor with `editable: false`

3. you have some nodes with complex node views and want to use `getHTML()` to render a string of HTML: provide always a correct `toDOM()` function. this function is used to generate the HTML and provides a proper copy/paste behavior for every node.

**Comment by jonathanmach** [comment]
Thanks for your input @philippkuehn!

It seems like the guys at Storyblok created a HTML render for ProseMirror JSON data:
https://github.com/storyblok/storyblok-js-client#method-storyblokrichtextresolverrender
```js
Storyblok.richTextResolver.render(blok.richtext)
```

What they call `richtext` is just a ProseMirror JSON state.

And this is the parser logic: https://github.com/storyblok/storyblok-js-client/blob/933dc19369fd6b62db42595781a15b957b663e6a/source/richTextResolver.js#L20

This might be useful for anyone looking into writing their own lightweight  renderer.

**Comment by philippkuehn** [comment]
Hey, in v2 there ist also a `generateHTML(json, extensions)` method to generate HTML without an editor instance (so you can use it on a server).

**Comment by jonathanmach** [comment]
That's great news, thanks for sharing @philippkuehn.
I'm really excited and looking forward to the new version and hope to be able to contribute in any way 🚀

**Comment by ThomasKientz** [comment]
I ending up by exporting html with `getHtml()` and rendering it with the editor and `editable: false`.

I am doing this, because I am using custom Vue components as nodes. So I can't render the html as is as I need a way to parse and render the customs nodes (eg `<my-custom-component>some content</ my-custom-component>`). 

A lightweight reader components (to replace  `editable: false`)  would be awesome but I have go no time to implement it and I don't care about bundle size.

**Comment by Winexcel** [comment]
I have similiar issue, i have my custom nodes, for example - spoiler node, which show and hide the content by the button click, this just update attribute "show", and when i toogle editor to read-only mode then click by the button doesn't work, i don't know what i really need to do to fix this problem (https://github.com/ueberdosis/tiptap/issues/1415) . Maybe do you know?

**Comment by thousandsofraccoons** [comment]
> Hey, in v2 there is also a `generateHTML(json, extensions)` method to generate HTML without an editor instance (so you can use it on a server).

I tried to use it, it says: 
``` bash 
ReferenceError: window is not defined
    at doc (C:\server\node_modules\prosemirror-model\src\to_dom.js:194:30)
```

I also tried to add it to jsdom window, still no result.

@Winexcel @ThomasKientz @philippkuehn 
Is it okay to save client-side rendered HTML from `editor.view.dom.innerHTML` and then serve it for preview after reload?

**Comment by hanspagel** [comment]
https://www.tiptap.dev/api/utilities/html ✌️

**Comment by Winexcel** [comment]
> > Hey, in v2 there is also a `generateHTML(json, extensions)` method to generate HTML without an editor instance (so you can use it on a server).
> 
> I tried to use it, it says: 
> ``` bash 
> ReferenceError: window is not defined
>     at doc (C:\server\node_modules\prosemirror-model\src\to_dom.js:194:30)
> ```
> 
> I also tried to add it to jsdom window, still no result.
> 
> @Winexcel @ThomasKientz @philippkuehn 
> Is it okay to save client-side rendered HTML from `editor.view.dom.innerHTML` and then serve it for preview after reload?

If you use custom extensions that use events, this won't work for you

**Comment by BroJenuel** [comment]
> There are three ways:
> 
> 1. you don't have any nodes with node views: you can simply store and render `getHTML()`
> 2. you have some nodes with complex node views: store the output of `getJSON()` and render the editor with `editable: false`
> 3. you have some nodes with complex node views and want to use `getHTML()` to render a string of HTML: provide always a correct `toDOM()` function. this function is used to generate the HTML and provides a proper copy/paste behavior for every node.

I dont know if any of you notice, with the help of VS Code IDE I was able to find `generateHTML` function that accepts the json generated data. Since I am using the vue, I can do this, I dont know if this exist on other framework but works on me.
```js
import {  generateHTML } from "@tiptap/vue-3";
const jsonData = {}; // the generated json from the editor
const html = generate(jsonData); // then I just render this on the html
```

the reason Im json json to the database is becuase of the xss issue.

**Comment by gitcatrat** [comment]
There is a fourth option and it's usually recommended by some rich text editors that I've used/evaluated.

Why proposed solutions might not work for you?
* `editable: false` is a footgun for many apps - you're probably doubling your bundle for read-only i.e most users (_5x in my case_) and running the editor for 100s of e.g posts in a list view.. Maybe it uses super light code path but still..
* it's discouraged to store HTML and inject it dangerously in most rendering frameworks (not to mention complex elements)

**Solution:** write your own renderer. I didn't say it's the easiest solution. 🤠
```js
// super basic example in JSX
function renderElement(el) {
  const children = el.content.map(child => renderElement(child));

  // few handled cases to give a taste
  if (el.type === 'text') return el.text;
  if (el.type === 'paragraph') return <p>{children}</p>;

  return null;
}

function Document(props) {
  return (
    <div>
     {/* props.document === {type: "doc", content: [...]} */}
     {props.document.content.map(child => renderElement(child))}
   </div>
  );
}
```

Few points to make:
* sorry folks, don't have working solution to give you, still evaluating tiptap and messing around
* use the same CSS classes for editor elements and renderer to get identical appearance
* more complex nodes probably have to be rewritten in your framework of choice (or share logic with interactive node)
* `marks` is a bit pain in the bum with tiptap JSON structure, you need to lift them up to generate decent HTML 
see: https://github.com/ueberdosis/tiptap/discussions/3377
* I just started writing mine (done it for other editors), so it's possible that the issues don't end there

**Comment by cluah** [comment]
Hi. So far there is no way to do it? Thanks.

**Comment by michelson** [comment]
we did that on Dante3, (tiptap based editor) it let you render custom components (react)
https://github.com/michelson/Dante/blob/main/packages/dante3/src/renderer.tsx
demo at: https://www.dante-editor.dev/posts/renderer

**Comment by bkyerv** [comment]
I think one of the reasons a built in renderer has not been built by the team behind tiptap is that a renderer that would cover all edge cases in the limit will be the editor component. Therefore I guess if we need any type of lighter version of the rendered we will have to implement it ourselves depending on the case at hand

**Comment by BrianHung** [comment]
Would look into https://github.com/nytimes/react-prosemirror

**Comment by abdullahmehboob20s** [comment]
you can do 


```javascript
const content : "<p>Some text here</p>";

return (
   <div dangerouslySetInnerHTML={{ __html: content }}  />
)
```

**Comment by LuizPelegrini** [comment]
would love to know whether there's some kind of block renderer built for tiptap, much like what we have for Editorjs [here](https://github.com/dev-juju/EditorJS-React-Renderer) and [here](https://github.com/moveyourdigital/editorjs-blocks-react-renderer)

**Comment by seeARMS** [comment]
Just adding a note that I would also love to use some type of renderer. The approach I'm taking:

- store the generated HTML alongside the JSON
- on public page load, render the HTML (so it's immediately available on page load)
- dynamically load the TipTap editor in readonly mode
- when TipTap is initialized, replace the statically rendered HTML with the tiptap editor in readonly mode

The downsides of this approach:
- the rendered HTML is not always exactly what we want. For example, I want to use `next/image` to optimize images, but it doesn't make sense to store the `next/image` HTML; so we store the `img` component, but that cases the full-size unoptimiezd image to be fetched on page load
- this of course bundles all TipTap extensions and ships them to the client, which is not ideal. Some extensions (eg the emoji one, or the LaTeX one) are large, but not many posts we're displaying use them, so we're shipping them needlessly

Some ideas I've toyed around with to improve this:
- create a custom renderer, as explained above
- traverse the tiptap JSON for a post and dynamically import **only** the extensions used in any given post. I'm hopeful this would not bundle any unneeded extensions

**Comment by jack-szeto** [comment]
I found a way to render HTML from the TipTap editor without worrying about style collisions. I used an `iframe` to keep things isolated. Here's the code:

```tsx
const SimpleHtmlRenderer = ({ html }: { html: string }) => {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  useEffect(() => {
    const iframe = iframeRef.current;
    if (iframe) {
      iframe.onload = () => {
        iframe.style.height =
          iframe.contentWindow?.document.body.scrollHeight + 'px';
      };
    }
  }, [html]);
  return (
    <iframe
      ref={iframeRef}
      srcDoc={html}
      style={{ border: 'none', width: '100%' }}
      sandbox="allow-same-origin"
    />
  );
};
```

This way, I don't have to worry about any style collisions. The iframe's height adjusts automatically based on its content, so it fits nicely.

Hope this helps!

**Comment by nperez0111** [comment]
This will be the official supported solution: https://github.com/ueberdosis/tiptap/pull/5528

It is usable now by installing the @tiptap/static-renderer package commented by the pkg-pr-new bot
