### ISSUE TITLE
Question: How can I change highlighted text into link tags with modifier keys?

### ISSUE THREAD

**Issue by edisonywh** [scrumpy/tiptap#668]
So I want to be able to add a link to a highlighted text, similar to the example on Link on the website, and that one is pretty straightforward. However I also want to add `Cmd+K` as a keyboard hotkey to bring up the same prompt menu.

I tried to extend the current Link and then adding my own `keys`, which made the hotkey work, however I couldn't figure out how to actually turn the highlighted node into a link node (the example on the website uses the `commands` from Editor, which I don't get access to inside `keys`). Any help here?

**Comment by BrianHung** [comment]
`state, dispatch, view` are all given as arguments to keys. Using [state.selection](https://prosemirror.net/docs/ref/#state.Selection), you should be able to the position of the highlighted node, and then use [`tr.setNodeMarkup`](https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup) to apply the link mark to the node.

**Comment by edisonywh** [comment]
Ah awesome! Thanks for the pointers Brian, I'll give it a try and see how that goes, cheers :)

**Comment by edisonywh** [comment]
Hey @BrianHung, not sure if I'm doing something wrong here, but I don't see state/dispatch/view in keys.

```js
import { Link as BaseLink } from 'tiptap-extensions';

export default class Link extends BaseLink {
  keys(state) {
    return {
      'Mod-k': () => {
        console.log(state)
        // {type: MarkType, schema: Schema}
      }
    }
  }
}
```

When I log it I only see MarkType & Schema being printed out, what am I missing?

**Comment by BrianHung** [comment]
@edisonywh Change the arguments to be 
```js
'Mod-k': (state, dispatch, view) => {
  console.log(state, dispatch, view);
}
```

**Comment by philippkuehn** [comment]
btw you have always access to `editor`

```
'Mod-k': () => {
  console.log(this.editor);
}
```

**Comment by edisonywh** [comment]
@philippkuehn that's amazing! Couldn't figure out how to use the selections to setNodeMarkup referred to the [doc here](https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup) but wasn't sure how to actually use it, but using `editor` directly worked perfectly! It's basically doing the exact same thing as what the menubar is doing.

Here's my piece of code that worked if anyone else is struggling:

```js
import { Link as BaseLink } from 'tiptap-extensions';

export default class Link extends BaseLink {
  keys() {
    return {
      'Mod-k': () => {
        const command = this.editor.commands.link
        this.handleAddLink(command)
      }
    }
  }

 handleAddLink(command) {
    const url = prompt('Enter the url you want to link to')
    if (url !== null) {
      if (!this.isValidUrl(url)) {
        alert(`${url} doesn't seem to be a valid URL!`)
      } else {
        command({ "href": url })
      }
    } else if (url === null) {
      command({})
    }
  };

  isValidUrl(string) {
    try {
      new URL(string);
    } catch (_) {
      return false;
    }

    return true;
  }
}

```

Thanks for the help :)
