### ISSUE TITLE
get raw content

### ISSUE THREAD

**Issue by DebaPrasad14** [scrumpy/tiptap#675]
I am trying to use Tiptap and on content update, I need to find the raw content data as well as html and json. But after research I found onUpdate, you have defined two methods getHTML() and getJSON(). But how can I find raw content what user typed ?

**Comment by philippkuehn** [comment]
what do you mean with raw content? you get get your content as html and json as you already found out. There is also an `onTransaction` event, where you can listen for **any** changes to the state of your editor.

**Comment by DebaPrasad14** [comment]
@philippkuehn raw content means- let's say I type "Hi Jonas" in the editor. so I want to keep track of texts which is written by me/user only( here- Hi Jonas). But I can manipulate getHTML() or getJSON() functions value to get what I need. But my question is, is there any method like above two so I can get simple texts without any tags or anything?

**Comment by akirarika** [comment]
> @philippkuehn raw content means- let's say I type "Hi Jonas" in the editor. so I want to keep track of texts which is written by me/user only( here- Hi Jonas). But I can manipulate getHTML() or getJSON() functions value to get what I need. But my question is, is there any method like above two so I can get simple texts without any tags or anything?

Does this work for you?

```javascript
new Editor({
    // ...
    onUpdate(e) {
        console.log(e.state.doc.textContent);
    },
});
```

**Comment by DebaPrasad14** [comment]
> Does this work for you?
> 
> ```js
> new Editor({
>     // ...
>     onUpdate(e) {
>         console.log(e.state.doc.textContent);
>     },
> });
> ```

No, its not working for me and its because if I print 'e' inside onUpdate(), then it comes undefined.

**Comment by philippkuehn** [comment]
@DebaPrasad14 
```js
new Editor({
    // ...
    onUpdate({ state }) {
        console.log(state.doc.textContent);
    },
})
```

**Comment by DebaPrasad14** [comment]
@philippkuehn Thank you so much. This is what I wanted.
And please create a good documentation as it is very difficult and time consuming to customize it.

Again thanks a lot for your quick response and for tiptap :)

**Comment by philippkuehn** [comment]
@DebaPrasad14 tiptap v2 comes with super awesome docs 🙌

**Comment by DebaPrasad14** [comment]
@philippkuehn any approx. date/month by which we can expect v2 ?

**Comment by NiuNiuNiu919** [comment]
正则表达式手动去除html标签
onTransaction: (payload) => {
          console.log(payload.getHTML().replace(/<\/?[^>]*>/g, ''))
}

**Comment by kimbaudi** [comment]
I had to change `state` to `transaction` for this to work

```js
new Editor({
  onUpdate: ({ transaction }) => {
    console.log(transaction.doc.textContent);
  },
});
```

**Comment by Supratentorial** [comment]
Seems to be an `editor.getText()` method which returns the raw text of the editor.

**Comment by kongweiying2** [comment]
Is there a method for getting text but without instantiating a new instance of the Editor?

**Comment by lopermo** [comment]
> @philippkuehn Is there a method for getting text but without instantiating a new instance of the Editor? I checked the documentation and couldn't find anything like this.
> 
> EDIT: I guess you would have to do new Editor().getText() since you need the extensions to be able to parse the text properly.

Did you ever find a solution for this? Struggling to escape the HTML to plain Text without initializing an editor instance...

**Comment by runthis** [comment]
@lopermo it is `getText()`
