### ISSUE TITLE
Menububble doesn't disappear on blur if editor is readonly

### ISSUE THREAD

**Issue by xaksis** [scrumpy/tiptap#68]
When the editor is read-only (contenteditable is false) blur event is never triggered and the menububble doesn't hide.

**Comment by philippkuehn** [comment]
Closed due to inactivity

**Comment by philippkuehn** [comment]
Oh sorry! Could you setup a sandbox or show me a gif of that bug? Whenever the editor is read-only there should be no menububble at all.

**Comment by xaksis** [comment]
Sure! I'll create one in a few days, mind keeping it open till then? I'll close it if I cannot reproduce it in a sandbox.

**Comment by xaksis** [comment]
I upgraded and could not reproduce the behavior. Will close this now. Thank you.
