### ISSUE TITLE
Is it possible to implement ruby?

### ISSUE THREAD

**Issue by Interhead** [scrumpy/tiptap#702]
**Is your feature request related to a problem? Please describe.**
I want to implement ruby, but cannot find it in extensions.
`<ruby>RUBY<rp>(</rp><rt>ruby</rt><rp>)</rp></ruby>`

**Describe the solution you'd like**
I want ruby to be added to extensions.

**Describe alternatives you've considered**
Is it possible to implement ruby by custom extensions?
I tried but failed.

**Comment by Interhead** [comment]
Solved by

- custom extensions
- prosemirror-utils

**Comment by aehlke** [comment]
Is this really solved as in tested? It's very common for these text editor libs to handle ruby poorly especially with selection, moving cursor etc.

**Comment by aehlke** [comment]
can we please reopen this - it appears to still be blocked on https://github.com/ueberdosis/tiptap/issues/986 so it is not solvable as indicated
