### ISSUE TITLE
Bind menu bar to multiple editors 

### ISSUE THREAD

**Issue by mvind** [scrumpy/tiptap#708]
Hi! 

Is it possible to bind a menu bar to two editors. I have two editors `editor_front` and `editor_back` in my component and I would like to have one menubar which I could use on both. 

I've tried ` <editor-menu-bar :editor="editor_front, editor_back" v-slot="{ commands, isActive }">`  and ` <editor-menu-bar :editor="editor_front editor_back" v-slot="{ commands, isActive }">`   but that does not work. 

Is this possible?

**Comment by mvind** [comment]
Still banging my head against the wall trying to solve this. I'm thinking the direction is make some sort custom node.

**Comment by BrianHung** [comment]
Why do you need two editors? Looking at https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/Components/EditorMenuBar.js, there doesn't a seem a clean way to bind a menu bar to two editors, e.g. what would be the menu bar `focus` since you can only focus on one editor at a time?

**Comment by mvind** [comment]
I need two editors because I need two independent user inputs. Anyways, I'm still working on a solution. Basically I found two ways to solve this problem. 

1) The naive hack would be to render a menubar for each editor, and the use conditional css to render the menubar of the focused editor. 

2) The proper hack would to write a custom menubar, and using the editor method `onFocus` to determine the focused editor, and then apply marks. 

I'm currently working on a demo for 2).

**Comment by mvind** [comment]
Update, I could not figure out how to apply custom marks programmticly. I kept wanted to use `addMark` inside vue method both I got some errors which I could not fix.

So now I'm just rolling with the naive hack. This looks like this: 
```
<template>
  <div class="editor">
    <editor-menu-bar :editor="editor_front" v-slot="{ commands, isActive }" 
    v-if="editor_front.focused">
       <div class="menubar">
      </div>
    </editor-menu-bar>
    <editor-menu-bar :editor="editor_front" v-slot="{ commands, isActive }" 
    v-if="editor_back.focused">
       <div class="menubar">
      </div>
    </editor-menu-bar>
    <editor-content class="editor__content box-container" :editor="editor_front" />
   <editor-content class="editor__content box-container" :editor="editor_back" />
  </div>
</template>
```
This has the added "benefit" of not not rendering the menubar if none of this editors are focused, which is kinda cool I guess... 

I will close this issue now.

**Comment by kongweiying2** [comment]
@mvind Old issue but couldn't you just use the Bubble Menu which will only appear if text is selected on the relevant editor?
