### ISSUE TITLE
Stop tiptap from pre-fetching all images when initialized with HTML content

### ISSUE THREAD

**Issue by kfirba** [scrumpy/tiptap#713]
**Is your feature request related to a problem? Please describe.**
Given we are using tiptap as a WYSYWG editor feeding it HTML and exporting HTML out of it, there is an **major** issue with the way `tiptap` parses the initial HTML string.

Given we have the following HTML:

```html
<p>
    Text <img src="foo.jpg">
    Text <img src="bar.jpg">
</p>
<figure>
    <img src="baz.jpg">
</figure>
```

When tiptap passes this string to `ProseMirror`'s parser, it will wrap the string in a `<div>` to ensure a single root element. The wrapping is very trivial, it uses `div.innerHTML = content` to do so. However, this is where the issue lays.

For some reason (unknown to me) when we create an in-memory element and load in `img` in it, the browser attempts to fetch the image! The `div` is not in the DOM in any way, nor the `img` but the browser still attempts to load the image. Given the HTML structure we have above, when `tiptap` calling `div.innerHTML = content` in its `createDocument` method, it will actually trigger 3 network requests which is a big no-no especially when you may have over 60 images in that string (in my case it may be over 100 images...)

**Describe the solution you'd like**
The best solution I've found for now is quite interesting. We can use the browser's native [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to get an HTML node without fetching any image:

```js
const htmlString = `<div>${content}</div>`;
const parser = new DOMParser;
const element = parser.parseFromString(htmlString, 'text/html').body.firstChild;
// pass the div to ProseMirror's parser at this point...
return DOMParser.fromSchema(this.schema).parse(element, parseOptions)
```

I've also opened a question about this in Stackoverflow, just in case anyone is interested: https://stackoverflow.com/questions/62019538/preventing-images-from-being-downloaded-when-they-are-inside-an-in-memory-elemen

I hope this can be fixed soon! If you are willing to fix this, I wouldn't mind creating a PR or you could just edit 3 lines in `Editor.js` at `createDocument` method.

Thanks!

**Comment by philippkuehn** [comment]
fixed in https://github.com/scrumpy/tiptap/pull/747

**Comment by kfirba** [comment]
@philippkuehn please see my comment on #747

**Comment by thesiti92** [comment]
this seems to still be an issue. when calling `getHTML` no matter what tiptap fetches img src's. In my case its an issue because we're letting users have images controlled by template variables, so when tiptap fetches the img, the url isnt valid yet and produces a 404
