### ISSUE TITLE
XSS issue when importing through getHTML() function

### ISSUE THREAD

**Issue by vido4** [scrumpy/tiptap#724]
**Describe the bug**
When using the editor and importing data which was stored as raw HTML string (usually by getHTML() function) it is possible to inject javascript code there and create a stored XSS in the application using the editor.

The code that is causing the issue seems to be that one [Editor.js:274-276]
```
if (typeof content === 'string') {
      const element = document.createElement('div')
      element.innerHTML = content.trim()
```

Most javascript code cannot be injected through .innerHTML property, but by using events of `<img>` tag it is possible. Simplest payload that can be used is `<img src=x onerror=alert(1)>` 

The code is executed in the moment of assigning to innerHTML property and only then passed on to the parser which properly sanitizes input.

**The solution:**
The simplest one seems to be creating element not in context of a document. That solution was already proposed in #713  which is directly related to this issue and should fix both of them.

**Comment by jnguyen32** [comment]
Is this project not being maintained? Surprised there is no response to this.

**Comment by jnguyen32** [comment]
```
import {Editor} from 'tiptap';
import {DOMParser as ProseMirrorDOMParser} from 'prosemirror-model';

export default class MyEditor extends Editor {
    createDocument(content, parseOptions = this.options.parseOptions) {
        if (content === null) {
            return this.schema.nodeFromJSON(this.options.emptyDocument)
        }

        if (typeof content === 'object') {
            try {
                return this.schema.nodeFromJSON(content)
            } catch (error) {
                console.warn('[tiptap warn]: Invalid content.', 'Passed value:', content, 'Error:', error)
                return this.schema.nodeFromJSON(this.options.emptyDocument)
            }
        }

        if (typeof content === 'string') {
            const htmlString = `<div>${content}</div>`;
            const parser = new DOMParser;
            const element = parser.parseFromString(htmlString, "text/html").body.firstChild;
            return ProseMirrorDOMParser.fromSchema(this.schema).parse(element, parseOptions)
        }

        return false
    }
}
```

**Comment by philippkuehn** [comment]
fixed in https://github.com/scrumpy/tiptap/pull/747
