### ISSUE TITLE
Pasting text with a link makes it italic

### ISSUE THREAD

**Issue by rikas** [scrumpy/tiptap#725]
**Describe the bug**
If you have Link and Italic extensions activated in your editor, when pasting text with links it correctly adds the mark for the link but also adds `<em>` tags.

**Steps to Reproduce / Codesandbox Example**
1. Setup an editor with minimal configuration (only `new Link()` and `new Italic()` as extensions is enough).
2. Paste something like "http://www.google.com is a link" to the editor
3. Everything after "http://" is italic for some reason.

I have a code sandbox with the setup, here: https://codesandbox.io/s/restless-grass-yjzkk?file=/package.json:299-305

This is even happening in the examples in https://tiptap.scrumpy.io/ and https://tiptap.scrumpy.io/links.

It doesn't happen if the Italic extension is not loaded, so I guess it has something to do with the pasteRules for Italic?

**Environment**
Versions that I'm using:
* tiptap 1.27.1
* tiptap-extensions 1.29.1

**Comment by Mansehej** [comment]
Have you tried this out on a different browser?
I suspect that it's either a browser/ font problem on your end as I am unable to reproduce the <em>, even on your codepen.

**Comment by rikas** [comment]
@Mansehej I have no clue what it was, but you're right. Today I'm not able to reproduce it anymore 😮 

Closing the issue.
