### ISSUE TITLE
Editor styling buttons reload the page

### ISSUE THREAD

**Issue by gotters** [scrumpy/tiptap#729]
**Describe the bug**
Clicking on an editor style button causes the page to reload (the first time)

**Steps to Reproduce**
1. Add the component to a page and include styling buttons
2. When loading for the first time clicking on one of the buttons causes the page to reload
3. After reloading, clicking on the styling button works as expected - ie styles are applied
4. NOTE: This almost always only happens on the FIRST load but unfortunately it doesnt always happen, making it hard to debug.
5. If you can't reproduce then see the Testing info below

Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/vue-issue-template-h0g28

**Expected behavior**
Styling buttons should never reload the page but should just apply the styling as expected

**Testing**
1. Login to mymemry.com with 
demo@mymemry.com
demo123
2. Click on New Memry
3. In the editor highlight some text and click BOLD. Page will reload. Subsequently it will work fine.
To reproduce again, logout, close the browser tab, reload the site and login again and it will happen again. But only the first time.

**Environment**
 - Browser chrome
 - Version
    "tiptap": "^1.25.0",
    "tiptap-extensions": "^1.27.0",

**Comment by kkolasinski** [comment]
I've followed the **Testing** path and took a quick look at the source code.
If I'm not mistaken, when you have a `button` element inside of a `form` element, it automatically submits the form after clicking the button.

There are multiple ways of fixing the issue but I think the best approach would be adding the `type="button"` attribute to each button that is being rendered as the Text Editor button inside the  `.menubar` `div` container

**Comment by gotters** [comment]
@kkolasinski  I took your advice and it worked!
Thanks so much!
