### ISSUE TITLE
Suggestion @ with Tippy.js and Fuse.js , search doesn't return the correct objects affecting suggestions

### ISSUE THREAD

**Issue by oliviermills** [scrumpy/tiptap#749]
**Describe the bug**
Using latest fuse.js@6 (possibly early versions >3) the results returned are `[ { item : {.. }, refIndex : ...} ...]` not ` [ {...}, {...} ]`, so we need to return just the item prop from the fuse search results, for tippy to have the correct object: `return fuse.search(...).map((it)=> it.item)`

**Steps to Reproduce**
1. install fuse.js v6 and go to  the suggestions example
2. type @ in the content and start typing to trigger the fuse.js search.. results appear but malformed or empty

**Comment by philippkuehn** [comment]
fixed in #750
